yum::yum_repo_file: 'swrepo.yum'

# Initial Dev OUD Administrator Password.  
oud_admin_passwd: '{SHA}rwv+eRSH7hACOhaKqDsNI4cyrRE='

pswdfile_value: >
    ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEASBxNz7KEKQT8P7Ga0kANnkxVQNsdpUPlJoAE
    sJzXUJ65QaBzsVpvjQGxdKPGszEZ5XS4ceAovyUqcJ2uFgiL+oOplFV/LreP
    IvAJqpTutdvUepLVZIeiGmyG4imQDaf6ZSfpmsEvqf503TvX1Uldo/nPzy6X
    FAUMonYqsngwLMD30KtH4IwfoNCy89/0DGoVLB8CdEOFnJPgZvpKhKybdRHJ
    y5AgmY3LGhAZ74i5cMo/slLXdbHCW5tE+xzgbX9lFGFeDYjpOPpOAWL/NYba
    fDR3O1FFswN2sJQourxOzItWpYzgWKk0GU4Q/42NJVF79ogBhZfoAa/TgVfD
    YhrwkDA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBDgH9L/0aJh9VanwqEh
    AbeWgBDY+1qY8RDXtOnkYOePiNcX]

oud_console::weblogic_passwd: >
    ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAgWOkXGoiKj/KEiIYv74GtjB7Ez2q5ZNpvhNQ
    2a1NFIWBH2pi4zAkpI0B1vHl0n4mxTbuPwwKPg8i5OgBSwUwnPgsobqDcfsd
    XT+UZS148zx7zvDnZ2hBDb0Ebz6PlH8CiDZQeb+FvriCXqhUOZcIp0tuWlaw
    4XJXVT4NsHrUoVZ4VcfKB4THbHieqAOPw+XDuTb1fD+y+hwd3ZsgCaIcmF+N
    i2kGCNSj6uh4AwpdahgHIFZpOXF9maJxmL+OrV0EaDheQht3VtjpbTcHPtAf
    Ax+jN5m6B/MBRwAulR8HounIyVbfeQPpQ0irtPgKaVqM6Xe0PWC6NsPNcuSY
    2KNG7jA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBCiQe66Pou1bdVaIN+I
    So0qgBDPgGf6qo2UnNQyt5doMRJz]

# Define JDK location (Java_Home) for OUD processes.
oud_local_jvm: '/sw/pkg/java/jdk1.7.0_111'
profiles_webeng::default::java_name: 'jdk-7u111'
profiles_webeng::default::java_source: 'http://cplnxrepo1.sherwin.com/webroot/installers/webeng/oracle/java/jdk-7u111-linux-x64.tar.gz'


        
