
# OUD Administrator Password.  
oud_admin_passwd: '{SHA}pwRAkSEVhtG2hvY0foP5GJG1fHI='

pswdfile_value: >
    ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAEM/aO9nj5tjfK2yJ8Cn4Xz4+q8YlXk24Z9Vh
    H+K48uAg0bZM8pBp988n7O7toFNuWouvZB4RI1rQAb1VLx2FkxaT/7AD/7UL
    MreP67dY6A2wnaJlo8nm/eieBgBs3qFkzHCBdTUvYfngt2uMNF5mQ9mPKYN1
    e5d6HdHkJe6Ywmt3w7D89915foYhZ9KSMaM0oU1ofmpBzbItdbdJtOewG2Dp
    fZOYir8qwIVVZmG3obdMeDkqOGdpJUfn3nEJDvQ+F7z6T/fUspGs6Cq6gNEN
    az73WijZPc+NA7VBEGYFdOYT7WpsT6AxXOuDAQYNKhAVOLCRbdVh1+WawrDb
    84aS2DA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBDGZ35IbczGSrsLSC5u
    uMGpgBCKW21Vb8y8kbFv7rP5bc1j]

oud_console::weblogic_passwd: >
    ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAgWOkXGoiKj/KEiIYv74GtjB7Ez2q5ZNpvhNQ
    2a1NFIWBH2pi4zAkpI0B1vHl0n4mxTbuPwwKPg8i5OgBSwUwnPgsobqDcfsd
    XT+UZS148zx7zvDnZ2hBDb0Ebz6PlH8CiDZQeb+FvriCXqhUOZcIp0tuWlaw
    4XJXVT4NsHrUoVZ4VcfKB4THbHieqAOPw+XDuTb1fD+y+hwd3ZsgCaIcmF+N
    i2kGCNSj6uh4AwpdahgHIFZpOXF9maJxmL+OrV0EaDheQht3VtjpbTcHPtAf
    Ax+jN5m6B/MBRwAulR8HounIyVbfeQPpQ0irtPgKaVqM6Xe0PWC6NsPNcuSY
    2KNG7jA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBCiQe66Pou1bdVaIN+I
    So0qgBDPgGf6qo2UnNQyt5doMRJz]

# WebSphere Commerce password 
wcs_user_passws: '{SHA}L8MInmibFUH7XzvE4PgUj7e1muw='

# Define JDK location (Java_Home) for OUD processes.
oud_local_jvm: '/sw/pkg/java/jdk1.7.0_111'
profiles_webeng::default::java_name: 'jdk-7u111'
profiles_webeng::default::java_source: 'http://cplnxrepo1.sherwin.com/webroot/installers/webeng/oracle/java/jdk-7u111-linux-x64.tar.gz'


# ###############
# List of Groups for SoftLayer nodes.
softlayer_os_groups: |
  # Groups Allowed Access.
  +:(osadmin):ALL
  +:(security):ALL  
  +:(oudadmin):ALL
  # Allow crontab for oudadm
  +:oudadm:cron crond:0 

# ###############    
# Sudoers.d configuration (additive because its a hieradata array).  
softlayer_sudo::configs:       
    'oudadmin':
        'content'   : "%oudadmin ALL=(ALL) PASSWD: ALL"
        'priority'  : 15
        