
# OUD Administrator Password.  
oud_admin_passwd: '{SHA}fZFUr6q0ieWXYh8eG68GDhyXO30='

pswdfile_value: >
    ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAcOlc0ufQ/aFb8jm6itRUTcrpslgLZNC3U+N1
    5z47bx7y51Q3BSBbxLe/wAiwhcok3DcoHhMsUrTcqxhVAkVaAjEvSkKsz/lg
    xQe9ps3zSdzhZWRlUVTrUpP1t9oaaL+luYEHlt6fU39j/p/menNhZQ/NSUOc
    cd8wtyhtK2jHVSpvvaduJK1kWdGB867zK2WY9BwFLxwrumWR8Vyak/TFYYRf
    v6MJJT4BLU6AcrngsqmTS45YGg92GvETfDYgibtJAGjOjbvkUYuIbE51UYFt
    oJKbSnyXBGEjbKwTcAOu0LDVXU3Z1WoEgWwiyNNI56orUUrxt18dwX4Ow30+
    BBaNGjA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBAI5n8UCYrvUtPZJqwt
    GjBDgBD1ahpuLNIw2vIADZMotQEG]

oud_console::weblogic_passwd: >
    ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAJ89DMhDjrtyPYMyo48r++aAFTr2TEQvUb0Ci
    vbHA0YKhaDLib03fzRfpp5n6QQ+Pgf/om/Icl8v0otxGZ48tsKM5ln3AP2h5
    1PwRSkDf4UqKGc8SgrCs505l+iebv3sZ4YvyeARHPBkWuiT3kAFPo/XOyLt+
    /Nenf8PyN0eVkYpboSw3Vm8Wm81M51A56Wbz+im+EVfaRDc5smaoUbBrkxzE
    AQJ29g6fYULclDJ7nab5HeDMDsq/pfX85EzeH27A94di95C5c5FtI3B1ANQE
    TXJ9LwKpLfr0q+R9Z+z7EO5fNjnYtYDSqhHXXsLzuCrn5Zlq1fu+MTJFL2Pq
    uPshjzA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBBwB9D4/d+7sYslsewh
    K3IQgBD5xdYGegU72orOhiSdJRwS]

# WebSphere Commerce password 
wcs_user_passws: '{SHA}FaafuXAzRqCYDkSCSHu1kDZR+7g='

# Define JDK location (Java_Home) for OUD processes.
oud_local_jvm: '/sw/pkg/java/jdk1.7.0_111'
profiles_webeng::default::java_name: 'jdk-7u111'
profiles_webeng::default::java_source: 'http://cplnxrepo1.sherwin.com/webroot/installers/webeng/oracle/java/jdk-7u111-linux-x64.tar.gz'


# ###############
# List of Groups for SoftLayer nodes.
softlayer_os_groups: |
  # Need to allow ROOT from ALL for OUD Nodes.
  # In case OUD LDAPs are not available.
  +:root:ALL
  
  # Groups Allowed Access.
  +:(osadmin):ALL
  +:(security):ALL  
  +:(prdoudadmin):ALL
  # Allow crontab for oudadm
  +:oudadm:cron crond:0 

# ###############    
# Sudoers.d configuration (additive because its a hieradata array).  
softlayer_sudo::configs:       
    'prdoudadmin':
        'content'   : "%prdoudadmin ALL=(ALL) PASSWD: ALL"
        'priority'  : 15
 