classes:
  - profiles_unix::gsc::oracle8::rac
  - sw_puppet_ansible_dmw


postfix::enabled: 'true'


sw_util::module_param::bool_exec_augeas_kernel: true
sw_util::module_param::bool_exec_augeas_limits: true


oracle_build8::kernel::vm_swappiness: 0
oracle_build8::kernel::vm_nr_hugepages: 9728


oracle_build8::kernel::kernel_shmall: 1073741824
oracle_build8::kernel::net_core_wmem_max: 4194304
oracle_build8::kernel::net_core_rmem_max: 4194304
oracle_build8::kernel::net_core_wmem_default: 4194304
oracle_build8::kernel::net_core_rmem_default: 4194304
oracle_build8::kernel::pid_max: 139264

access_conf::access:
  - '+:root:LOCAL'
  - "+:%{hiera('sw_snow_disc:snow_user')}:%{hiera('access_conf::snow_ips')}"
  - "+:%{hiera('sw_puppet_ansible:ansible_user')}:%{hiera('access_conf::ansible_ips')}"
  - "+:%{hiera('sw_puppet_ansible_dmw:ansible_user')}:%{hiera('access_conf::ansible_ips_dmw')}"
  - '+:(sa-local):LOCAL'
  - '+:(sa-remote):ALL'
  - '+:(gg-adm-gcdunix):ALL'
  - '+:(gg-adm-oracle-oem):ALL'
  - '+:(gg-adm-dba-ops):ALL'
  - "+:sa-qualys-linux:%{hiera('access_conf::qualys_ips')}"
  - "+:sa-cyberark-linux:%{hiera('access_conf::cyberark_ips')}"
  - '+:oracle:LOCAL %{::fqdn} 127.0.0.1 10.140.32.22 10.148.5.81 10.140.32.21 10.148.5.80 10.148.37.153 10.148.37.152 10.148.37.150 192.168.99.153 192.168.99.152 192.168.99.150 10.148.5.79 10.140.19.164'
  - '+:grid:LOCAL 10.148.37.153 10.148.37.152 10.148.37.150 192.168.99.153 192.168.99.152 192.168.99.150'
  - '+:tricore: 64.94.254.0/29'
  - '-:ALL:ALL'

oracle_build8::rac::ssh::grid_pub_key: >
    ENC[PKCS7,MIIDvQYJKoZIhvcNAQcDoIIDrjCCA6oCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAjBLhAGyb+3p/FvZTk6tV2wX62SUDPIa4lheO
    1VC7ibXAtlF6PgRGtC0QEBmARX5UniX/Nnm25HNfNACoM4wFdYQBg151ZRLk
    yqkoG8Pe1nsqtm7csgShrHjelZM4VIwDo74y+gIXHFb600lCwjIlOlFc/TrJ
    1hHP16dW7nUsBDt/olOpkB1KouI9VW1q/qH4N6cqGsep0PibbJTrWNhNZ/wf
    3bqnCYJjyCl+vX0+qvAOQrN7pFISQT7kn/+UVh4lWQfGxV8NyQ7osGwJItfL
    6p18+11JwpsLr+6s/a9GoDQgxNgXtlq9N/3t4NL1p41AXhI/mzuO/4KalK/i
    YQ3dKjCCAn4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEAAbmXtTS6EO5Xpg
    PkIVyOGAggJQuCbF8sOT0z/fxVodj/nOldUp7THcpegW03zef2ANpe8vb98P
    bABhgtByl2OSoIOhB9NLY0cAo8xYwTqwo+OK0QpA1MMnash3XqBCjYVybn2z
    xFxS6FzTVZqCADZUQn/E+LcDs1pyn41ZXFViGnj0OY6SrjMorQeWCzQSGoPK
    OXczva8N4NmQJSZRUyOHRKPAvON5R/alIy8P2IWpzbJh7jgxVqWdxw/MFh2j
    Sd0K+RHYICaVqAVMp92SL2ulQokc7W+nt4m4OnXVzXidGuZlvsMxzD4qqJjj
    sFK7xy6zcF97PRh+PJSsOlon/j0D9g/RTDHUYI+V6wcKFMu+sF3lY2jkaiRI
    v+ztaRKTr4vfOzJAgpp1Uw4e5NfFkGIO50Pfin88aJxzt0ufJNzvaV/kRobA
    HxjzSAotkrdVJ/8KQ7iDO3ilvoeCtlwkWlE0hPJGNqZibgKZWL0FBU3Do/Fc
    mReTgckY4mEQrX5DkhxgTa9JquRD64UJWL2EFZgPDTjuly0SwadHMZVBKPKB
    2CTvO4aBOmEMBwnY7uIwuW1d/BebEFTGtds9boMPWD86pP/cJy6yX3qFpVKE
    rDQDKB0m1aHuITTeu1GAV/rV3BZ0K0OsHIz169mcKVGRi7Pddur0oUa0JG+x
    MVUYb5YuUwuBKya51rtSNrSAmWGnb/mfyaToZES+NquGFzqF7k1EyixWq0w4
    3NxMZZvFhPFs7HrsdfO0r1LsO8T2Bd9ReJH/1VzOjY+x2qItVfObDDHuomZ1
    7m8MRtVAinX50zJW8UfTJg==]
oracle_build8::rac::ssh::grid_prv_key: >
    ENC[PKCS7,MIILrQYJKoZIhvcNAQcDoIILnjCCC5oCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAuylNYUIdyys4vHzZHPgRbBsMJ9hT3OUqcPy1
    dHM6nvzumSupqeWFS9w4euEwIwLjEqOj47waSizvMMcK1Q9sD6xMujpLtMm4
    XM9g2kCX4Szduzr4VK7eDunbLXfow9CQIJL7juJl1x+gkxVeGwGRK2KC68F+
    HlQ+Tl26bbyT93O7pY9pGlq+VgNdX1CNp+Qq7gxyK5W8Y8KSx/uchhd8Bdre
    T6M+jzKPWKpEYExBvGtAMeviqrtVE54f2ZqnqBnGunNv8qhIPIQj+RVxny/z
    WyjN+pcaX/aVwJnPkPkUIdqm3hJHaLzJMBCAw2Gbu1yTd5uzwJC9nNuAp5Vx
    wQSP9TCCCm4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEENdMthAg+vrEJnY+
    6KuCxzWAggpASRBh0Xh960rNz+Mz89WkWl8suo3/r5aVM01eOK90cS2wutC3
    YPZGQGZtzbKvJeSbIUtQ+zpxajEkQMEDlmhnKF2icDSo2m3hkB9tuifLPVMh
    SvecHD03UrNtFW73KirQSaUBCH73HWfyFlPZyixtO7Vb7/Mq+9HIMwuvvNzq
    c8Y46vvVKl4JPEO5FTz6a9HparNIxqTZO85hV2qh9zzYqb0zcf+N5JeTp32n
    dwoEfaWy+Fdx93ZXsER9kff+Vj1fuIrUde9JW2khaWE2ieVybbu+mP6pjENU
    g4QwmekCTBXrqpOY0iJMjyH5PfJK2JQURyzv5mz7X7QnyyWCozPFbgFExRMJ
    Ise8Hd/U4lzILKhdsBR27BRqaG32KwGbd/NvXhnB+62X9cGropyOJt4Ey8D5
    FQU39CrAp9W0GTR1YYgmS42kuNH+eomU3BfmgTalSbd9FdRHf15GrzvSlMAG
    hDLQpsrykJV8tRWXqV3TZF4hVp8YVI4TiyP2izju4kYxgIAxEvfFO8sP/gg9
    GLRJUOuoG/4Z6YxWSvBQV88z+2DewjWmcXCg9TUYhjwL0841tP8yWWLQM0Rx
    w2X79KNKLKJ5ajZgGmlfJw2s9qU7B4/iTojxGhBX27GhFu4mQjHE8FUyM2uv
    UeHQPJWtE+xKRD+jaDpqoJ1j4k9AGdsBnIDvcgdnLVm41Wj7nSX24GFVV7gz
    AtSiPbUjr5gKE91juN2PJ2xHUNtpTe2BgusZJT7O/zdOfpkFp+q2iCBmCNt+
    /FRUdj6VRcREaFwJzsJA+wRI7A1dWCGJ4yBH2MxQW3pKDBE4EaSsjMMBA9WQ
    ToSD3dJCcWwm1F2lcTzoItY04JLagT0enmCBKDDkvtVlK8CBqQ8brtr4h7sb
    EbN2DooJ55t/IlX5FRAYkmOFARqbxF0Pn2LTF/gdkf90AapfwHt8hsbIpPG1
    FJfZEwBIKHlvfaEa0XXbcOcijpK70ukii32mOdzcUGjdQsqtDsmUteWUwvEQ
    fElDWRxlI+5Ds5cqTluwyJq3r5j06e207OwUm3CpbGGYRiHN/5J5USNKI06x
    qJ7ZAbUdmi6Mlv44H2s5ZV/HeutEO8nurYse+ZGUQM6/AZOMZ44C51VYuNPp
    tZipmTkX2LnI2RIBDvb6KmayoHcuIJFvkK6V7SrYwqLmqiP0LM4uzJV/kDiv
    iUoMfSMzr0RPp9Yvqk796cXnpLsAqOS/GkrJDau+ZOzElraHoX0sx8DO1Ec3
    trnicMta8TAKtpQ4zWEnIv26ypgqq3GxOquX0A2klAsjzB6ahfvtGW/xGpXs
    DdwajCbsTyfmTvgLF7aDyPKQ79c6FR70sUIgXTD1eFeOIstnZ7V8ArF6FD71
    teSoOYOMEMFlHoompfHLROhtUhpvko3rln7Eq760WVZxcprRD3Kjlz18u/JZ
    za/FjwB5dfEO1GRpkQ3clWn71fldX8yAHhYIvQcoRYqVhnOpx5TAYW0OouL0
    JXSXptjLeEwRNpUmkpj9ZMxvglrjepKp1lXSgwpKXbKOIul1+rAr6Gais+9d
    WIosrhaj8pTKYQgvdwvceClD42x/KNUhUCrcKp4ke1GBdifloe9tG+s3K00j
    SRfNYugQYqiwP5tKzdqJbxRdw+9R9lePjfu7hNXI9wqQRsyuOQJ9fxFOPq75
    BpPFXez+J0h4sOG1lbssaJZjKLxl7qjF1RjKeBIR7jiCmrQydhV02pQi4rOd
    QozXQG8wEPDDWelUJwXw68bVbZLCGELp2s1oOx1TWuK5pDM5C0GNXbRkoW0U
    aPDHraUwAqun90qrNDTfN01N2qXpQDNz8dsp/1NjVDXAzr/Ka3X3Ys54NFib
    w5kKJzgzGSL5QlbOXq/vAqmHN/EQj0zMQQvuY2zNpVPGNmwiAJEaRME1CjTN
    pV3mZ5s74PoxKewh13v1NOms9GydeCDUNAvW+xjjWBvasWbJM9AQBcPjSOeM
    AyoYw5JI+pG+gCX713cOjUxNyTQkdEmzinph6QOQkiXYNAaEPX+ema+lJpJO
    Wr/1Wtk5CAZPchfWKCQAA9qysXiOFdEbT58Z4ejDzIVz/iMA4y4wkBeojExi
    aq3VWXde0mpGHFqYEmaAvNKS51swnNlfcpV59IY09JJqzl2ftzfd6Ep37aOF
    PfLo7y8Nahq1FLDtk9/D4fCWVj7pzOHb6BtUKnPZgJmeALfzV5zUJU+ilR0f
    jAD8C/XMktox/k+3WXxq9xpD0yWYQi5+2i2W1YoK9c7zFUZuC97Tt2l2yGNm
    la9F8oh3aLYfDT0sC83X6l5yo6Bj+I3ODXvxZRdSszg6ZMQKjtW6Vh8QH/vC
    +JOjVhn3inMslHQnypHX2A5aAxDPYVtCDUHaJqtJ5IW6oRH34UazPU8vv5t1
    05ZnIMpUDLpVidbTz1E0ltPd54UPOYIwLFZ4SRN6mexG8uhwdfGJdPk3Sxjd
    tHa9mvJ7LxruJo5cLQKWgjPAdiAOC66DPyiiiQk7cxz8zXj3IlRxuIiBInYG
    D5D2s57nCqtZ7Qc4ouYwJ6+eKw3ChmvhTc/54v5xgCssdpvjR1u4sNuQ/UgZ
    VAd1KvUfEU8xVGKwyE/05ziH8LsDRlhbaVCFbpyLfuJlXkbQssQpj09oPsgc
    dMcl3ovw9V4vfkpr/I9n8eRqzmjDTtDQqxHOPwnfNTiaciiDxh3Af58rgiyx
    nZnH0FgE4TwaAJ0Wp+UI5aqzWOa+5rPKpnVoZ/84jmZXkziHviRP5hyMPsLD
    4WqK5g8v6FvKxsvzxl+p1BXjgM6yldLU8nnzd0qmiu1UsyHMCb2Son25Bau7
    cCH3Rzat9mKeWIu89o6Z1Id6gm2OScPr3pOAGNhbfMTvN8MV2Yy2xTVcWN+c
    1QAj2luU2QseuqtyQ0ZUVxJON4bTPnFl0yHCXiV6goFLREMZWe54vuWQVLaY
    PvNbLLT3tepsR5/jTaf2DhnSNxeHWkGi1wFCfP5h5oqMb9uuEa09mbl0XOgv
    8tR00Omgw9oIGFnTtqnSMF8nZZ6eDA2newSc0F4Q0h4YZfW6wdP4Iy4FXXyy
    raqKdpqo7jwt4eNy/qtNDcGi5Ir8pM3Odm6baJqcN1UnM0FSugCC3Sifu0KV
    8dZ8DECUvOwjw5H17paKjKVIAr9cpuB8qQVHRL9/f1trF4Ft9rnkhvqpN9Oz
    ekgm3IRaDWTdsqmW3Y2wSniBxdPIS7y0fAsiAPNC3B6pr2mrShELL+mPVeem
    amSuV0vA1b3AdupClwQl7M9gPjDzUU0i3QmmYjQaFHirE992iLz6d40APrw9
    cNVbuyQFxok2qjQ/Ooz2TZKq+qiqxhzxof0Var+3FDUWzx+ihHHeft8l0BMA
    i0wEpwpBcgNRdRNO/DB5Ln7iTx/4x62i4J3spOOrQrnv2cEkJ1fn5pdrOEjn
    eUIORvhw6w6x4+n7CLRsc1kR/h2TxCSmNBUUh/XjF5fO8H9wsfbQyCDFkH9m
    ekn8ceoov8zGwfBZ7nIZZ6i288Mz3WU=]
oracle_build8::rac::ssh::grid_auth_keys: >
    ENC[PKCS7,MIIDvQYJKoZIhvcNAQcDoIIDrjCCA6oCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEANBeX9+tvMGJf4h0sJoU+qcN84SqzPBvntxFM
    BCUxmBKpAvPx+VQ6vjB9ObJVg8zsUgNri/UX0Zu163lcPZ67rSYt+tSFLOhR
    w4o4Ct/3ejVtLZ60BZIrf1CQ1GjPWJvfDONGFFJqj7xMAMalRe2InIvvgG2v
    tImJlu3CipIACmtdjqpCSUZRwl9tJe41JhUCPTYcIKPZgzfwSlckYM29ncCi
    WOZVWqWZqJLGKeCnYT9ca5upJzXSfSnjbE2yA5uwTPh8Akrhf83txa4YD7n6
    d/HgMw6CNyFhNG7fs4V74hhuvGHWkkwuB4WQ0sIwiAYO46gieEifev3ZrQeh
    1ojoAzCCAn4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEO4za8aRCxquOvCI
    c3aZHYeAggJQ0FH87ZH2sDFbosDZqqkAPOD9aE918dBHn7CGK123fo/AUr4h
    Oy4k+TGcKdOSA4Z7bRAU/cUS4OROUoPsRr8nWdG56TlfN7GNdT3aATo64S36
    VhWiTLJsAmcq//3x53lGqWZ8mKLz72wZpmqV5JXMEkkPCXoDTf/mQ0BcTLn3
    HzEpjFqzvabTfNOCNJAoVqguPItskeihvheJ5WC6Astk2i5NSwdr5QKQ7oFh
    K2gwZYoXzyAbs/KyMeWC51WL7vTUV6FFcqfBQSlSXZHo5QR/F45HE7KUbYlW
    To8nGdo8ToIQHwQnx7Z5XVUSGK7ryVKzS3FDq1JqymUJ7a0tEq6JQQTUNoNv
    lN6zR3epHmmhWLRXgePTuxLKwedIOE1PRW1fQrH+1ZT8ZflD4RULHYCJ9L5W
    IwxSq5LmafMBhI+GhTddEIxNybV6M0o3MGQPGF9vdQtOmL2coOETDWEtwLIB
    cMflMDzzvUDf1J6iR7QbLaFXZJrk4CgqChAMJKHCAawyhc9/VCcSffkgOl9O
    VXp83Kg5MzoiUirEZxb2y5vOVX7yaDRskO3nO55a9rdsqWkXhA5ZleG0mO5d
    b6cn3Zk28wNh4W+M0i7dD4pbVDmFicO+dBAOx3QwadwJLMviv4+CZ569+jzH
    IK/3wJVsHBjsr6Z68pYvpGWE8KKVCx8WCTlc8QNNMJGKU+AAJthnQtK9ZpQd
    iZwpX0kZSy141ft0k2/dF2G2O3LkbyTzdg+PvyZYuzS2I3S9FXuB4b67pKpF
    2VQUcWZqHMzlLS20dKZs5Q==]
oracle_build8::rac::ssh::oracle_pub_key: >
    ENC[PKCS7,MIIDvQYJKoZIhvcNAQcDoIIDrjCCA6oCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAUhngqWIfRZ1DGC+iBl4xbcHkwnlDGAuh3luR
    bloU5HtYTjzMXjw7VHf0U4JvBHK2YOcMzkyV8H+tGJo5DIu7+uuv5OofsvNV
    AqyMVoXmzJ52Z4zXmIlkUw4P6+zNk/aROyFVeiYWqIMdxU35VdUyyL9qULz3
    duGecgVtUZjlldyz7446DPD2KQ8zkpGR7Wz48QnJxlLi3R/yTcYuoKto6HXf
    KBitqZWDx0B+k6isA4K1Y2Z/48x1QZV+sMpzzaw1kHxxKNYSNUnWVrTdwpnN
    mD/SRdaaNpFW+jQOMYVTOHmXqvu13wJpRGiBm20LcbQ7KMS/lcV0IRbMCBS2
    aS1kKTCCAn4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEHGgarsvICN5CZ9o
    eh+V5gWAggJQx4B7/xIOVOdnYyCIyn+uC6r4tBHBMolg2VwJr8wlJ/5qaagd
    hN0DzudgKTdQPRK5T5pdoAkJVZU0CZhJpohkfVSmDNXM8glNxmu8kCVRDr6O
    JkK2+4JJfMiEOpA0UJXXOZLkQbVT4KMKNUZFtP5ifDbi7riWU3Gxv1q8FP5C
    cH3yFaFkTcj9Z6l6gBmc8JggzQlVzz/371Ylv9Vun6q5dirVROiYuyaLaDjd
    XPION9xSzl2poNOipSAelr+LXETHpRmOR7yxARu6bnCuoQBv5Be62QWUfOWt
    2nLVbktxEnhJX7VxypIS//IaFoHCzAn+hBXxNcb+w7p9kIK81RyXo2GNe09c
    9uJ2f8sGBb2ERrkLF871rUi0y1Uql6A2X4sGX211X4daIKu1tFJr9NDHmS07
    nD1ubNF7UVyONKRx/7ceNCb9H3W5fPQiWQbmtDUb8mKF/3NeiFM8rFhQV9ek
    cQEBcqHvVWDK2jhfvas4Sp8bprwvq/ZemRnePvWnd8pmXQTSevv5UBPo5iYE
    J6mjf1f0RNRFwuNoXPXJi6qXvq7O2ULZb4onsMnbJGC/1iN1KWJ0IjfjyrBg
    w4EYCq1Jix4y989JuNfUJftHubXTdizqF4DiOGLP4GqAKS/Ng8beusYywV5/
    X1NlLX/fRg9MkEyaYD0SW8Aeqcow2mm/+IJSCUtvx5zXyzKoMco/KuZkET9B
    LZXMEkdRsnQbpd2BNbxsxiupisT59PvbGy/QfV4Fjts5XtDxde4ob6qnTKe+
    RCCbkP2hNqmLzffB5KPqaQ==]
oracle_build8::rac::ssh::oracle_prv_key: >
    ENC[PKCS7,MIILrQYJKoZIhvcNAQcDoIILnjCCC5oCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAejyrWHgjm7+gq3JiIV6C/hqwoHmBhm3wbIFD
    YWi2ZGCZxAL8IIrJ4KjBnJtKfGcNoNigLhWqubUdVRJphBKMGk+YE3NnKBms
    3T7Zh8oBF8dmcxXmDxMVJWCQ4GjSu1rwaboHn9/CdDAJG0k6jI1Z7wrmsulX
    3Rwo27uMXtsybZw6jA3hOL8Eo9XWtef7CPubByYnAXVgIq+EDc8cTWnvPzBp
    GK2ZB644UBOK5PorPZJyC8/2bnsfaWEFk7gZAr470e6QRiV+K8LZzRa4kAN1
    OgoH38/fhXUtP919z4KmQpLwGRDPM6CybmpLNmGj8RyNxpzFFhoBLY0+ks/P
    1Le0vTCCCm4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEOpUoiCcDAx6gkL3
    +RcUhOaAggpAkXlOc3QhzLEmNCxlVBUwbfFjgHDz4RnC+Lvi/btBpXw+Mxok
    Pnrf4x6n/8m002OGNEqHhhB8l6urogJXkTQxXpDyMYFNTLnJUSlk9rpDn2O6
    P77iRMEdQ8ltajxsg+d/KgztxW1VGFXVAUFPuBHMlSDgdL3HiGWxyJmDjrfP
    pVX41VRaKhQVWR89UILsxRO5uHTdCjkpgZ0lYV6ls3V3ZUwNcdjNEH2MuGRT
    YjSHQL+ZKjB5UDKQhVFR8f0eWKMT1LJ7WBrJon+Gg5WA4PTn+AQy7k8RLZt7
    sX/ySvfHrV7xa4u43vD/rrb+GPEUZacfEa5q6LG2O0Au/9odspxe1pa09d6T
    KLorDB8F2HgZhl5ehjFS2x9qxbu26n5yqFn527NRIZzNJdX/nciRDZKza8hq
    f788bpQeMHGlgTVDI7zMSvoXwHanFmuMX4550uD2l1PyqBfeOk+UN5f47j/Q
    pNbdNAL774a9acPj3V2vAGfkAmJrrCiBbBsUIihz0COm02TyVAJM95SWRg6o
    YuDD6/9LaVtDrzDwYXUxcAMVfhCYLdA92dU/VHkL1oacYGN9Di9YOhnNsm2Q
    G9BeQYUsYoXfQPnlfdryDtW4/Vo5rtrud1u77cGU5Tga+42yGzvuUz0SLBwU
    Eg0XImDJKMhnzYlMQ6PDPlwpyFeLRDkl3VNS/HqhkYzPUe7/GhhK3igMOVz7
    H4hd4yfvblzDjU3Oc2TgO0sp0XM0c5YiH71YYx7XQ8F52qaNKpkh5B+aeDYM
    I+o7+JAGLO6cFxQR1oSgXlrWPqP00Wg3jUZguoOmDlEEz0XMETVGfULT8H2Y
    /AohtB5L2P+fj6zKCtj2oFUas66X1tzOGX6/mqSoisJ0CFGShAVy/7O/w7ht
    zv7/k/kqsGe97PCq+Za2XtDnQlKnREfme1an73uwJa7/z+ii6lFSIwoWq+TN
    zrbZ/CSGea4/r6aYjh8HsYWWo437i1T6NdhJxsbZrVexzgfLPjgPQomu9pTQ
    5Mb59pf1t1ENuEwDRoH/z+jTXC85i5CAhPHWxMkNIL1A+Sx4y6RPXFtgjSiy
    IXuH2q+3naWWTZEwO+KaxpwbrM8C/D2NopgfYjQkZUZc/rZJgQB6bQy696Qa
    BF+0BpqAophBJA2RiPrZkpoLFrxdpzwQ6jPZAJDCqG3UEpG/JDsimAttJptN
    0L296w95Y0ETPsGIfWskQEAQZfXAZK4VnjhxXCuxlrtHzNE5HnpUgnVcT13o
    JnvMPuz9BYpTnshNMrHpTj8kgZhmiX/BTGWUV2L7xstk+TSff5QyEEdu5TBE
    8KMc/fDHu7a2ACm8Ys0M5qW4UEPCmR3zn+nh+woq1kD5P2NVt4sGdE1YAB98
    ZfkF5MGFtyK0tZXjcWD6lpvaF6jF7+9iIHGSa7L7CCL/pX5Zdcxrl++EsjE5
    SQjezeHR3pgTDwor/9JWYP4DY8AZLF5JRfUym2bLH8nxnrckq4zqujUkyN5H
    zolTtQ3Z9KHSWRqU1k/cj2vKgAHDFkEnjpcRO3MUW/wImDNaYv0dXhcKPCpQ
    ck7hzmcAKAVqWknHXRXJW/GHH9gMjr3SaUKezcSgzYK/Td/b1x08e4WEEtGP
    PM/yvT1+MJZta4ktDKmzKxq5hcxGDZ5zOrQaTSuh1niVG5FevsDKYdpuNjp3
    HJenqhXMD2+n5rJ400OdLYlTqrbB2YEON9ls7PJlNLIEuy87mOP9qJGRA1vt
    OIal4JmFHag9Xv0wZRA8yGLVrEdXWrwJeJhgFPdnmK4LSnmvwk2p15F0E0Be
    HbjWQklnx1gEqKopJWRPaQDk55xLb0TDj7blyeH9UZL/i9HFW0wpswuIe2wu
    Z+nZJfdjGn8THn+buzeN05EYmAFjgRptij0gpuw0GVWfwmogzmdF/Y9ueO1c
    572bpVzXfvmhd/O5vpzZl+3K9JL4dkPXp1jZJx9VFyyDpI9neaoZ5gbcQUFE
    LrifW0qp5YR/1EjpkdATXsm0WWVNMRn3GZdkgWRzT8s56w5XkYRfd/sUzD4m
    E1Q7vMZDVES/YMlkIe5F1gM7Tr0L6ckx2EdEBHqeiXv35JMh25nQVaBYX8yg
    3FqG4I9Aic/cOTQ/gRxhJz6RWx84tTQLEFIFJ3c/gb5MnuEDn1WSPE4CZalu
    2pgpQ6KuRfirvaYq1IKZNGRFyGiwSUs8v5I47td0pBGFMuheZcVDmJW3Ecsc
    Kj/e8s5hR2Gxp/XpKI+iX6VFMHqKWA4gkGlTVQpmwRdV4FG+MCK5DPShGNwi
    gMV5AwpQHAw/bHbCTHfxoXeDozDhVooe79TWrplAok2GPSHGVVWgrgBRTk2X
    296m81ymoKVqLrXogediQsS7/irfvrN5QrxZioXra1b4QQ1sWPSNxI6/IlIh
    9K88KNC9GPEqPcCipQYHs5hO6K/J3yBR8uK8E37vu6QCOexXE2cg2sKpHo6d
    AbiXWJFdx2NXPuJa71sGXjZnNSkUF7Lq8mr4BBdbk6uOlwb+I9MHjS+0lkf+
    QRdLew9hUxKStEf0YnpvaG+adEvnLlU+bD1MSWCyznZIUn7UHuc68yrGd74C
    EalBW6IzXm/KCwnxrMueB8xfbbpCNwd4pcdPKFUjuyBkEnkFBia7VtFhXAL1
    G8+Zh4V6ycWneUe7KXoTgrl0rRdHNBFzmFeqBdE/sL09+QHzeveoeN33DbYY
    Kr6I7s99+842lMhvK3SzPuUTfDrocCdl67DJaZlpOJZqSVUeP2vsekPcCssA
    iTQQEw+h/KHBVlyAAcQtmfB0rq7ssMdvZWTyllSJ2RthejXeYB7JtdCbCrWX
    5vsrfM0vKEUx7LxcZYbDp1DOTkA6djwvHnWmdneoCTeuifSy2rRkRXCwXLe+
    4oQRgPzYUSO69vy9uV/lG3gbwjjNhaHapvQfZyQRN/ztc/3vreWa9gp0u9N1
    MCCQR8SwZfhdCny7S4VFFblqjRFx8RF0o7VvhL2JcchMmb+kzYA1H41shBUK
    CgDPPbGeMAKOjhJiXSaCkeYcMXKjQqsin+/UDe7Ru1XcEoXTmbZF7t8R/mNo
    1pX3VaQhWLP9MEbN8kr2oJuyOymz8v4Lrq7J9g85ZQD3LkwedE25+Xtxa1XJ
    zOq0un5ZFKI9gYrWwWPFGmto/bh9sAQhxqOmts2iIh+8UAD8b0ZH1ZXzn4WN
    Nv9cuD4CqhdbYxpl4QVNh1NPPvuHsMMz7+nfaHFnmBL+b1MqCP2qonxX+tuj
    bSwrni6nmMgf2BeGQ18eJsHP0PNrZAv2FXFUogpHyZreCj6gkqVhdBzxzJ0n
    SLGkEuhSFM+USknoQFKxk4kWTluyzULg0rxrCgz2dIt78ddzIcFu0htT4TwU
    SIyaA9aH3cH2mKJd3kZVf4xF19y/Dq/EmJYTmFsQ/Zz2xGZkv+mJ6XnFSSmD
    lb8MSccf0hyGFL7egWEffWH7egEM8z9L7CGxDlfA3Nl9BTjidR5nlyodhH87
    LjWUM4KruZ2dDM+b8BEAV6cFvYJxk7o=]
oracle_build8::rac::ssh::oracle_auth_keys: >
    ENC[PKCS7,MIIDvQYJKoZIhvcNAQcDoIIDrjCCA6oCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAYMeBYN+xQOEY2CvibII+FMdiPVaWS2uEhkzP
    gHvq3TxJClWDtibEveeohDZgSbLuT1zhZXr2vsHogYdJqwIpKNEDIM2lp0UG
    iog+JU+wJaBHxiHoyNrlSmXgdzOIf2MygJrHVVf/nQzgAp2naGLnBZXrIZlI
    TiN7nCQju2SGwZSogzEJ85//b34wTAsLOubeXVqyaRL4Op9iPcYg+uG0+1Re
    ofQoTCLpgUiLVtokfA9uVS4Ny7D7oowdVR6aTd642tDfo8uU4WdqH+5Mlxo8
    RpW04IBsD+89WzjbxNdqj6m/R11dQp6VhmU/8hxCS6v72sRM+LqY9HiLe4kO
    tcyxEjCCAn4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEOcRsmvJ5ulBviql
    DNLmpWWAggJQ7hRqjECSCx6vNGmLHiwcYI0sW1goOlglf4xOpIslpWd5H+Sr
    b7/yooXfBeaA2nwmX215LaTvTvN1Aqf8dkCpY9WlvXwDHcgmqlwoAux/snHj
    gWlcK1gr0Fo8tbBCAB4JUPtl0srPs+0pwHYd0D/byo8kfUDHv42swwk9XCLN
    tPVEXbWOGTOhwlLuE8sH1fa9vqQnuvvR8xN/lO8CUEbUwHf16shB7Sfzkh2S
    NFgncA7OV3dXYtWiLN6+varGq0bky4cWtWuZR2q0Gf5uFSua9gjQ+ygXQ10L
    ibryLcrMCDplzqiJFnYiZhr30RtL1Etmyt3JtxYG2kG3wOi0gDmPKHGyondS
    Q/YXIgxZDWxYWU4z1g8luNmdy6JToYathBwd7hN2MB06hbYDe+FPPFJGfDMO
    Ol1HonkCOlSCvYp3TdEcbZcXABgo0e+8TBEhAkZZUrzbbnMOU6Zxre7R5rZJ
    VGud+/CBlBvMWGz92xR0ECEYr4+UmjdkSpUW9+A20w+PAL0sxxZQv9pyt4e4
    vpDX/GheNOHucIpNRjdaZETiSUVV8GspYolWdFIWzkHYccxRPAqjjSnREz/F
    IVwwbsxsuTxxW/f1ocCtfm54PLB50GhbxwhvvT+UPUZAac6Ztjo/W7MXMgf0
    mUTL+dp3c3s62Qy8fu9fx93NfI+COYCH7Wmgw0XDDnKVUK1hPb1ybNd+eEl2
    /CVcRc2WioxEpwUdn3qNoLfCsY41J39BJqXBrRZK7a7dGH8+ZQeMZrO8I8if
    47dLBRhK/HpvWDsdfrOjHQ==]
