# Oracle Enterprise Manager
# WEB Server (prod) Configuration MetaData
# by-platform -> ORACLE_OEM -> WEB -> prod.yaml



oracle_oem::nfs_mounts:
  - '/global/apps_backup -rw,intr,soft,tcp,bg,rsize=32768,timeo=600,wsize=32768,vers=3 nafgps01rw-nfs01:/oem_backup_prd'

# Fixed NFS mount for OEM stage 
sw_util::wrapper::hiera_mount::params:
  - /apps_stage:
      ensure: mounted
      options: rw,intr,hard,tcp,bg,rsize=32768,timeo=600,wsize=32768,vers=3
      device: nafgps01rw-nfs01:/oem_stage_prd
      atboot: true
      fstype: nfs
      dump: 0
      pass: 0
  - /BIP_STORAGE:
      ensure: mounted
      options: rw,intr,hard,tcp,bg,rsize=32768,timeo=600,wsize=32768,vers=3
      device: nafgps01rw-nfs01:/OEM_BIP_storage_prd
      atboot: true
      fstype: nfs
      dump: 0
      pass: 0

access_conf::access:
  - '+:root:LOCAL'
  - '+:(sa-local):LOCAL'
  - '+:(sa-remote):ALL'
  - '+:(gg-corp-unix):ALL'
  - '+:oracle: 10.148.5.80 10.148.5.81 10.140.32.21 10.140.32.22'
  - '+:(gg-adm-gcdunix):ALL'
  - '+:(gg-adm-oracle-oem):ALL'
  - '+:(gg-adm-scan):ALL'
  - '+:tricore: 64.94.254.0/29'
  - '+:(DL_ADMIN_%{::hostname_upcase}):ALL'
  - '-:ALL:ALL'


oracle_oem::qa::rac::ssh_private: >
    ENC[PKCS7,MIIH/QYJKoZIhvcNAQcDoIIH7jCCB+oCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAK8ZDq46Z+siZxo63t329C7i5j6FnMR2TU2bi
    Ww4Uj5PRWJhEIV5NuH5bZ7huPndXlnesKvXXGMIYTGo9wAAh/X+MkIwXvrN3
    RZC81B+uxS1zrIpxzchQpojakEx+TzTBmqP9XFK3lQJAMJ0IN1jzFYXHskTS
    qkyXBP1eT5gRf4cr2NdZ19IIMszguo7burBGMW7DL/vvVqQw8Mugu9THHO4G
    L3fMluOv1uPOc0eXi9OAUTmx49W55nKGXt2DP2igFhUlvrGNmF+pVawDiOV/
    gVXf3xcUqXnK1ZLNdTYyHt3g5K96td6vPnAsOB/KBRUABkGfnvJUid/36eu0
    GU5pKTCCBr4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEG8++JliNj8Uz6w0
    ogqQAHiAggaQRZnX8hKYP7Uo0TzBF3eL5R/TZXYa4fd6k207E616jTMynnDF
    U1MaBrXYhDQsztujoSnns4u+uRS4HkuvopkQujZXuyOghndGaNAwD3/Egx08
    45mooRlZfcP01BKuj1h+TIkRXKojA26RQ3lF25nZ6PVZapr+yquhjFa3WqqU
    6gNMOKhJVtVQHK4VRiuK1wXK5Klb/f2Q2EkQibuKXJ8fpL2SPZAyZzWV+VGh
    5tfGZFjscdE72DvOV9EEMKuX2O/nWnw738vtJ83W4NIO7AT4eJVmrlkKWUhs
    a4Mxlc/3JBUoJ5ReFGPNFB4bCaL71y8wf1zVOIKDCjmbpu68Rkkupyo8dzRl
    KnjlHKprQYG4nkc0sbiiJ5IQ5Ifqu5RIEPn+adKJviwSG2P33WqVqlln5E7F
    19JvaSyjfBMTFp3NerkNjvn7ZH/ne/w4op8GUdxVA1nQHNobD5SUAzd75ECw
    Z3+HV6TEmgKy0XkIzicwip4W2X94KSlzX7Jqa3FAV+Cb0E7bmMeZkmmcZc1u
    Es6rqC32TeTN1DFyLgeFdh6ui0moD/b8kzNlPrXzf4TOHDOusr4LgHmVP3eV
    2UGEoBF2NTFJLPxkEZxmenzKAGtE5krpb1FgJWRJJfcnWnjvch9P69hD5MF8
    XQFdDAZQn7CaozMz6dwE3uYMMX3+K02FFyuWQ50guy4c5DNbw124ve0J4M16
    gdnwtGOEIfcg2RT7shDgVsNxxnVXYKIxJqMw4sA3C6C2LHu9O1ysuHxYAhtn
    uWZrKlU1p2AfVk33zifz2VvQOxZRmC9hYT+z5hn4f/zkOi0DpgvZB5dG01Qu
    kCAh1joSo0mMnG8rC4mrXE9EopQO4tQPVGPuZ1zK4kSWY+ULssnM/zgb3yun
    Nl+1Exlx+FUpIgXcGFC+D3k2+hb2mmRcokvaBbL2MhjlyDZJ4A8Yl1GlLOqj
    HFTl0HOuRzxyTzLG9pmbisHQio/kut835DpKW4m+49fAEK+sa12EzL2BDiNT
    DAZbc0xGehtPK/WKdEVnVA5F38HKzAB/859PuHFRlRnztmk4SgHAgl+XNEJE
    P+YbPTsN9nWWpDTZ4KP2jT16LUmYtaZyYcTjiA7xX7YuGfEoZVzqWt7M6xWC
    RCtIoJC7byRwQot8rHwGIx4duyYXJKKebe6AZ37rfUjx98mUO0aKzlM1wt+q
    Up79FCjEoLEoPm8nbAjXYB6FuNKCHQpjTe4eIQDOkLv1YzAnpBoFDEhU8MOg
    9R+wgCrYcsu7CdqaLAXfnqg/kyITa26ApDgql5OxbSy4NEiOtb4mpGIjxVFN
    3K+HgcDTexZ79QKaoAfXPtjGm54CBkLELaELya8GOepD9DwPlKQwFsI8GcvB
    nrXAQr2owh2F2wgg4SeukDjqBVaSQ32o9ydTJEvNUl56zvN4LG8TCGMj0JXc
    9fSRID0emt2nlzTgX5y6up0Pd5pCU16UjPTRctBJxBoiKD/6DN/N4BQjYQXv
    81GHdFMuyR5nm9+UVWlRKWc0cr1BVbr1GhCUkOqwFGsOne62W9z1NDEKN7jK
    awIBZjHN4MaFheNLVycdp2D96GiM7gvM24s7Hpqghz0dtepbReiO3MSEhrbQ
    zl7HE/VPehY78MNWe68olRcdX8IzXvnnCda0QE5kGyxk121TebnlHgTznyaI
    mbbyW/bkftZUWkdcKLFkQtjrOc4HXVLS4buEGYqM3NYtHRmsfdBvnMDbDVsN
    ztFbahE9ynIWnnkhKTKBVkP1KuElxL04hlUjNXPYT02rskAIjaZ7sqnsIlFo
    iA6UB55nf3zkRLVayLR3kPvVZ6wXs0fWIpGgaELg0MgUDE1+Jkum3YsYEzzb
    5Q21BK3STFqJ9eoY/x+LFIENazKbvsUEAmIiHORnibj8bzfGv0qJ+qIK+VSq
    ND2NuB38KDY7clT6GYQqeYdPpoTqricS35VwdWbWK39wN1QOIlknj7KctS5+
    hEgiQOKMta+2Tues7hEGhSqgHUkOik24oSvmrDyovqECih23ORUQbyM6pcVB
    1aAzcsPxM2w3XACwxwNE8nFDvUtEjQb1q3kRNr64KGU3YRWa0+OTyI8G0Bfq
    2Dj7a96tGmHTmqcR33ImUZZ0XyufceZuQVxGHTnGiZO7QWuz7EFWeZsLUl5Z
    akXCiUsJLVZnafDjwFBcvwzhVSi7W+9gTI5Eg274uxw3GfzDNbPnCpy4LPsx
    9MV0VVkZBPdd2uJdDUJVQu28ae685gJ3]

oracle_oem::prod::rac::ssh_private: >
    ENC[PKCS7,MIIH/QYJKoZIhvcNAQcDoIIH7jCCB+oCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAZHiSgrR0ig+kEbm3hvsomv13rhy6YLpYJ/lU
    Mkh1B+Bre8oAHrnkknH/8PPL0vF399dbE6tfc21acmhUsvFo5TH3/bMx5mhR
    Pi1dshX0u523oCB501JoZgLOfoKBQn2cMLnUjjMogeo+DrLhlVtSUBUrZs0r
    k1jkqTnGlgsXUr06vM3mFRMePBDgMKe9PeItJaHN+QPhnQY0m3RZlOuDaFNp
    euhpCJx4CEdsUANaynK4Yi50AjF8LbD/wfjY9p3NutFwY6gOOojVLM+CG3Ao
    dn5GyooiFfV4wPZRFkQBmLbfCiGOpFbgE3QX2eR4knz+JeJR/NwGG5BaEuxz
    VP1ofDCCBr4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEGsNj6QR1DQAN96k
    IH2ysYyAggaQvRhOuthlvioCYRM/0BMx8pmP6JrLQYtMomu7NZs2xSeq/xC4
    5Mph1FNWMmzIy4+XYcqikxHFIxKYYDIzRHyUDwFQRo+Hw9CBKvCvQS8XI83B
    S0W0V673xJbNmANteDS6+vQZKTOg0frnr72rIFpmYSDFmLBxpQqDw4bT6eIg
    EziyY2YWKgbAkxbhNxjiw/iPZjIIG5BMni2cSqeQVJJ5i4pIZk3KCdJU1PlO
    1mLt5S4fgpX5js0leRvdgdUfBVlS7hajJKiigd+fzKCFL7gVQKz5jvzOgVXj
    LDbSS0zGKN7xB96JlTTAk8Z+p4teiuviw8IQxvuBFp9ZrCjW0LHvE4mz6uC9
    eQ+72RCe1H3HizacvKzc5urVFcAkdMhpZsxGCvcGMCWy61acRh/rJiN6xOV4
    cHnxVkdb7yU+Ui8VHCEIe4GaXcLKsioytZ2Wf3W91NC2uQcI3iIyIzcTpr44
    238g/r4NkAp4SH1SyDztZeOupkvU0MjkMxm2WQvMBPwYCnxMnat6gE6Fvk7w
    3qNoknIOO+JRlI0wTQlz2Z1nuMPOpBkmxT65dtI4G9zAK4bC3tovX5p8XImx
    37OlopTaeuR3pTsa5Cdmqd7yKNPvC5+InlMfWevJl45NpmW2niVStwW4TZj6
    4I2+F4r1rhff+nNO7uwaqNqnMmmHpg4W4SqheFOoPP5pAs0l5wEOh1zddwQK
    QHw0FiJ8UB2BmLilXxSDUIabDykSxB6XM7KTWO4knMVdKvzvh0G6yJwuqf3s
    dODy9yFMO5kLQ2C7iGPoy8yez6TUmtrMZvikD5erpZ37zuzpa498dZURqVAC
    98+z30bm+1hE/K7P5g4MeRI+F1zKbm0N5tyW/T2Wcw57CxWvvxHb+493+kl/
    JNhlEElw/vWwiibSG1bRvjglQKeulzR2XJmLnO8/0imyK8CNpM+T3lzrlP1s
    tP2eQO4ULOaAnVYiIXS8QePcQA7F2Jp5/c7HL0rCyZm81qrqmSPBFYK9dLV1
    /+aBURdiirbyPzyLc0N4myqdZ3ntRJKhGxMLRdmdskETdu05Ymg+rrw8fwjJ
    80DsXBriS8CabzMVqWIWlJjA5+zRQZRiF8RIsAIS/PbCCmuyDQk1PjheX45f
    qN5x5lZwePRHfM0owPdjOtpKJ9CBGjcUEsDVEFd+hPXqebgQCzUKS2ZG9qUR
    EQCHFmNj8ADAMJGclUL2A+iOZspcLbdDCH36HZGE5DpdJouv4wdpd56TQ01x
    me2NfT7+3S5MgV50swPuudQ3cJNI9FH7bKOIqTNAiLAh9dMEzaqJqZTeXMqZ
    lSyG7uAPpwz1NwzSE29IrvliIwnWXmk/pW4Sw3Ej240DZUE94SQumoZ35XEx
    hO8RdP5f2oKZ4Uccj7OIe0ELzu0QQFakxDkCw+Zuw0WfAnZWLVRYRVJy3Jou
    Enq7+7q8ITtdEjTqXWaKr+bCkNJgxKuW97QQOKX4XPntBY/IWjtQxDC5qqWp
    O6J377vySrTRI1KvxufHem2oARKtlRy+21g28IwHI6TDR/o7XJfiPUrovHex
    l9ALjY/ZFUh9qaMnyz9FEBdEohhUxPCOJCKgLuVvZBed47+z53r0cXm18e67
    JgHu58XzXp2zMGWCWEIfGeHU+6WoYZT08ziQr3SbdWV6QbdtQBWjOEcP/o9/
    ZkuHwT3Wz+K3Mo9+UOSDVHNIwSmWaZVVJyh4xLhnvNvGJQ6wXcByqqFgdcBA
    rHA/fzNLLjhXgC5TCstkhVkVubrbYhM31fTBB7az+v8nXBdNfHwDhfP7Cyh7
    ZFYoRlzG0EBPv23jmP2Au2tvdJpAlkiOewC6Vgrx88moaMyt2TyHr0Dwf+kG
    Rv/RgWYIK28MuGD2HEggNmwLxcfofLGPcx9ap2mVNj/TVHPVUrvG2+SMwoBF
    DEsK0eFgdNH6XQZwEmuoocS260LHEOJ+01iRfxpna3LDdPO4D/H4sDYoFn9f
    kTicPhRyygDRPAe39QmKEzMkmPAw3EVvWSnuhlq2mTfwCOgX7HtkaNKaMGh7
    i8J1cb8EZsQUOgQmFI3kK6VBBwAoXoqJZYHb5Fd+Xx9jT7retr1mzSNrUME8
    JlWTKzLpTj+PlOa/QTL7ixvZJZTn2p9qjHqCAb55NENd0OF9fwfw0StHNCmp
    A4XHI9JtjJzj5oL/etzrldOKcG1Kx5Wt/7c0iNP9y8Ohyw/hgtEWt0Um/y7P
    AvN2gEaWpNBAMDpk4PFvguMsl0hVmSle]

oracle_oem::ssh_config: |
  # Puppet Managed file
  # by-platform -> ORACLE_OEM -> WEB -> qa.yaml
  host cpoemqdb*
   IdentityFile ~/.ssh/rac_qa_id_rsa
   User oracle
  host cpoempdb*
   IdentityFile ~/.ssh/rac_prod_id_rsa
   User oracle


sw_util::wrapper::hiera_file::params:
  - /home/oracle/.ssh/rac_qa_id_rsa: { ensure: "file", content: "oracle_oem::qa::rac::ssh_private", owner: "oracle", group: "oinstall", mode: "400" } 
  - /home/oracle/.ssh/rac_prod_id_rsa: { ensure: "file", content: "oracle_oem::prod::rac::ssh_private", owner: "oracle", group: "oinstall", mode: "400" } 
  - /home/oracle/.ssh/config : { ensure: "file", content: "oracle_oem::ssh_config", owner: "oracle", group: "oinstall", mode: "400" } 

