#by-platform -> OVM_MIGRATION -> PPM -> prod.yaml

oracle_rac::udev::oracle_shared_disk_rules: |
  ## Puppet Managed File
  # by-platform -> OVM_MIGRATION -> PPM -> prod.yaml
  KERNEL=="sdc[1-3,5-6]", OWNER="oracle", GROUP="dba", MODE="660", ACTION=="add|change"
  KERNEL=="sd[d-h][1-4]", OWNER="oracle", GROUP="dba", MODE="660", ACTION=="add|change"

# Directories for NFS mount points
# sw_util::wrapper::hiera_file::params:
#   - /util: {owner: "oracle", group: "dba"}
#   - /stage: {owner: "oracle", group: "dba"}
#   - /ora_stage: {owner: "oracle", group: "dba"}
#   - /swpkg/applmgr/ppmp/apps: {owner: "applmgr", group: "dba"}
#   - /swpkg/applmgr/ppmp/inst: {owner: "applmgr", group: "dba"}

# Production PPM Servers (cpprod16 & 17)
access_conf::access:
  - '+:root:LOCAL'
  - "+:%{hiera('sw_puppet_ansible:ansible_user')}:%{hiera('access_conf::ansible_ips')}"
  - '+:(sa-remote):ALL'
  - '+:(sa-local):LOCAL'
  # Adding ssh access for RAC cluster members.
  # enabling oracle to ssh from QA to Prod for PPM Upgrade  remove 10.140.32.54 10.140.32.56 after the upgrade on
  # weekend of 5/12/2017
  - '+:oracle: 10.148.19.88 10.148.19.89 192.168.132.16 192.168.132.17 10.140.32.54 10.140.32.56 10.128.3.12'
  - '+:applmgr: 10.148.19.88 10.148.19.89 192.168.132.16 192.168.132.17 10.140.19.24 10.140.19.25 10.140.19.26 10.140.19.27'
  - '+:sa-oracle-oem:LOCAL'
  # Adding access for control-m admins
  - '+:(gg-cg-wla-admins):ALL' 
  - '+:(gg-adm-ppmdb):ALL'
  - '+:(gg-adm-dba-ops):ALL'
  - '+:(gg-adm-gcdunix):ALL'
  # Note if the control-m server changes access must be updated for ppmuser
  - '+:ppmuser: 10.25.33.95 10.240.24.116'
  - '+:(DL_ADMIN_%{::hostname_upcase}):ALL'
  - "+:(gg-adm-tricore-ops): %{hiera('access_conf::tricore_network')}"
  - '-:ALL:ALL'


###########################################################################################
# Oracle RAC 1617 (aka PPM) NFS Mounts
sw_util::wrapper::hiera_mount::params:
  # nafgps21ak-nfs02:/CP_ora_util_prd  /util
  - /util:
      ensure: mounted
      options: rw,intr,hard,tcp,bg,rsize=32768,timeo=600,wsize=32768,vers=3
      device: nafgps21ak-nfs02:/CP_ora_util_prd
      atboot: true
      fstype: nfs
      dump: 0
      pass: 0
  # nafgps21ak-nfs02:/CP_ora_stage_prd  /stage
  - /stage:
      ensure: mounted
      options: rw,intr,hard,tcp,bg,rsize=32768,timeo=600,wsize=32768,vers=3
      device: nafgps21ak-nfs02:/CP_ora_stage_prd
      atboot: true
      fstype: nfs
      dump: 0
      pass: 0
  # nafgps21ak-nfs02:/ORA_applmgr_ppmp_prd/inst1  /swpkg/applmgr/ppmp/inst
  - /swpkg/applmgr/ppmp/inst:
      ensure: mounted
      options: rw,intr,hard,tcp,bg,rsize=32768,timeo=600,wsize=32768,vers=3
      device: nafgps21ak-nfs02:/ORA_applmgr_ppmp_prd/inst1
      atboot: true
      fstype: nfs
      dump: 0
      pass: 0
  # nafgps21ak-nfs02:/ORA_applmgr_ppmp_prd/apps  /swpkg/applmgr/ppmp/apps
  - /swpkg/applmgr/ppmp/apps:
      ensure: mounted
      options: rw,intr,hard,tcp,bg,rsize=32768,timeo=600,wsize=32768,vers=3
      device: nafgps21ak-nfs02:/ORA_applmgr_ppmp_prd/apps
      atboot: true
      fstype: nfs
      dump: 0
      pass: 0
  # cpdd01ak-nas1:/data/col1/oracle_ak/cpprod16v  /global/dd_backup
  - /global/dd_backup:
      ensure: mounted
      options: rw,intr,hard,tcp,bg,rsize=32768,timeo=600,wsize=32768,vers=3
      device: cpdd01ak-nas1:/data/col1/oracle_ak/cpprod16v 
      atboot: true
      fstype: nfs
      dump: 0
      pass: 0
# Delete below after 9/1/2017
#  # databaseb-nfs01ext:/ora_stage  /ora_stage
#  - /ora_stage:
#      ensure: absent
#      options: rw,intr,hard,tcp,bg,rsize=32768,timeo=600,wsize=32768,vers=3
#      device: databaseb-nfs01ext:/ora_stage
#      atboot: true
#      fstype: nfs
#      dump: 0
#      pass: 0




