classes:
  - profiles_unix::gsc::oracle::asm

oracle_build::kernel::vm_nr_hugepages: 17000

profiles_unix::gsc::oracle::base::nfs_mounts:
  - '/swdata/nfs/cgddorac1_repl -rw,noac,hard,rsize=32768,wsize=32768,nolock cpdd01rw.sherwin.com:/data/col1/gsc_oracle_ak'
  - '/swdata/nfs/oramedia -rw,nointr,soft,tcp,bg,rsize=65536,wsize=65536,vers=3 nafgps01rw-nfs01.sherwin.com:/CP_oramedia/oracle'
  - '/swdata/nfs/oraremote -rw,nointr,soft,tcp,bg,rsize=65536,wsize=65536,vers=3 cgnaw1b.consumer.sherwin.com:/vol/oraremote'
  - '/swdata/nfs/cgimi4 -rw,noac,soft,tcp,bg,rsize=65536,wsize=65536,vers=3 cgimi4.sherwin.com:/fs1'

sw_util::wrapper::hiera_file::params:
  - /swdata/imi: {
      ensure: "link",
      target: "/swdata/nfs/cgimi4/imi"
    }
