# by-platform -> OVM_MIGRATION -> MASTERSAF -> prod.yaml
# Mastersaf production database servers
#  cplamsdbp01a & cplamsdbp01b


access_conf::access:
  - '+:root:LOCAL'
  - "+:%{hiera('sw_snow_disc:snow_user')}:%{hiera('access_conf::snow_ips')}"
  - "+:%{hiera('sw_puppet_ansible:ansible_user')}:%{hiera('access_conf::ansible_ips')}"
  - "+:%{hiera('sw_puppet_ansible_dmw:ansible_user')}:%{hiera('access_conf::ansible_ips_dmw')}"
  - '+:(sa-remote):ALL'
  - '+:(sa-local):LOCAL'
  - '+:oracle: 10.148.19.192 10.148.19.193 192.168.138.11 192.168.138.12'
  - '+:sa-oracle-oem:LOCAL'
  - '+:(gg-adm-dba-ops):ALL'
  - '+:(gg-adm-gcdunix):ALL'
  - '+:(DL_ADMIN_%{::hostname_upcase}):ALL'
  - "+:(gg-adm-tricore-ops): %{hiera('access_conf::tricore_network')}"
  - '-:ALL:ALL'
  
oracle_rac::udev::oracle_shared_disk_rules: |
  ## Puppet Managed File
  # by-platform -> OVM_MIGRATION -> MASTERSAF -> prod.yaml
  KERNEL=="sdc[1-3,5-6]", OWNER="oracle", GROUP="dba", MODE="660", ACTION=="add|change"
  KERNEL=="sdd[1-4]", OWNER="oracle", GROUP="dba", MODE="660", ACTION=="add|change"


# Directories for NFS mount points
sw_util::wrapper::hiera_file::params:
  - /global/dd_backup: {owner: "oracle", group: "dba"}

# cpdd01ak-nas1:/data/col1/oracle_ak/lamsdbp1     /global/dd_backup       nfs   \
# rw,bg,hard,nointr,vers=3,rsize=1048576,wsize=1048576,timeo=600,tcp,noacl,nolock
sw_util::wrapper::hiera_mount::params:
  - /global/dd_backup:
      ensure: mounted
      options: rw,bg,hard,nointr,vers=3,rsize=1048576,wsize=1048576,timeo=600,tcp,noacl,nolock
      device: cpdd01ak-nas1:/data/col1/oracle_ak/cplamsdbp01a
      atboot: true
      fstype: nfs
      dump: 0
      pass: 0
