access_conf::access:
  - '+:root:LOCAL'
  - "+:%{hiera('sw_snow_disc:snow_user')}:%{hiera('access_conf::snow_ips')}"
  - "+:%{hiera('sw_puppet_ansible:ansible_user')}:%{hiera('access_conf::ansible_ips')}"
  - '+:ediftpc:10.240.97.57'
  - '+:qadadmin:LOCAL'
  - '+:qaduser:10.148.37.207 10.140.75.135 10.140.75.134'
  - '+:sftpbpm:ALL'
  - '+:(sa-local):LOCAL'
  - '+:(sa-remote):ALL'
  - '+:(SW\gg-cg-wla-admins):ALL'
  - '+:(gg-adm-gcdunix):ALL'
  - '+:(gg-adm-qad-admin):ALL'
  - '+:(gg-cgit-dba-admins):ALL'
  - '+:(gg-adm-qad-progress):ALL'
  - '+:(gg-app-qaduser):ALL'
  - '+:(gg-adm-mqm):ALL'
  - '+:(SW\gg-adm-gcdunix):ALL'
  - "+:sa-qualys-linux:%{hiera('access_conf::qualys_ips')}"
  - "+:sa-cyberark-linux:%{hiera('access_conf::cyberark_ips')}"
  - '-:ALL:ALL'

# update url during testing. Once live, this will be switched from mitilinux to miti and reload of apache
qad_progress::miti_url: 'miti'
qad_progress::miti_dir_index: 'wsmfgt'