#
# Common platform configuration for OVM2.x & OVM3.x server migrations 
#
# by-platform -> OVM_MIGRATION -> ODI -> prod.yaml

# Production ODI servers (cpprod14 / 15)
access_conf::access:
  - '+:root:LOCAL'
  - '+:(sa-remote):ALL'
  - '+:(sa-local):LOCAL'
  - '+:xxsw_int:ALL'
  - '+:xxsw_dev:ALL'
  - '+:swc_pos:ALL'
  - '+:odiuser:ALL'
  # Adding ssh access for RAC cluster members. 
  - '+:oracle: 10.148.19.81 10.148.19.82 192.168.126.14 192.168.126.15'
  # Access for OEM agent
  - '+:sa-oracle-oem:LOCAL'
  - '+:(gg-adm-dba-ops):ALL'
  - '+:(gg-adm-gcdunix):ALL'
  - '+:(gg-adm-webeng_linux):ALL'
  - '+:(DL_ADMIN_%{::hostname_upcase}):ALL'
  - "+:(gg-adm-tricore-ops): %{hiera('access_conf::tricore_network')}"
  - '-:ALL:ALL'
  

oracle_rac::udev::oracle_shared_disk_rules: |
  ## Puppet Managed File
  # by-platform -> OVM_MIGRATION -> ODI -> prod.yaml
  KERNEL=="sdc[1-3,5-6]", OWNER="oracle", GROUP="dba", MODE="660", ACTION=="add|change"
  KERNEL=="sdd[1-4]", OWNER="oracle", GROUP="dba", MODE="660", ACTION=="add|change"



sw_util::wrapper::hiera_mount::params:
  - /global/dd_backup:
      ensure: mounted
      options: rw,intr,hard,tcp,bg,rsize=32768,timeo=600,wsize=32768,vers=3
      device: cpdd01ak-nas2.sherwin.com:/data/col1/oracle_ak/cpprod14v
      atboot: true
      fstype: nfs
      dump: 0
      pass: 0
  - /util:
      ensure: mounted
      options: rw,intr,hard,tcp,bg,rsize=32768,timeo=600,wsize=32768,vers=3
      device: nafgps21ak-nfs01:/ORA_cp_util_prd
      atboot: true
      fstype: nfs
      dump: 0
      pass: 0
  - /stage:
      ensure: mounted
      options: rw,intr,hard,tcp,bg,rsize=32768,timeo=600,wsize=32768,vers=3
      device: nafgps21ak-nfs01:/ORA_cp_stage_prd
      atboot: true
      fstype: nfs
      dump: 0
      pass: 0
  - /home/swc_pos:
      ensure: mounted
      options: rw,intr,hard,tcp,bg,rsize=32768,timeo=600,wsize=32768,vers=3
      device: nafgps21ak-nfs01:/ORA_home_gpos_prd
      atboot: true
      fstype: nfs
      dump: 0
      pass: 0




