# We don't have a class setup yet for this server
classes:
  - sw_mod_cluster

sw_mod_cluster::SSLCertificateFile: 'stores-sherwin-wildcard.crt'
sw_mod_cluster::SSLCertificateKeyFile: 'STAR_sherwin_com-2048.key'
sw_mod_cluster::SSLCertificateChainFile: 'STAR_sherwin_Com_Entrust_Bundle.pem'
sw_mod_cluster::SSLCACertificateFile: 'STAR_sherwin_Com_Entrust_Bundle.pem'
sw_mod_cluster::configFile: 'mod_cluster.stores.dev.erb'
sw_mod_cluster::ServerAlias: 'dev-sweep.sherwin.com dev-sherlink.sherwin.com cdapp.sherwin.com dev-posweb.sherwin.com smisdev.sherwin.com dev-microstrategy.sherwin.com dev-shercolor.sherwin.com'
sw_mod_cluster::MaxNode: '500'
sw_mod_cluster::MaxHost: '500'
sw_mod_cluster::MaxContext: '600'
sw_mod_cluster::sw_log_level: 'warn'
sw_mod_cluster::sw_log_rotate: '10'
sw_mod_cluster::sw_log_size: '100M'
sw_mod_cluster::sw_log_mail: 'baskaran.kuppuswamy@sherwin.com'




sudo::sudoers_template: 'sudoers.apache24'

access_conf::access:
  - '+:root:LOCAL'
  - '+:(sa-local):LOCAL'
  - '+:(sa-remote):ALL'
  - '+:(gg-corp-unix):ALL'
  - '+:(gg-adm-gcdunix):ALL'
  - '+:(gg-adm-solutions-delivery):ALL'
  - '+:(gg-adm-webeng_linux):ALL'
  - '+:(DL_ADMIN_%{::hostname_upcase}):ALL'
  - '-:ALL:ALL'
