resolv_conf::domain: 'devsherwin.com'
resolv_conf::search: 'sherwin.com devsherwin.com'

#ibm_connections::nfs_mounts:
#  - '/swdata -rw,intr,soft,tcp,bg,rsize=32768,timeo=600,wsize=32768,vers=3 nafgps01rw-nfs01:/connections_dev_shared'

sw_util::wrapper::hiera_mount::params:
  - /swdata:
      ensure: mounted
      options: rw,intr,hard,tcp,bg,rsize=32768,timeo=600,wsize=32768,acdirmin=3,vers=%{hiera('ibm_connections::nfs_mounts::nfs_version')}
      device: nafgps01rw-nfs01:/connections_dev_shared
      atboot: true
      fstype: nfs
      dump: 0
      pass: 0

access_conf::access:
  - '+:root:LOCAL'
  - "+:%{hiera('sw_puppet_ansible:ansible_user')}:%{hiera('access_conf::ansible_ips')}"
  - '+:(sa-local):LOCAL'
  - '+:(sa-remote):ALL'
  - '+:wasadm:127.0.0.1 10.0.0.0/8'
  - '+:(gg-corp-unix):ALL'
  - '+:(gg-adm-gcdunix):ALL'
  - '+:(gg-adm-notes):ALL'
  - '+:(gg-adm-scan):10.20.101.96 10.240.6.26 10.20.101.177 10.20.101.178 10.20.101.179 10.20.101.180 10.20.101.181 10.240.6.27 10.20.101.97'
  - '+:(gg-adm-infosec-admins-linux):ALL'
  - '+:(DL_ADMIN_%{::hostname_upcase}):ALL'
  - '-:ALL:ALL'
