access_conf::access:
  - '+:root:LOCAL'
  - "+:SW\\%{hiera('sw_snow_disc:snow_user')}:%{hiera('access_conf::snow_ips')}"
  - "+:%{hiera('sw_puppet_ansible:ansible_user')}:%{hiera('access_conf::ansible_ips')}"
  - '+:(sa-local):LOCAL'
  - '+:(sa-remote):ALL'
  - '+:(SW\DL_ADMIN_%{::hostname_upcase}):ALL'
  - '+:(SW\gg-adm-gcdunix):ALL'
  - '+:mdm_xfer:swb2bc04.consumer.sherwin.com swb2bc14.consumer.sherwin.com'
  - "+:SW\\sa-qualys-linux:%{hiera('access_conf::qualys_ips')}"
  - "+:SW\\sa-cyberark-linux:%{hiera('access_conf::cyberark_ips')}"
  - '+:oracle:LOCAL %{::fqdn} 10.140.32.22 10.148.5.81 10.140.32.21 10.148.5.80'
  - '-:ALL:ALL'
