helpdeskcapture::user::scohelpdesk::upload_key_public: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDaxQd74ynLWWsEk9GJaDEWL6Ygkxe5beia+mq7IkAxyWjeqJmUHJuhmwvVtPq6yZ5juVbGr2U6L43Bl4zdJzGiWXHIMXBUXmrVw67IU2FNytuA3CwTPjSc2oG/DI+im9EP/bTGZ77oB+AlH27EuQaP2gB7eolwEHGw+5SkyUwCHeTX+SbNqaOgl+lFhNkY96CUBXiWPscWyIbKkXVRLkZyk7UUG8zEkGh2dq1ZAu/N0JaJ2kfuUieC+XxEAmFaDqTeXVecxMZlgyQiyJrIFXrBWSY42TGDHjc1nonOZkbQVDoyc88IXiwdbittAY3ceFx4kthBSGq+SD9VIOZVjE03 scohelpdesk, stores helpdesk screen-capture upload, generated 2017-10-25, prod

helpdeskcapture::user::scohelpdesk::upload_key_private: >
  ENC[PKCS7,MIIH/QYJKoZIhvcNAQcDoIIH7jCCB+oCAQAxggEhMIIBHQIBADAFMAACAQAw
  DQYJKoZIhvcNAQEBBQAEggEAgDZYxQQkC6cR4s95/VU9pd/busE28SmMQEB0
  XpNmI+Z7x28kM3y7S5ynYoYeBL9StuXlHPo3LtkvkRCORq9ubpBVZYH12MS+
  KChUZQd+iuug1xukN/Y/Cr1fcx+o2NJ2jxdlKQRW3Huefz04nnQ0pkA1ENeE
  bH9H9A8+K9HmYIYXkVL6JIALsNf/D+RR4O0+FGJvcY8C2EKBB+7xk3OmxYXw
  w1MQ3wUG2kaJcCSFnOz6myUSwMfzGGDTYSSqEXYWacKAINrBDDKCLkvugTBj
  raRBC8eZ0b6gjWa80Lw30dSnniCBLnztISrYd6Pr6CA9D83zbSFUKSCxem6r
  H5xnPjCCBr4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEFizgKpSHUk6SYeD
  WOrtwrSAggaQBwQJke2w8dUY21e7XXj3UMImpBNkKuemlOCmbcZ1a2YVCVC3
  j8QZZJo3UKKmWERMUXpmvWev1mEocm3+gIPefch4s6LJJMzaw0InyKZPDTDy
  N2WUZuzShtM3rpPdkomvSabz1KVflzwaPi2XC3M27SSvEDPdZqrI6ZDlvhF7
  Uq644UhsmBPKx/93+XbnafWWcG9XSW5a3GlnFwxQaoKuWx5NjOcNW3ll1U0j
  ELfM1VL853I4nioVuqVoKZktjiI58eQW4v1e0WYD24GtV5R5tDV6TV35ZYOA
  moNs0RHWp3W6USYREBVNZKyQYWRd0EfkIWecmAIaQqlXxCVtyujnoqQaNEk8
  CKmnd7acZhpO3COyBgN+BLAb7besg2B0dU4nVoQlBl/7VFnoScA1aNE9C2Cm
  PQeNtwb35cLWd158h0CmVPjw4JMk9PWks9sG3vdFf5EQ3a19U3iSv3ovHzW0
  DNJgwQcV+oOuyfskuN6rP27ePq45C5Pes3mIjW7js/RiU8aJw3bs136cx0EB
  gLu6pv59mQcRd00h5EidljWeWEUhwqcdvcBT6Vv4aIe5IJuc+U+jMBmx/MQr
  +X4O98Bxw/v3j0mx29l1hFRStpaoLpIbsMqE4zIJFM9FhvSRx0J6Anjcg2yc
  qma4lLK70TGYaQjZBgtWFgCtCjdm1xVRw/XqVfYaBiDKeyjg6GMBQBsKp7Ij
  7dzpSGdBZ3NqWKBCRDy1NVancw5K1hS2TfVhkMRU+twFyh2rCHodHKhRAunw
  VLOrxtLIex0yXjoRj54igoNOQPp9DHcM92gEL72ncc1m0Zn6IBHnppfMhfJw
  fkZb80oKMll07WzFu4Ek9P1ch8qMGJavd7nEwlMqzK5WTea+L9Pk4QGl1dP0
  pLO0aMqYNpPkPa/USv46WIcARzLuGd+bZh6iBZY2RRLmfnf9d3gE0fqVvbJ9
  Ex94EHPqSpDkLC4uoojYZpNXVtg60L8qYYsZST7j5OVKR4MH88/3laoKsszl
  hyZC4TyoCr2jSSlTbU3WhIByGCwtePJSsDll3cwmS7FCwJc7b/yS+lakd0M0
  6KueQtGgVVoazCvrXwNutlGxtZfpNxcSpgcqn5fBOSrwan6hNqwGGvezSuZe
  27b5BMNM2df2yoxMiRWSMH3QTwYozcMbxFid6PM9BokjhMZ6KS8Og9Y8qCln
  1HfI5KoZ8wR9FU20ibGajuAG/6IUZs71wF2sAEDQcQaL1F06Jni0RzjOwTrE
  BcUyubWngZpDWysKIHkJvuwAAvWSTyxTZZj/YkpCfBhQqMNYWKQq2jGPjFIp
  J2HSnH5FSU3kuD2hO9jViiyW+PaDEvAxD5ztzjOwy492klLyoaksyOzy5vGo
  D0Afb1oQ38aNDsFE7E7Bq1u7wARij6bcybCBopdzdtwyRQWr4r/HESi5uFlr
  f44ar4rIGq+Zrj32SCFn3zJkYhO5rNXVJRJuCEbOLegoxNgKxQHTpwiBf0Tv
  3B67hBXfdX3mYjLgB2E+I0qp9maKBCQUA0zu+XKuw/NhCB7nmlcWyNfRrfus
  wH/oQEJMSXL4HQEDP2/AUCQgu3dAOq47covg+7IQE/MptJ+bcNMdK4rR/7qQ
  G2HS59OxedT+tLSFyacIK3PHJ1bNOGOPdt9uiom3vJuOe7y3CFsa7SExmWt4
  bfy/zsHMsqBLog6hIqC8uXVR4bzB1tp+88xSox8Wipd3EPYJ7SE3sJnv8c1+
  CJMzHqsbO1SpkeGEa2EYrih+oYNQ4T0hI7iHc3BSZSoOQonduPSb07niIDMY
  sHIK9bLnBA6dtjAXUyBiQMq6+9woHX3n2/+P7lHIk8nDB+I1eL9PxDgq8J7I
  6NMOdV9YTdzMQvkO2TMrMIMFsz6s7jd1CM8UN6bGmInv3/x+wet/41tbqlZI
  8FTlDJ+eGlEV2CqAB0kwOrFRoEZFAXtl195FA+cHAMQ3fST3J5GAaW5B9WQj
  B4mZHhqWGvwP4lRE6SEvYwj3QzJPDDsrNffAUrdxPRSDR/KDveZY2mzKirWO
  JnIksl1DPo3cvasW1NxvQ5gc2I5zb3ONH6g8L1XfiYHdLejQRsY4n/YIkM1K
  CYb2VFz2AoBZPc1J4iwYTaXhtDGOMpQSrEdjFplRrQGIBmUpei8AFsANjvzK
  YyHPPiAe1aL25qRVwHXXRnW5S53PJPF7VwF493MdLEAujnPbMQFww4ZK93n2
  c4wm4OPpvGA8l/8PFsM1D0fpL88DpwBu]

