access_conf::access: 
  - '+:root:LOCAL'
  - '+:(sa-local):LOCAL'
  - '+:(sa-remote):ALL'
  - '+:(SW\DL_ADMIN_CGATLWEB1):ALL'
  - '+:(SW\gg-adm-gcdunix):ALL'
  - '+:(gg-adm-gcdunix):ALL'
  - "+:SW\\sa-qualys-linux:%{hiera('access_conf::qualys_ips')}"
  - "+:SW\\sa-cyberark-linux:%{hiera('access_conf::cyberark_ips')}"
  - '+:SW\sa-geamdm-bamboo:cgmdmweb3.consumer.sherwin.com cgatlweb2.sherwin.com cgatlweb1.sherwin.com cgmdmweb2.consumer.sherwin.com'
  - '-:ALL:ALL'  
