# by-platform -> OPENDCIM -> DCIM -> dev/yaml

opendcim::ssl::key: >
  ENC[PKCS7,MIIIHQYJKoZIhvcNAQcDoIIIDjCCCAoCAQAxggEhMIIBHQIBADAFMAACAQAw
  DQYJKoZIhvcNAQEBBQAEggEAeXW/MUYpdOcpj0UVYPKyl4WppDXjdtpLBcdH
  dJI63dIWRWjcu0HUzJQ0SRaxoIStnP0vRvyPaU7Fn6QhBdqhwDuCBZIM1hb1
  w9I8vP6aYvLsg+XGwyvZXItFEt32Ryw8s36ttam70GOmogzqy07mSBLLCqqE
  RlEn2uu1JhBqlxXFu5RM48fyE/WpcL1gPmqhmF1AUqB/AEbXzeaazKJFKQLE
  GHlw9I7c8Rd7ZnyfIUFYH6E6CN52GTC+E25OgcDnXyiVzChnAa4pshw7vCL8
  SetprgSLC8c4GQRoCXpA8G9ysILKBzcIGpEgJMS/9XjENjpq2+DtvTWZO7Db
  DYPzDzCCBt4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEHCdV1KMDix+LpH9
  YLsxQfaAggawJ8qseyHJh+neh8udebSBC3ydk3ybD/bwvnDDZDG7Fgrzj3VN
  rxI16J9wy9nsC+l2N6Q9ZaO+nsZkS3FAIL0df2a/YRbexof/7yREEdXHOmsE
  oXPFLEvov64T2TrXPJkKeaceJp810xanqEQdHuXaWn+P1FJ/xAv7QJPMaq5q
  nINW0qaKt/6az2GoRFxqThsPba4G8WVwxqAXhyNo+YAOv5p+CEAsDeKvh5AY
  H1p2Ka+Z/s2+hxTVpezKcJIwbhdS19T1/EoAiCi7MzH0FWlsmD9MJORZHZTk
  8Vz1r78Jgxiwn8MozNkx4aM7XMLoLQAhyAO5laADBaUHi4XMUpA8cww3Pmwd
  n/4oYmNCyItHl/ODlWcUXzx++zmvf8u33PfaLo0SAhocp0lao8b37CtH72UZ
  ktIMPTPj6gvQAMS5f0mTXiMM9c6VtcqzoPi85lwnKd1WQM+kebf+j7Su4IGH
  YAHnECk1hX/WDN2BBCAIqKvRweazE8spZ14kfi7t5pDxPhlm7JL7KRL8Ooe4
  vtPwDKnocw6rnyQH8D1Qhqn+RTwBBIOFxEdvDYO+kur2/pHac7YXj3ulPpJB
  /BFqfyf02bX7XpKVyUsMLDNWRmw7q7vRL75uTcx/fQgzXXkW4Stou1G87E5Q
  i4Jojc+dsXfp9UwaAydmDmwYVU8VGnqj+ShU3qAr9DNNAECvKCoe/1ZQJ1c/
  0iycDoj5DiKlqOZHtrtn4qu0bua/R7NjBoNRBKfu4o23D1KX5p//pD7NCgK5
  A6eq5B1mlOizYnro7S6pFgIqLO3TDImAa0A/7gT2S/3rOZmT+YgSGK4l+kY2
  HWjcxFFkcEZsUmoM2/sZYetaPG/KPrDUhslpTK3KTmp00kxttVPQbPK/e9w3
  dMjRxNkR1KrMCqi++IQDRIL9zeMizlvpI5tW1Fb0juybKWKGRGciBbtwgp7V
  amCdvXS4QIbDAdRQa9+XWq5RYLBtfRPt34ii7bW6VU1z4wFK5QQHemSVidsF
  b1l/ru1Tg/nKYgWa1hPU4RDgj7kwRuNqUD4tNNZfXKV2ixbSy82iB8cZBXdE
  eumt0RImj7W3SOBEoO/9JbSLd6VpqK9+e3G7sU8hf+W2eWhJwL9qfLQrKjBM
  10V3PQu1iVgHvJ3XeDlogG9qqoLm4Rawji57Z9wTTLLWhBotxwOfao9UeLAC
  POWd0hC7DVLiu40fTCFp6mMyAhwrnOpAF9TxE+4l1eRtKNnbqDLfOsDzjYWA
  vrXnTjt5tZixacMenDFKwqzNQOkFzlIrzws8DDXUEKvuEOdoRIEnLAkbXAe5
  8PrcnQpDN1uNv3RWgbI+0AxWiaQbnQgmDvtsxhpEHxGTIPE5fNdb7PJP1QtV
  WJZPbE/3qHyCNeC2Kb1q1b+JkX67gsU5kXHwZfOvdUs93RM9bGKgSypsb8OR
  pVRPZcJ4t+p6zK5GEdcbIO6jSdRz+OIpuTwEw5IuOHWYdSsR9i9ugTQUM96C
  bd4ig83//k61m0XuM4Fx3YOBVmVXbe0oxo7Es7OB94bYJLFI5WDeAvWmhxh0
  dSFlyx3/jhzMqxfAl1F43TvXGWIgJ0oob7rMZebo5ItduZSw08xu3AtAT1DZ
  EGib7Gp0jWV5vxCe9NCsKd2h+zGBtKP8IjjI37/Q5x6N3RIpKYJy64xfUgOO
  +trvB7fB4XkAsY/SVtOaIUfeg+nmYVSS5IdgH0qkr1FqdG2Fr1j94wc9VZqL
  BSKib+e3Xsjq9dtzpdOlvwnmg/3OLhUplIGcjjhmsaCY6IcCcDh7HS6t6ZeC
  KeZfevbWo6+lyV9xkg/44ty/6RcF3RObphrgBGvMuF+BwAhLxqgsuSAnfc37
  nhfndB37xL5NDvdyS8/eXzqvlYKhG9IlZafNfHQGlr//KRApkp9AJoxQaCYE
  4EhswWd6KJkbfb/Wck98pGiBdrSdQnjGL0IaetwHDo2TmGOKLbebrvUOgaaA
  RbxJoNNnRyv3Eikj9iSSbdINoSjQThszb4u3oTZaJ2PE7jk2BjZcLPlvWDQX
  bpgjhJU5YjgjxfEreEz1GPZcb7JDDpMggIRxhgZA1cvTAGqL35wUdMA8cqdg
  iburvSDlWxva1dsXYuawm4VcnebP1OfIiA2Vh7ovp2vBt3edVtGCcTbY/zeg
  dphvlHU93Jy4jWUInIGTQxfvR1nRMDrEZpsxPhOM2KvSYUYEkTr/A+6B6Vdm
  bo09ZqLIMJQsvwUB2vidk53u4p1LRuKem31ciblR9VxdfltN/InuDLh++5NK
  WGPXaTbTur1Oy/o=]


opendcim::ssl::cert: > 
  ENC[PKCS7,MIII7QYJKoZIhvcNAQcDoIII3jCCCNoCAQAxggEhMIIBHQIBADAFMAACAQAw
  DQYJKoZIhvcNAQEBBQAEggEAL/JRzyGCr+FbzGaPbQQD3R+o6FHSgPbHmShQ
  2WYX3pqf5HgJO/Kb612MK6IF3qsEQrl7UNIssJ6kv9ZlHgo3xdL8BtS/n0FW
  Txa2fangnknJKUgRL8gT7iRoAN8Jp8UJThq3WDsaEMeSODwYEiZClin76JGA
  9dH0LM2OWwGZ22eLMBB5OOaGvo8NvX3v4CNMunSBmJQ6nr7vOcIBnBCYSCCk
  vc5M+78cKv0oQRcSErvVsa1CyOL9won6htb833hL3lCK/G7IFBFVth3qQinq
  XbLEiKu+Nvmw9ZgMGcuEMD7fus3T7G9a9e9TC8UZr6t8JSvsqFtiiGDKpw6g
  h+ziVzCCB64GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEGkEI8Tx1/WLk4wX
  RpOEIDCAggeA/x71fCFm2wYc4NugJp/0D4kdxMvMIr8eGB3Rs9sJU71PVKea
  AcLAZAqlt8r8z2OHqK++LanRkP8SQJeKCHzOrxENP0C3BrEUFJdEcgi6KFe0
  1kOHtFxSy6NvPehuHdCgRzjenG5BMMG2xrbadIQXhnHrVMhclxDfWj9kAHMp
  3XFL3tBJP63vpez+0Vlnz6wQp9DFdcpDiMZTXdMFRzVBflBTpX31Pg7cPmD7
  xvpaq5PH9QjuzP/Wty3/hXBPiLZnFBL00YRt9J+lo6thA5LkopMcF/ijylVp
  TxeZAoo05Ti1ohFFEr/sGk6Y1bDAtdLTJytBAr8k2iZbic2PXVprgIQPXeSN
  6JLfvtBkAhgb8vW2vN8WHfKg1q7Uu4MbnaiEeWPUsdL0D9sIzbS8gcGMux32
  6BzSllVOQI0K9Wb/5mjjAGgo5FVRyMq9Rc/cgU0BIqKmxAqoJKRQ1d7FoZpM
  Y7QwZiNhDMAyv3x1yn1MZ061hqxRdPj2tb17GgkkenBWcW784BIuN3FxJOD2
  jJLBg0kkQebtsmtdlwBpVlZOIWXnITA2i7H6JdrXvA3x552ID7G6iOU9fI06
  WnNVodet5AHNepARXFIXhNKX/R/EhLXCsyDrO7tR9criuDE7UCRTzB8hojDC
  E0KZQKM41z92nXS5w6czdFuLqLesTjlFOOxHsaxw9cVKr/mLAEGouHOUqcdt
  nOi+J13PgoUEoHfSBYBigGtU1Sc4PCAw6OGQY6yJa4Oqf1R10OUCJT0u7Q30
  i17UxwL5xQSyNFbcLhhAivgJdcE7zsT7DdcTAcARNqKQ2p2vQ8UMR4Ka/77/
  cbuw4dGMs8+jlCngWWoA5gvOsd11ZuB+CYg+wDnna3tffxdKm044rshwmvld
  s+pNCuzXeoSl29zhFMPuQvQ12hwTMuKYyIquXyrtspBQpBopfTb350I98yRo
  FZgpP45UZ5XhlCIi840AdPmAEmNJs29AAu7o8lu5wOUMhghgGX5LfR2cPImd
  oB+xXAcWsGmhxsXd8bs2w2Ud6G6ACbrdlqfn42qjBYryWAtax5fDbX7HR+y9
  Ib5mYmgtdQGrxC3GTjR3UJESuN2VISR3M0CIsI8VUsPacD4AB4mbczmXOjDV
  h1bklMnRj9JSWgJ/VROGfL3lTpnX6n9VcI7G+vT3BGqTbXvDGqgSQE0OGIz6
  nn+uXxFfh2z8r5N9hZcHHMziF2/Xq4OlNHNFlMDfb9WsA5kLzJg9+WwBWsye
  6C4HRoouAcS9binjWmht7tqwTxbEIKkGbiQoYf2c0/VxvzUeE0vUzQ+eTPin
  tmU86L1aO4UZkluVCV0qgFXxmX6+lGvyqqPxW5ePfdxnqpWyq6UNqt8/4Iev
  CA0Sm4RXW3TGGswbq/2ZMOQrhxfLDrUTDc3+jQR34t5S6ZDGob9hb96SwvoJ
  L6jhCYV3FEQL4wHTlVVFt6JeLm4lUBtJE0WsC9TDujnGH6op5QMsj23NTXxF
  AHLnf/E2b1OhhH4WHWq9Evdq166P/27XRwgYEuwT9RS5jvahJajj4uhOfuDN
  vtzqmS3MpYVItem6wgoTsClZFbXn7LUuUuXTiXPTVfxRxT1SB38JVrXpX8Pr
  +YTuWcgaTR9QBW14yFxONcsYlAICOmx1orlMe0XWylyO8DqRqJl1Ygrfwg/s
  4/ut6CFZDZxSFkRxxASjmphfzaS2ZfY8SQUpgYE3ru1pitvYaq4C9mT41gF9
  CIMhdfi3dhkMZU+jDRHuo+sBDGQ+eLMiMY8aYNwcs+BlFcodrWzeVaq/e65Y
  l6ZJiRER3j9pEls+RAwrHPU+nKEQdMF9JI8n8ckWsPQPCIuzCwjqNA9eutWH
  p9bNBQAxaGpvXe5mYf5li3gtggZtqQqVciEMpMyVevYFleMePTBkHaILNrGZ
  L1V81WKg4yX4fHXfiBpzi9Q2MB1pDjEvitI3ltesSSQFsdB7/ytw5vpIAcni
  KfYHbfvv5xRBAZhNirV4YVnOP3im5oJqGt+wQinoicH9a0BU0gRIeMfYjYYm
  dbtMxH/s8HweqfB3fjE+BFQJDMJ61UkIZ7UWfJAIA3zvQRkaklXmZioknhOE
  +0IU7udFj0rF01WPRs/a8y7NkHEXWsYlCM/6su6pCqZA4NIswTVx9yhHFCZn
  vMHyl1x2YIYqnDp5VRKwLQmVB+tSkrpQxp/BvjjSfZWF8vnU7SYlqJNni3Cu
  M8GJUBseBVr2nUFaGWV45WS3tdrVaLY2VTszqZq1XEYf/vOYfiu8Wiu5kZf+
  dAcCU1giMu97kXPCPt3YTpZWkfVVZgUj6GtSDCrwyqh3hzWYU8QygnB5l46x
  10gIDb+Rbs26e+DGudt1jlSzJZSA3Ho3HGJtqItGryY1+4+EhW3yinx9ggX4
  WqUhNVjtN+lWp2MYogZA4snsAYJKcedufLCKANNx4X2NSOOBzEf9VqjE3Ket
  f6x09b+IIXMCgLxHk+FfZLJfb+JCWrUQGv5Gm5JAm2MwbEJDv5Lf1SABwOP0
  eStqOh3HtCZ1H6d8IWXQMFD0jfByjCAIHxRo2agTbzjKN5Qs+YGe]


