  access_conf::access:
  - '+:root:LOCAL 10.148.16.105 10.140.16.100 10.140.16.94'
  - '+:oracle:10.148.37.52 10.148.37.53 10.140.16.48'
  - "+:%{hiera('sw_snow_disc:snow_user')}:%{hiera('access_conf::snow_ips')}"
  - "+:%{hiera('sw_puppet_ansible:ansible_user')}:%{hiera('access_conf::ansible_ips')}"
  - '+:weblogic:ALL'
  - '+:(sa-local):LOCAL'
  - '+:(sa-remote):ALL'
  - '+:(gg-adm-gcdunix):ALL'
  - '+:(gg-adm-val-weblogic):ALL'
  - '-:ALL:ALL'  

sudo::sudoers_d_template: 'oracle-weblogic'
