access_conf::access:
  - '+:root:LOCAL 10.148.16.105 10.140.16.27 10.140.16.28'
  - '+:weblogic:ALL'
  - '+:(sa-local):LOCAL'
  - '+:(sa-remote):ALL'
  - '+:(gg-adm-gcdunix):ALL'
  - '+:(gg-adm-val-weblogic):ALL'
  - '-:ALL:ALL'  
  
