classes:
  - sw_docker_3_8::node



sw_docker_3_8::node::log_server: 'udp://prodelkstack.sherwin.com:514'

docker::registry_auth::registries:
  'docker.cpartdc01.sherwin.com':
    username: 'sa-rancher-prod'
    password: 'sa-rancher-prod4builds'