classes:
  - oracle_build7::autofs

oracle_build7::autofs::nfs_mounts:
  - '/swdata/nfs/oramedia -rw,nointr,soft,tcp,bg,rsize=65536,wsize=65536,vers=3 nafgps01rw-nfs01.sherwin.com:/CP_oramedia/oracle'
