---
- hosts: servers
  gather_facts: false
  become: true 
  tasks:
  - name: Run r10k
    shell: /usr/local/sbin/r10kdocker.sh "{{r10kenv}}"
    register: hello

  - debug: msg="{{ hello.stdout }}"

  - debug: msg="{{ hello.stderr }}"
