classes:
  - profiles_unix::gsc::oracle8::rac
  - sw_puppet_ansible_dmw

postfix::enabled: 'true'

sw_util::module_param::bool_exec_augeas_kernel: true
sw_util::module_param::bool_exec_augeas_limits: true

oracle_build8::kernel::vm_swappiness: 0
oracle_build8::kernel::vm_nr_hugepages: 9728

oracle_build8::kernel::kernel_shmall: 1073741824
oracle_build8::kernel::net_core_wmem_max: 4194304
oracle_build8::kernel::net_core_rmem_max: 4194304
oracle_build8::kernel::net_core_wmem_default: 4194304
oracle_build8::kernel::net_core_rmem_default: 4194304
oracle_build8::kernel::pid_max: 139264

access_conf::access:
    - '+:root:LOCAL'
    - "+:SW\\%{hiera('sw_snow_disc:snow_user')}:%{hiera('access_conf::snow_ips')}"
    - "+:%{hiera('sw_puppet_ansible:ansible_user')}:%{hiera('access_conf::ansible_ips')}"
    - "+:%{hiera('sw_puppet_ansible_dmw:ansible_user')}:%{hiera('access_conf::ansible_ips_dmw')}"
    - '+:(sa-local):LOCAL'
    - '+:(sa-remote):ALL'
    - '+:(gg-adm-gcdunix):ALL'
    - '+:(gg-cgit-dba-admins):ALL'
    - '+:oracle:LOCAL %{::fqdn} 127.0.0.1 10.140.32.22 10.148.5.81 10.140.32.21 10.148.5.80 10.140.75.46 10.140.75.47 10.140.75.48 10.140.75.49 192.168.199.50 192.168.199.51 192.168.199.52 192.168.199.53'
    - '+:grid:LOCAL %{::fqdn} 10.140.75.46 10.140.75.47 10.140.75.48 10.140.75.49 192.168.199.50 192.168.199.51 192.168.199.52 192.168.199.53'
    - "+:SW\\sa-qualys-linux:%{hiera('access_conf::qualys_ips')}"
    - "+:SW\\sa-cyberark-linux:%{hiera('access_conf::cyberark_ips')}"
    - '-:ALL:ALL'


oracle_build8::rac::ssh::grid_pub_key: >
    ENC[PKCS7,MIIC7QYJKoZIhvcNAQcDoIIC3jCCAtoCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEADMI0KXmSbBq83eRcY8cU8gCQnhXugNDnY6sP
    6YP9DQaRTBRxYriv+j1t1HVzG8tEgGiJ/1mnhEIzO6S611da5+HUm4d5xbbk
    HCFWVIdxpKOMPREJzhzhRd3fVIjcBIufFgDevLdBpTbGcAMOETawib7E0kDv
    RrPdY5RTVJWLZ2vNKDdYpKjkGvq6KBEvAAbtTzWT+/PrZAfYrHmUZp011TT+
    u8prj5ehcLT2x2/GgDQhZIi7MgLBMtjPTDYF2L/InsrRp9GPH/eklBAeVrFF
    liqUlu7Dliq5BFo/1F8FK9/obNaURgScxQ7RzaJeLsgwMhYLbsjuma0zNEEg
    PW+UjTCCAa4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEE6h2qKMEAIIixX9
    cEuTztiAggGAyDMvcM6Rri5n2xGojdNv+c//EQzDZ3suwZKKdyfeIuK48pkA
    ZKVgPuENJONi6uIgh3WnZDcM6ebCnwLMWZ++3W9bNwGvhzcmM313s9mcO0KA
    /9X0LbWfsw6QZXB1yzpBjAn4mpBaJWNzigc+fOEgk2NxhcxwknRtiOqW/O49
    3lmt8CrKFQ5dBcVQ+V8U6cFb+I34aGjdm1Y+HWecGgGUOMyPslwJ2/YUj641
    GgGsssBBfesBP6Eltjpxx9di26zTrQdu4gCT5Y6tuy+Mugrp64v236g6dcvn
    Ay6ZsU/RZI6s/85oW/63IzRRpWMNtkTSSEEi92ZvRvS7mSUqUsicl3OHni1+
    eKArE14WWejmZHeBPRRSvWfjgxRqPUQPxkIV7rPIePYUSLXX9Z0/QNpbR16B
    BHq8jvIpphORunvM9Lp83qu3Dpj76JwJ3uspY69+fwJnPGqudchtogFkl/eQ
    IT8GnSDDLpVsDgI5j2kBqXaC05Y5BDip+YLR3VZ7c8Nn]
oracle_build8::rac::ssh::grid_prv_key: >
    ENC[PKCS7,MIILrQYJKoZIhvcNAQcDoIILnjCCC5oCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEASoaZ2Q9yqutlQPJGuPXBJ04N9Si9erH4IRV3
    7D2Fo3wJ9BNumr6GG5D6/kG6fAQJnytqxhcDP5RsVOsc4G8i5X+2myctBNQr
    I+b390zVVhC4FhbcF4IEAXZ0CgLr4coyPjWN2bdLZa6HYjsWTgFkQ6A6g40k
    Ksfcarug6MOVQKC1SCCUEWxo8qaGkfZYYfdl5xKlzSzeWEVUi1jctTDxykX1
    EqkXAZG/uFO7nbmjTM4MncM2xcRyo0uCEPdpJ68NlfM9e0FosYLtVodQJoiK
    fkRpX9arKKVvIT4H2L0HJ/xC4wx4JQJkG0vdxMZtWiGsfjS8HyLIFfTtYhIe
    9FV0tTCCCm4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEHfE8rk1YAN3TRyF
    KKk0aluAggpAiaaAIj5dU9JmsgRr3VTHEAkKGTh7BMeD5h3puK27B8N12+yR
    VWB96+/cm7iJrZjvijJ0q0Zweq0bYj1Kvtk6BDJeY5/wBP6JrBfBZLw1mWdO
    vCkK/c/UuuPOcdlCS6IYtdyY2gTpIW741pJrmMdW+xYYtCJMYshgTa1Y3BTW
    KB14hmkQOoS1jxUsof5kxsgzYqosdOI0wODTDjdqUlGBGPZDaSKTAoZOHiyM
    T9xXIrbWoPyVP4wz+XPIMBOJ3BXkMho9vldNlUW+UdUqRcRlDKLH+CJ6obkQ
    NbaddB+KNQD5OR35BSKlHUOc8fZ4mEBOc367BEWG3V16qI4kHbC5C2WwZyts
    W8RjqDO3+k6z0xjktbUldHt4Rd/n8ShcMAPjAIhsHC4COhGnLGIRSoLB0vc+
    IWoIg5riH98YJgBa9GP9uAmi4pT30lRuNLDORNKLqNfHOtOXfmjdst7syE07
    rqZVuj64suAVYT2cBJjan6Rlae62nx8+oNeiTEjx9DnnYvUlmfb70Xik8K2f
    gDGKFbPEgPzCpwNoi79T8Xu3p7JtQ8xCLI3xWU57ymppNrjh/dr1IW/ROQnD
    W457an3IP55oOesics4PTL+0oz2xQMjSPSDNRcrezrA+uEBgza65X0jHjpzo
    /a3cKMI/1hqPhRjudjzhGo9+FC+Y3JrEb0mwoT30suaGtwDtmkeVii9AkjIk
    FBVR5D1Wn91dSxNXZRLzjzmBwc4ULbxNdlY5jSC6kKuNA30iqyQVSdQ496jG
    T5pNM8/omN4NYyQscjnXNRNT7yzegOpe0vvl5ATH2WeCtIsmLxnOUWSuegbC
    c8t5VnHO3D3YjB8uYgj1/MswRWgJfwm7wIR5CkzL8JXXTPyqWYDE1Afl/0xm
    hldVNSMBieyUo8hMwArAAX+k3yJMS6M2avHiqbAAimseBlzEwoz3I37Ae0SF
    zU90MloVLfJpNcE7yeyPI/r4PLwXaYbUo+2NQwyJ5DMxyLT/qwrMgTVIVhPU
    JriVzHKid7FKJK24KoQc7YEp2QoueIKWmn57FHrl92MH1ubf8mbdiSAAkSDq
    U5AvxdFK11D29oZrLisE66zInRCuGcPb+u72oABkV1cId5d6xrCyxeXUzaS0
    I5Nh2jGolCvBY+uXIy2rzHezP1lKKCu8Dp5ld1x+K2RaMdxOWP8gr8pd0hYl
    d0Jq9qkTmF4RX5JV9dXBrRIONsbluNqPHmSAbuqecy/I6IZHoNRfUFb8jC8J
    ghcBQMtIIG4OgPPVwGpY2kxxRDKfL09BvkF/OTwM+R8oApvt5Vw7yY1Kfw7q
    78GIFUDCV3icrFlSUVOc4Wf6ICH8184Obv/mG5s3062zmec05Vrv2UgYVBW6
    9+ZWP7alOxYifngYS0bUMfTjvE0i6nzmCFeUm9QaUJw/FAv/oID694lO9XLS
    j7M/4PcPL639Ki/PYE3AYWvjSwIRlxmRAYy4DKXhJ+ZlrPezzz40iwENWeF7
    YBMj8IlJzFs9pEU41PH42rmOvisD67ltO03HBW8RjTL9BD2ZiG3ONBcqC56b
    uRDq+YblZBPk7bV/1lt5aH1wr07s3Z0dVUq6hwyUtS2+empjwnE5X5JQEDvz
    KG/igp6BHdqQezza2Xkg7T9DTtZMj0Rw4OuoU5EeWerGhEVYhyZXWNKK/PEP
    fBGg71t6YELOMfKAPw6UqvMjtd1fyuEA/Lhw9W1p03tzzJdCJaqvnvmyNaFw
    I/XNXyd8gLYOfnfjR/KefKm6tZH5frnsy9XHNTnIvI80snZq1zcZGRjzeLdx
    LZJ4Tz2qPWyrH9uqUOoCE5Cp3JsA16q+6P8JJk7ZUpQRTfYVAhunBfTrApy6
    mRI0vnDPuMWrC9pay7aNgOTSrE79dQqiS9gMxRvicody/JbfjMHPEXTIXuv8
    2yjEfNn9OfVT9mk1Sk4OasWoD/R1cjIFPAscoduyczDtj57P/q4yTX8xJZTi
    7f2LdR6wmyccUeeKDoyyNzC0tS9PXnidWJCTVDjXKXd7JHJn11ce0hwUrDOd
    UcpV85i1Y6JMT8c41tudcF+PvnERrlskBuqCVLDWa1ggIAD36ha2UBHM0HkP
    w9361cbuWdygj8wH/A76fQnK2o40YGpUeZeMP+36H4JYNyIq9JAO/xleHYks
    wr4IsoSTDfhFrpd6t2DSFYTEz2XVbgFe4MtsaJOwhmKoL2FIQSqx+QNz7MXr
    noj5lEJ2r0RP9S/QArwUrdUkusyVlMHrY5wkQ0vsjIwqPjeMuGCxr9+wXjUx
    V5UdOmex4k6xUU/m/Kiq6j2ueWpRURItbH0Bma+PXZbfM7Y+l15TeBMRWhO8
    4hw7eC3ihxE/+4MrUyEQZCpeengbvXWa2N/Z8gEkg7Ihb9K8Bnp9xxufIg64
    7Wm3jjo5wB9w7zrQ1xI7LxSbLjjxyRdoA1W5zCFIHf2jtnNozGqLdNSapPkk
    qPCRf6AWpQ9eNwNzE0aHSj8dFy6wmmm2jkL7zibkSWQO1U+Un2G7ZxMni52Q
    WckVS8ygBojWHLTsiYCQBn98LrfZuVEg4QajjaJDb+6q5pW80hFZTXlz7g0q
    7ZXjuXk1M/uklbMEVpoU0DYlDVRFwe50abLE1HpXRbZEK1NdOyga9688zU7X
    xZhYA/XajX0rGkpZ4wn9X7m1AS1m992JdMUu0JskYz71gkF4/tPwokpthPGg
    DlOhFgeqz59vOXFS8Zz16gC0Ia8tfhAOKssUhw8im2mU9LEUKFu7cVLWxvEx
    amrtv+6unBTg5adhCvshJEEVdUnn6XNcpgxqjES6e4RsQ3zAnB6cLS7wGYAY
    8KsoU0EY7M10lBClwzbrCXuUCdlvEgOy5IEh20cpAx8phZTWAU9AQjg219tC
    AcRBhBDimcY3pyJNOz57kGUDDIS3EfcDUrNvlpYYg1Kf+uTMXRtUcqL3NWyy
    OcrfJloSZ7lFjss116s1X15Etis415bRErLeWECycFOAyhF2j3HiCbm8BJxd
    ezM22RmEKaAERAREw/GlXqb0nLRzwRKkToMfcSbbVfBykdiZFRUQr0ciVSod
    47ApGl4Uk0KgWDf0s4/Th601pqNuFjtlKnDE78/j0f5R20jud7ofuQQMCW9B
    eZgjMsjOx7fz65Gd3aOXsLyTqHiceCg990Vknr9lycQ2cwjUIzYH0KG8Un+Q
    OMW+pNXW7i6M8yeZ62cIIeqcu3z+15ELyVee61kidVKOFPcurUb0VDNoxKCX
    GuxyD18GACboh6EEMCEEwm8GNfTroLkILv+DSOWcnf2P+ljRO4rQIL92j71G
    N8swa5hYJLMjB6wEC7PLxae7Ks0kI+vTR0ZwYCtllD+4ivq33q+yv1k5QGc3
    sTM0Wfmg7mv0CWy/zjHKaYy6GECbCxuD/Zlj6u8J5mea03dBkpU5ebDXbD5T
    jI5QdFCpBlARBDIlS8yynTCYIzuYAo7AzYLdOhOyjbQu02CKJS8F+HMS8W/R
    r0kfw1D8cD5jize/aQkI8PL+KyH5WEU=]
oracle_build8::rac::ssh::grid_auth_keys: >
    ENC[PKCS7,MIIDvQYJKoZIhvcNAQcDoIIDrjCCA6oCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAIh2ouGnbDQYYjpXQknaCe+idRyRixCA2ldgy
    TBlHD/oPSg/dHbGP9CgLXb7ymwu9vwoXxan542tU1cQYcZbbd96NQXCd4DyT
    KSRprhSBtsWLDzkwZrU/aAXsLVmRJ5knrf8nsoG307kpkZCuBgAZv8ThF/Io
    XLgFAHTOw2gpn24K+USGO52q5Qmw5p+M5nwRG/qUK7lrW+NCVSpVy2Ate7QD
    MaVHTavUd2SlgGXiyTt6bUnKSArCGE/mWFLR6SrUWyVvj2cMoqQ8wSN+mLWo
    DYYiJrV6TxMguwMBsmghJs1iDyI3APbWafMzsmnhrHUnLEdsEiSQeyz+7E8U
    UDYJljCCAn4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEECaikGhwaZxURtAW
    VxOLetGAggJQE/R/9zSACKRBd8cItgW7MX/QqnCgN5ILHmOmZy0jViWDHHyA
    QMn2jqGmRO0KBV9vVWles74ObgDf6dzFGgFSU4TTvubtXDHAra5rqpZP6kfP
    AFUS3228cWdNgwFJNR9p/kjFiCMRBHN3XZolCYKVeAkvkMmNiaOXxpd2LFIl
    jj9FZTYCZMg23OZKjRxVHZ2pDZoG87P65TZV112bM5ZIWxU4chP9n11FxA2v
    vXUaduAVpWxBHrw8+gPDWsXVp820uhmO61Dc/2emAQ2e3HcDBM/Q4GuVJSUx
    No5J85SiyOcH1t/9GvY4oQyK/dt7SVCi5whM87MIkD4R15inxNZ3gOWj9/1F
    x0hMfJnntXJ6Qt5l0v8jmvOPPKiwlwFdMqsiHrcPLrp2Nc8HZTD06pPYGO18
    V1/kcDHZkYGd9xBa7uw3y/olXY0pc2m/v+pIuvQuGNrY0q5dlFzgK8/L7dUB
    vZ/xkfqvj5gkoFtiYLfmdbdSX3INbXBdoFh5IlKTIOJp7+1i682SVL3JHvYC
    IAbdyNgvsWhTaO7vC10xIeRGEG1G87rXyq3RHD0sXA16ooCqDsg9z2uWXD5Q
    5sJ2aGF5gr9MFQCe9UlVYbz02kDso9HzL/XEXIyGSpIX76n0G1fPawwcGqKC
    je9rQHqxRWluOMlu+It4h8vQ+PPBS2zPD121UAffBuDc5sYWVhBh/23jqmQi
    RTbQlJGWppO6cEKk6bFKkBtlkXhJA+kjj7Fi8gtiVSYJSaVUk6li1pqebXpk
    XQrGGlvnzKVWB4KC4JODcQ==]
oracle_build8::rac::ssh::oracle_pub_key: >
    ENC[PKCS7,MIIDnQYJKoZIhvcNAQcDoIIDjjCCA4oCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAfgUVg9Ygt6nM7eWgMxn6AZKCDAEhijlc3zqP
    icj97g7kH3V26OgrCeNfv2jgFX8ZcL3b3u+Wx8zi6TZvst/0rQ0ksMAeUJnf
    iThQB+hXFT0v0lomu5RT104oF8poPH7WveKz7uu/vP4IXA+rNEWfoVf2QHWA
    034uBf2/Z6aMa2WJ14DG5fAR4LHbNpOjS7feahsxxeOgcU62mAjVCK5W0YLM
    6DWGsSUlVr/ySB0YPmj6Xuv1S7qYdj1kpXYNBbGd0ok5/+6ED7Sfj4xrWPo2
    3pv1Id6SnRUlboOfcu9Ql0dAZV4V9dD0tqq30YfXn6ZuM4vBmlF0B0qL0L/m
    V2HvJDCCAl4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEPWYwzV5xlQ6vZcC
    Re/+GUuAggIwF3dCasbawkwD2fKna8oiQhBDN3gOVLXFcDwZ9W5gJw+7FeNs
    /lSswhsPV3kEG/WPNahZ/vRxgzxiKRFqJ1jjivKoSMUsFkJETVkf1cvcaJJ0
    ijMsqwbac8Ydzu+18MS24db9/qvpAhZhVAW93I/q6OD5xbRJvj3Qp4Ty+JF3
    Ni+F+eZTjsQg+mFBMG4wPsYpnnUjCAGOI5S5qnPIAuFikrPdJUCWKAWeRByL
    TW/kOcAJuO7CiRNOVm9HkBveORlhu1m1L5xql5WUCu1JoU/fyABykAc+ibo1
    ixrmkqU60dWfk/jjzK82SWs1jXfwUIUadtlbe1o/gprrBl4TPu4k+tIwlTuf
    dOfFldsgR/Fm8D3b0cmxNc228tiDKqBNmbdDItEBvb+Ij7zeR2/RtoUswPLq
    3fKeikheeSFFUf6bQzO63hJ+COX6cHpx1Qx2ZQ+P/y0hq/8tT9DJUZAnXLiQ
    2GfEmNMaSoqKZsYDmLvMePFfLFgAv5Z2PZ7co9CU9qEYv7m9+NSP3+gtaLAi
    qYD4ZQGSecIwyRl4jpNU076bmae/0gmGd7KSqALNX9VZ84TdU5+JWg5kuCxO
    VYF3mMHUhpSzNQmlUGxjSgnOHe+lQpfnE0K6lKSFEwM9mbQhdV47MF5XuPiV
    Gdyh0BB78q4B13tYMkZPYz9pAao1B6UliX9NiuDXMcrPw7PkwbNX7+PKDAe5
    5iKXjVq0H6GxwEG5NdR48ffFICgQFipSbMTLE6s=]
oracle_build8::rac::ssh::oracle_prv_key: >
    ENC[PKCS7,MIILrQYJKoZIhvcNAQcDoIILnjCCC5oCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAUmxrT2VhZYIhWUviRG9XwdcwyV0B5SCJDxcv
    4dKEZMahKEVQnnJJy2RjcELv9FtcT1TqLGaoIjal7cKW3Rld/No/V4XRljzm
    ggOeKrDccjmNp7tPooxb5eowiNvZd7DdYBFQuHfQaDqoNstHLZcw1kVyZg80
    B9aGqLIbdIqV5B7xx0orqkRKIWGQzfn9RxU1BDqeVimUx2TsEAvCB2VKlDOU
    r9XUhukH17NLFv77bbND9opTenNFXXeGiPkf/FjnMUBVw1wI76hZWQHs7jZz
    9p5j0u3SFn5kjketuCasg9wACONSKlLXIGyvPdLIqunIoY/Sf7R10TczP8nw
    mGQVsTCCCm4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEAl9MwlD6gbu0ieG
    oc7bIACAggpAVAYtSwNpufUQhaIsFfkSBE2KiPYp2JJOegOk4ChGU/VHzZkR
    Ps8BVzwow28xh3SneKx+K22QyVnhEwOrTOA20T+DCjR5Pnj2MGu4HCO2dNQx
    iuWVl7flVPBYooHX/SWcZfugAGfVtd6m58YDqMJNRN0ni3q41tW26C/aS3kd
    evc3yC9Hsiq+5Dky3LZOfRIbxRvci63rxQDjJiulMPGVgGliBQzaA47FNnL+
    42PNfnSN8RWAitAw77w3/B4cIvR+BeqdZF3z/ik7rGNKLIdOIIuVOXDDEqe4
    ErxvzV1/3NNdLEXe5VkZrPKeMLsXar4Z2Qz16PaAxCx6MT9BHrHN40Xzpia6
    T8pP/MP4qsRUU1hFuvXAB8Xpc9ANDIQNta2F5jwvrao5W7pmE1QOhgdM2+AN
    p8AXVVczQzWRRxrNkqHqrqigpDkPIIPg+zlZdgCDcCO9M0p5IEgm3C9sv4Em
    tflITBjl0JsmJWm/erqCYj/EoPWspcCU+eM7nkyoiAukqx2EdEWBpu3jhHs0
    aZ8w6oAybcCIKoZKBP/bG3OG4fo0CH2IUIcF+r/l2cwvoUSiw3A/Z1+tnOXX
    47+0cHekwAp6w+7EHUfXYtEF27M1s9V3XR+DBCbmuJ2CdQmPVOSTxMhKPUPd
    lShwCQTZ2MhH+Kt4qbMaaw6KOl4rAkiyowRgp2+y10QBzCJXe7R/jBENGabZ
    wZwHBb32q+HsBbB2MdJPMN8DcnfArllLXZ2LYpVrUHjSz45UO2Vi3Ig5nB3V
    gx+e3NKYKJZUyoBW6jcj5+ngjZ+B2tZchWOqvFFfm1q0+ThH2y7iXMRhJCQ/
    kQeGRWVC5y17v0ts66FqHOJFNRz7bWrliJLKtgrtrvjXohynSrIBdyomkr/5
    4ptyhA0ByxDDZD/I0xXJ0LK7pzPDCOWcODkNpoAAQmEzfZgOgJJrSrFjWvIT
    IJNb7N+crJNk08LUjACsj5yyXKyVAjS+eWNwsyo5Fxd5uo3oaSsZ0lpmaStC
    HZduL6RRS41WJsHpOCPTtaujO68jNj4HLq12/hQi1YiEdrj40mGsEW/W95Bo
    aq7E1iRKE8pRWqXUNu6Z10UMmQ39jCIBRCKnWvktkzmXVBkutnNNToP923vh
    bGC7vUY8Fd8PlFd8V9T0fHUOhZelU3oP76JuDyjFumTzCRKhlwSE5ZvEb47m
    iVvWeqhJyIyZtAAA6nHSxJ+MGYmiAhCfzz8V65pr9b8XLSnjTDJdgKbslB3d
    yPM8NuESDPqPKOzHTcdh5aH2Jwkx14C7OJ41t/3UPRbNFGvCk+Wjyb2Ynjr3
    02TSEyciEqJzLGuTGMERHz3uGukGp7IlWjs1KmlCQ1WkjwNYfFbi2rFP+n66
    litDSHeNyyDn2995/hFmKpQmBYq4gyQfaihG6WJjqJyOUX4psMykSYuib4sq
    81+mcgo5Zgn0K40zOYUm4r62pdl/2RMNJitMPMMeyVINedgCHO6h7u2HuFUP
    snX7WZm5KFH6XLKNqVDwaishpI2qczokdIjoQ6h8FtQZF/ESyYHtG2Nc9S2Y
    1cPRvnkb5lnTrH7kC+gk0mm4I2lcBm9bpU6iiW1HPJWvszLNGEy+P6jyEM4f
    8hufvKg+03xazCn7lJd/cdRMpnFGU1/f9wP5lMEiQ3pXEZsUzMSohyCNe9jF
    AZbaR38EvjHlWjKSUkZn76UKt8mYzpD9n9BDsp2tTRmhkvRnYX5qU4YyJqu0
    r5aggOQdpGmbGPBUf3bT09+2EX4cQOXxtZeaUltk+0emZ6YBUrvtNd79jmYB
    hzt7UUv5/kRl2lHg5vIi0cS0XLtb2u15Y++HqS05M7u1/TCfTnuZpjs2DZk1
    2IOQIyxFMu8gQDyN2MLJxtp4UHijGgsaQmXHhp8pLhfmjc8QoH73jeDstrlT
    QTHX31qWwmNmztijCz7ZAMecmbD/nCVGHHpqOc4Vxc8/zkVgWQrtiSEzeR0u
    J3B8SVlhzBNKeZxazvu5gxCA3sn2mw0NwSUg/O95RB/O/2RFv2aulA6HStOh
    cdIhnsW3CA9qBcoLMRlC/yRpooGGUeoxgtarqLHNRBoPj8W+3SFckS+exPgc
    itf7YRhKo+LNhX7JeEtQWAQrWnyZ6lT0xHjhLI8P3uvmvs8TbA8l9NQSmoRX
    Qpv5P0Mauqv8PHo6vHo9f0nhfpQgB650ELdsVygJzEPJjOPT+iIyTnEUl3uS
    uC7c1SGU/C/7H0N69bBll3oZhLyar2BLuX508vVd7jQV2bO0Kg9xaT7MeEfo
    /9OGGAZ4/rjAA9BX7Btro+KebbHtBAll2F0iRSKxH3akDD6/k+rJpVHQNMjB
    c4HR5yi7QbXy2q+NooExfnb7ad882HZuiy4PN1Bc8yVYIRxsxhOM4UvWTEbW
    KCuxXCq0KQh8t1zMMGnLOYgxm35iqITUW753Fvpq4lz6xeQhYiyQfSsFcNgS
    +GlJeUCJq7dDTMFurUmGCCPBfWTsu4CdDSh/imUFKWeanVoBBT8Ptw2Q16Ao
    Ao8jp9Yw5xinxf/Q83DCyoHvM98S8XXMdW1ReK7xgCbl28KIGKbTZ6Qi+f/v
    LeCKSZ1XJrBOr5dCul6E1iGTQRpmD8B+52HXaYJer/cPATe7GRCOQ8gks2BM
    hCpyVjBR2PyQBmkgdDHmVHXNlYJ38Lrd7+12JudObVsKcqxhHGKxwIKK2LgY
    9GvyThUeZKduGIlTJrkvxtAAqJflqyXZ+da7bETbb1n7vA90wDZ4t6eDkHV3
    +QTb2/89GpuXomOXWHlut4vipcvI+H3XZz1VWmkxcS7aJHIPzYKduEaGoidV
    lRG+3Qw8pHjGffeAi/9jrjgJT+Mky+k17NO5v+sHhsIQySL8QR7gAUOstw7G
    XUKMoEj8gDA6zDKkjtZCuo3jG9CI4ft1rsF73IN2fu0m21TFtBlAGsDoZVkB
    H4Ft6T8g77W18h6+/o1aQ0UticakuVh13Xbkpefyy/b/1vJwugzOCzBp6OcG
    vSDckmOhBdQTXfz+aP5HNb4213s0TpJLqX/2DyGlUAehswdQDfzoz7gKOSYC
    Eb+Hx5O2pLkaPVvnLzMqPSb8/ipziRVR+NnMm0Dpfy8pdcek86xcJREfTKqt
    Sd1lUnj+VD/ocJv8r7mJa8YAyvsAbK8ADwmHH7YOX5yTM5EKPSkTGaVJlUe3
    wRRBT+mB8A956H73VssKTJInxhW+Y5YQ3tqUt9KyH7kGEtudj6W97Oy9ZoSc
    3ukHRWQ/hP6t8+DzWI9c2TPutiCqL9uFvwh8jagDbrZ2UurFmM/WSyfji8O3
    prFs2/0zx63hQ2GuPbArtD6WkRxD/i7b0TJ7RdzCWuPEwaSOzvxxMAi0o2FW
    1MnVFE5NZ1Vm8XbqGxKSAtk4zHWTwWFbOuMDMwo0lN8A5o6gg9P1waxTPrfC
    cfKQg/RyYLZ4U71wXbnqk+6Kbn+kLWP760R9mX3FG3ucOvJHO/w9gH/LSltZ
    dthyfMCgv89/wyVUUHx2BZIu/vPntto=]
oracle_build8::rac::ssh::oracle_auth_keys: >
    ENC[PKCS7,MIIFXQYJKoZIhvcNAQcDoIIFTjCCBUoCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAr6MPO1U/XJENo0v7MkPhPwurOV3np1IT2T82
    zpNTrRdygAlRw2eM/NYzsIoozu+vawdU0xlOxm5p0q1XeQtPDXIqNR04DfzV
    RXlzrJqUa6Cexot7Umkey0iZgLlh4FuGMWoCWdTguni3kaNyqRhSFBTMEkgZ
    fm9tUUy/DgXz8OMx8v7+1bUUuHcb12qXwEdt1XvamGz8xnn7KtDRl2KWQjrz
    RQJVf1erlZpSe3T9v58RrILth5jQXTKhCvTx5Mwp74LAPnejeK8zRFuWpbDq
    yCcn177bFOZkBd+K7Vtpc4VddxZxGWycf1yVN0I0xXmUCT/P+cE505raYvvJ
    6jpbozCCBB4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEBtoI2HTSMi+lm9U
    GQnRt+CAggPwCsWL1LaXVGqS6QzrxfDYfHPPtAkQpKIYfgZY8tb6O9V0e3/a
    lCUm4o4KGPFINLnw4dTyLtbQ7GVyBV1P+i6rkn/kK77VMKaEZBtOYp57U1PZ
    gl1O+EJFNKFLr/BO7X4yW07Y0bSlHgjoQIMZH5gji3fwXEaNVz8nSlR7kS7M
    6CFT9PA1k5HvI3TOG4qiGa8yUoGWPwbeBcWkTw/rMQ8sLAghkThYn138vLgz
    83dm5nqustxGb8IYAPEh/odwQlWgJcyQk7e8500P1qO+UktAHCsMfkcVooKE
    3amSRcnFXu+/+pxAf1b4aD9/DpYhu/L1NWJ1OZu+Q3lxpHZQYm+Hnraa3rmg
    7FVk64HJTPGhhJgenn3+0rXHunif9dI8umfUOnzdvmU6hwAY7aM+k0Orkm5P
    UBr6jcDNelIywyhILFmiPHRmwaqW+JKDrnFRSd4CgxGsRe2fI23RiAQlsEPf
    7wL0s/AISdWW+4trOPALEdAfYvIg8XBaiuL4URM27ix6xU0CTLinP8o1G+ye
    ffJTjllvahpSbRgs4l8I3Ivn9VdImaCeCE6amSPy3vS504yP0ZpQXOxPNT1y
    r+hwEhs2y33tk1yor8DrJ2IIxTO3kH/+PZ7VItKF8HUQMSQeztS64iFTkA7z
    OAT8xen73EFJSmchMJ37MnYNiKV05IM+Iuv05isQtk5BHDrBfIBOQSBsbQhE
    s5iY1NdW62DAWxrA8EvIURYEEkH5wV97fpJjCB0B7glcVnIxq0WlUiEfcTR/
    SJm0OJssB3+kSHfGq302Y/jX1rvPKkwnpKpBvsFLMEo4bHJrLgaUV8lhAlau
    0mecbhLUqod7WdTJHPuS2IO6Wpa/wgC2zBCsXFfHcYvR2O37AMPdcViobAGq
    OtDrsVL10548RE1ezZw/G8tmeHNkD5YrshqAAkUTBqKExoQMKkTKQMxG4/gV
    BIWcILGK3CWQi1E540bps7Uw39O+JpCdLynaygZ/7xK07dtNkOHbGR3P2d6V
    OBGNwQJh03ZzWsachngG4laULW2+/NX/peZkKilmm8ZznEOiV3aw0EBx5uqb
    W7CX88nUEPBb2BAFuVHubBTRcq2btI0GRLZGRfDtGD8/l5XaFeGfO0XnZTyl
    Ecq7gTqp0ltVTbu2yAP/Sic0yt5Vi908rXWo8aiVf3N8E/7u2B1TJM74feJ6
    2UyINYnrXvBTpZ7fzXF1TJROHYJ2JbhnQ254IN9bX0qscu6QVktT5YRsQLga
    5UO1kucQrj7uiihHG2SDMYWmoWjoNjJu+eGqYBjHanzP4HsNKtxhjDbmrwB3
    bdnIX9pR2rb3bTyLvdWjd5QbODwTcHiBmE7E]
