classes:
  - profiles_unix::gsc::oracle7::rac

postfix::enabled: 'true'
profiles_unix::gsc::base::auth::sssd_auth: 'true'


oracle_build7::kernel::vm_nr_hugepages: 3000

access_conf::access:
    - '+:root:LOCAL'
    - '+:(sa-local):LOCAL'
    - '+:(sa-remote):ALL'
    - '+:(gg-cgit-dba-admins):ALL'
    - '+:(gg-adm-gcdunix):ALL'
    - '+:grid:LOCAL cgeisdb1a.sherwin.com cgeisdb1a-prv.sherwin.com cgeisdb1b.sherwin.com cgeisdb1b-prv.sherwin.com cgeisdb1c.sherwin.com cgeisdb1c-prv.sherwin.com cgeisdb1d.sherwin.com cgeisdb1d-prv.sherwin.com'
    - '+:oracle:LOCAL cgeisdb1a.sherwin.com cgeisdb1a-prv.sherwin.com cgeisdb1b.sherwin.com cgeisdb1b-prv.sherwin.com cgeisdb1c.sherwin.com cgeisdb1c-prv.sherwin.com cgeisdb1d.sherwin.com cgeisdb1d-prv.sherwin.com'
    - "+:sa-qualys-linux:%{hiera('access_conf::qualys_ips')}"
    - "+:sa-cyberark-linux:%{hiera('access_conf::cyberark_ips')}"
    - '-:ALL:ALL'

    
oracle_build7::rac::ssh::grid_pub_key: >
    ENC[PKCS7,MIIDDQYJKoZIhvcNAQcDoIIC/jCCAvoCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAm0nKlKqBUJmKunKmObzjOE45zXU6p5EITKJc
    kZHLauyNOAJk8ZGC/L6FJ1Rc2WJdv4I3rjUyecRYm0/fzownd1RYmPNYYvXD
    02WgRHOFwXB+zDuQOTamvpQWGOZRt9OyZcYTXV+bw2c0aBDuM7XRzr3OvJ4V
    1Da3oDbZ2LugfMrBZIVIv7MFdkUZHmaSIdZsMRnr+wcDzT1yMGN8KWd1EC4R
    G6DCBce/tMZTHtlq/7NRrHCWMto/ngrkVok/buYE5YjXbLlgvoqVNlpfzZRW
    qz6hEcxD98O3sdxBrAQLXuSDrhLvq4AsPEwr/A3HbRYcIXbjBoRk19xClKr0
    QQlQLTCCAc4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEJGDvwC9qH9hJdTI
    xyHAyGWAggGggnnlJonA+vuwRvj4Ku5M87ahsiLP5BZARDDqaBd/2F7AC1/8
    xcJJUfAk2JehpLwi8+reyIokc4e9OFdE8VKjV5M/sI4jUjvM2MbqOn4p85bT
    qLe9AkTnYItctiKSSw5vd1ShPQpUrf3HfQNpVZBmZh77tTPMIObwDXpV4PkO
    bSCz3R5CcoSy/qzTmA/W+wN8cuyT99gdZgLjoMIAYdWryLd0vLGcx7km5T7i
    nSONH2TaAwW6THn/+YDskJNfrRwqRqiZl3RDOWlG9dvyDbQUNWm0PHMC1BsC
    G8ufXVw4zqeqFr55mEDO3CycWlZngJ5fQpk1SjO3pIrJiK2ToSKWhcGaFsBz
    IRu+o2Q59kcxjoLlidWQh1cSZwQqHXOVJ4cQxtMLt0u8YJJj/x67hFWDKvgj
    qRXHc1bpnc3VpBlkyoN6viMw9LuAiLKDL+/LZdVugnXM2SrvsGT8uwXouRlT
    mPU2aI/g7yg8imR/bp6StLP4+jnaTlBQuAc7UrYeRgWt1+0odnw4ivOB6vXH
    ij/nJp1lXV1F28LnSa1W7ecgxck=]
oracle_build7::rac::ssh::grid_prv_key: >
    ENC[PKCS7,MIIHvQYJKoZIhvcNAQcDoIIHrjCCB6oCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAwR5uyguFh6+KNC0vLuxY20R6Y/Gcp9MQGyEb
    Z+b+8Wv3FKAvHYP+Lc3ImoODfZ741uhardCprAIGvoXVib5itgI+IDgnNSnL
    b5Wic+TGx5KquG7V4jCaeEYuKnIGI5tuy8KUe1Q7DIPo9x5lumVfnm3YhaKu
    +JvlqzQ0bO0crCr/qXUIwcBvoGddqgQb8RSCKeRq05H5O8XrHfNh8OuUr4NT
    SK+Z8kg5uPjmm8wTzGFDZIcmkzwx0XpJbuqODxsmU/VagOKyjaG88SI+Ecs4
    DEzUeEO+3Pkp+gWfTZ4GvPBWPvwaHMRKksiy2HfUTKJfWMVxP9Cyi8qzIF1v
    OCqqNTCCBn4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEMzQgqujP0AWe80a
    5Y3psPCAggZQZHfFp0OsJTSc0Pb/dVxGEDvZvk/Xjmtmni221GzubfPIHNfr
    /2f8fvNG2xFR2Pq2oHRrGGTLJPZXlcNXa6YEHYmcA+enw6cZAE3SGUQzPoEi
    mSUbOMmnrUMYrw/LOmNTMIEBtra+alB5LY/uwtAhHv2Y7XQbehgKm8Is3hxw
    LUPr6miCEg3kzd5sSM5HifAd9MUFLB1o5OLiq7yrMx3dhcGe7dOQ257+m2yJ
    GBG1wa34g/K59AENJCwY5Wcj2RKexrUhWCxQob6kwGzSg32Qj6cETm+L9ohU
    eTjaUZqWBi91LjRkSQ/2W7K35TrReFlwqUUEYUaM6weI/TGWUIty104jwiFS
    7wZW7V2m0H3zcbrgxfsonitio1SgWFuvpy5RTvHLzDje1QqmZ04wWU16XpYD
    WJ/koOQ0bfreB0pY40XHrW5rjekbku4ux3r1NI71T2WWFbCsBiqaZ2N/iw+c
    olG7TpjIERe/fSh4sCxV57lOvY6HdXhnque2cbRNpQrzMFkL8fbmk9biYhNm
    iDSDxeRgWiAGPH/XhJwgdbbcIcTivyT+gG3LqDxq9YMB9R+oXSKgQKjD8842
    Xuo2GqvU9OIYTeQa9S5fXLG0xiUIJ+3O1sVt5BJfte+WuKDvRZD0aaKPtrKQ
    ijzOpf1VttcRCMnfuQ9iUZsXwP8cxizB9PWTfxl6dmQ32ZC2Iafck60qlvhY
    h25zX/nA4PpDkllCZ9F0CFT4v7fgwBDLfDQzSSlxkYyeRyk/ZvpxIXXL5pKQ
    0nZribKPNR3LD1tpQ/e2VS9rMM6q7fiZgVeEM9SM1yoTpjUDpUInnkbg6vUX
    IFSLA4D410am+ans0Nxnp0tFmKexF6TmNjsVGWkxTMQDZCUohOmvY+FL/Lmr
    06lOncHZ6ISRrBpDR4Tb8is2ec3mghSYmg2MelK4JAr9XXlypN1XvfIdJJ9R
    FAmRD6LylFZiej1OsuPTTtjurmtPKydIxsxK6//E4MeKTWo0yx6jf19EX+kT
    5gVDSkEa5wAv8rV2TvBb6a78eFue5vKQ5hzsp3dVAbFfGlQqgs4LBQcnaEW4
    yE7XXmU5kXLfeKp/CpB/qjdQn+hSb40P+kgi4y5FC7wVwZOFUx0doEDcJGKC
    +uV8yAdWlphX+KgMQ5BT7ZsIykuQgwvf/Uw6mRd1H8NYfv0BtZcISpB6llIk
    w7oMcxZTX6lNhkUo2mTQstj0WuS82Cf9D+0s3dyFRaTS3xuXDHGznJrPxipk
    AL5yfJakc3nRRKULRpF+cY/APLGPXJLaEKjnbsZ/3Z7uBT/+++tuHqwF8mOI
    g9y9CYMV1kog8knvZDouGLVWE1qNpC9xobBoWe0hHK4FiQFnajC/fv4Jo8ke
    LvXaGuJBOS/QviNLVk0aAJHJUF6qLXJ3Egbo2VRP0+nOYkQr6uid3HGpvGn8
    O5o2lCvjGSL7bhDdiOkWuh7CG2/3e96qaKEeaGW2i6xJePET/M2vdNkSoM1d
    Ez44TY1MoZXt6dQu+Pvogysrjfg3sGIAudbfRbE2Weln6AY+VflSqJFLgLXg
    DqkJEJDp0LfMqIDjFofhhB91LHtlY+FHzwPMCp46P3VmBGixwJXleMEbPBFO
    iHbPRNPkUe93GyZhKusgLA0vtVqdEbucFcwkUBdc1Au3w10qTjcwDO8EbyV5
    BvFvtDWRWM3nPyPzR42q4EqgEN+NSSXxNPpa8t9IzvbxyCqZGpmorNIg+xZE
    LsUr5YB+SRCmaOAJZ5TaOM1eklYHyCLQA3CNKeFmhekdx2xoafA0L9l/Jz2e
    MqSNxTx2onDtsRmHt0M0l5a/wTLs351U1xeU9um22KPZBPHbl09UOZrpWHM6
    8MwZt60asRnSpySpABAYMy7A6caCTdlGHgMbywKJ+RB1s35s0HGFADwki69X
    dqFqy0PVwZHwNchSPWtZwQgQUUERLHr2VcGGqeuqT9o9HakNGhBfXAj3ZflY
    7XvwULQYuPFXQvnJNEGQM/VAUebGWS+ilRFxapzuVrUpSlgTsTlc7IENjp6V
    0AM6BbzY1Q+TNPqeENQLeR43WUqjHRqhuOcKjoFg++cL2rpj6zg1s19nkXt4
    7ZqXikpKUZ5yzYM9JVKm8Xr3aALj7KmSa+tA+9nLJ+AbppMy0ie9yYbjvd9T
    BddKHF0=]
oracle_build7::rac::ssh::grid_auth_keys: >
    ENC[PKCS7,MIIC7QYJKoZIhvcNAQcDoIIC3jCCAtoCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEACdD2iNUEfbQfxGTLE98PSV7QyxAC6Opadw/X
    QiI2XTNURPqsVgbru+tsyZ7tb7CZibh5gVrN5Guvs5Uc0hOCgiFWkoJtpfwn
    sx3VnzBKxVNoUIdhovlLDqESvWR+IhTYkZ0j988ez6wg4EfSx531kcYDI9ri
    Msixm0V6I2A6U7B2KZwZNqkB1bizntq1kl9TuWaBrqh2wBpsTL4o9qpmiwUe
    RmI5La6tjqv8UEKLHZD3Hvu6zgKETvPbfgIdN9HpsEr71ZeDpYXWx1sjc/lx
    oB5HaZTjrWM2NsWV+rnnag86rji24+vmjLxSSrDUMEjyn+WwAxN149QZ9U4A
    DFfVijCCAa4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEDIxOaobB00KKSlR
    /ir8b2GAggGAI3eU/2t+5YDIcCpWjTRujXdc032aaOlGLYzPV/BGQ8r2VNA4
    fJadLhHxYkNzRXx/VBvzo/IqK9lZmq0AFtwzMJBzmOkf4MwMa8/KU+r5O3FE
    ikYP9wqV0Hw88A4np/uHywnku8MRTAxMorNNhB0I5AZ9cLtAXIGDOnVw7Asp
    uY/mMGz+/cCQrEguJTQUUfz1l5ZH5RStBa1AdXCmwvxeU//u8dJ1ZLwokFul
    QYiV/oe9eHm9lRofUI3+f2VHfMByK9SUSh08qYwpAhyXQ183mtdAikCMqUys
    fJdvaq++z1tLbvqI6jEFNQJyxp6jI3GVZeiKrxaHsuYMt65HkXphVD3CG6DZ
    UeKVVm7+cy1pK7l1F+de6DRhLnr7/8PPKDco+S9ywmtTMbC7ldiVrzMhfzpO
    IBWErcygKb2/2LYyRYHyZsoSytWCvpvkRhDS6kWgEPfPTHNGH7ajBRy2Aom3
    G6UEbMNXmde9pVwqy5ibdgqGmSUPyHfwQPfZ0JDWFBEh]
oracle_build7::rac::ssh::oracle_pub_key: >
    ENC[PKCS7,MIIDDQYJKoZIhvcNAQcDoIIC/jCCAvoCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEARGrFbeW/ykO50nhuRT1Byvd6Yjt/eGYKgHkk
    NEdTHQPIQ2vQuJN8gn0kCmoIIMKmPGyzKj5eMXHQscej0/vPaiCXXUNL/K9j
    rS3atHt7eU26LzB4HPKSfq9v6dSTEoUhMInVVFYyw/swFD8CtE5C7m1IMkGp
    8i3XdjDpcHRtRrN7p9ybGpkIHMjAaKCEcdS+JJF3L9TUsGmn+kRcaio1Mrgp
    HvuvTkBU4L9vjLUiBgzl6cq+pWM8TvQh6j3IFMjAys+E+nPCRvxnZUZm2wnd
    +fr2EQfhkQvLD4J3RSn0jPlQjcKUfM5T29TglnZ/m2rZyvzv6oYKib4ekYhl
    KR/TZjCCAc4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEKN9N2208NERIb34
    xgltYOCAggGgPlZU9W3nqbFm5e7eAoBptE/YI/phBw7Ln1OAYnhV71xmbDNG
    cZ04yCZGK7IJXsl636jOAqn9NB9eNIqYVZLQHd7d4fEg5E5ka6dlFACux46g
    onqvzcQmz+HdHQmmEyBHwn/ctEEvLTp3mS/tc195eGU59ACaKqlDLlgyKO6N
    TCDMJF1c2M7SfFOwYPWMHob+vdtVQVWEfLz+FKyTfni7pnF+nwug/chvPE/B
    falH82bMtyghimsipT663p6ZASsQ1XKbX1jCIBrYIFR+zK3+q05VOfYWLOTR
    iM4j1I9BdRicSCwlG3Mp/5tcwCUlGs79b343TlDE7VKtfnOXpYhwAu+zioeQ
    yY4ESlZKyPbaKWshboSA24Ca17Q1M3tSO38GwgXksoNKoK9xZgVhW7rm04sj
    B9137YeeGpyQB8+Xh6lwuQRCn5OoD+zZEEXpWHj3059ekiyK3hB3TUnteNRC
    Cnz1xKRusjozCxXZ+9FWcRADqUnN1k3NziOFV/piXKA0E1a8S1KxcJedCNSy
    Gsyf0MOtF/IVglMGRjeCzR+1UpM=]
oracle_build7::rac::ssh::oracle_prv_key: >
    ENC[PKCS7,MIIHzQYJKoZIhvcNAQcDoIIHvjCCB7oCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAUfd8vaX7Ul8S+2bUWDXlS+x7sqeEaHcFzCxn
    EAMBzzG1xu8usNFx5wMmBulrhD3IRmEC00pDLENLEZLNDWlAoYajM659HzAA
    Z3rEjeBKrjL1NXEfDlKaB9NgqEZg1r12h1bBMbfQMys0Y1eEkuPXdWRv7AiW
    gYBE3+RRWSiV9DuqBZqj2TsYOcaQU685rAFcWE2wZ782Wau3CMxuIFR8RXi6
    OH21XryY1x/phtq/AoYx1xSh0unJvpU5dSA1XuQlOEMY0Q9HEk59lY/SCUQ3
    zKQDYEdXNFr8UhznY9LlVzbfisWaCJgEJp1rWY6RzzF0sbtsfj9Qv6CJlek/
    JuojmTCCBo4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEOTXLiyDTkDxumhK
    PWnDVqOAggZg+ju9GybDDVRIKSU47z3Mif38BhAZd7LdrLVWUECZNtPoSMc+
    gRJlBhts4ZJWcoKOh1YQ/9ur9k+0ecURKZUPwzQO26Mf9zrMXj8N/F/u3NZx
    SFk4cZ7L0kAnqwSGHzRUVfThCZ2+Q2+4WX+LXnqksMVUNDXXKETvdI5BJf6Y
    eYj/X1GupHZvecW2Fzdt411V3Ai4ERP4Klzk2JFoBoKdRM3gyRh6Kgx8v+sT
    ijPZQzywv1K+8m3wCBR+r5kT8h0hYZpgPhC7nOx3CPf+TfJkWqimCe+Pbpwa
    11aPm1fJg9ecWO6FOylVzDhgKszK3O2dZnLp0dWMMvZVSjRFByvv8q5Da4Hq
    4IGGLTwAv+YhHiOWdRpHn3AYqx7yhWlZI1o1mi1gQ7osF0eu18aj9X+ZFVwe
    b3DN7yLJNLIgJ4kYBg69slISKOeHgf1kQlrnYC1obD5fRJg9igOXZT5dXr7t
    McNTw0f1/pE5zTUqTGX4fAGNmI2frEgi2FC3JoWolAQWWHwkMFRxSiBeDhr/
    tjZPU7SbYyyApcg8ARGWTX41RCL5aYiZedxzr1+Vie6clKwo8AtHCFY78nl/
    ta928kPxxMYGT5XQAGqLnIGQIfrg0ZnILKKI1/p0E0TZ9O1EmqYLKvXmYAKZ
    dWQsvqL/MyyC2MKYCiRn0BLHRo27qjg1CbMNE5GpzpFJ7kRQv8m08UKwB6Ff
    Mv25XlpBO+ax2LJ/KSKtjoiqEX1FJGfEwUzZBoMwvUONlKNrd6ZRs1YiHouZ
    XsetgWAhmWO5fsL9uN6ohG3auosm5rlctojji8jhlnrwSNZK+k5ZuHlOjTJy
    8vLTUA9rhGVft+H/jwiSgTM3qVtNoxwvK8L0eVdhHvWj0ONI46dMc2XJ2DaU
    Vo2LBE9pZHWFvku52UcFoxb2cNhYsz6QQunNsrAXArLV6QfWBlYGaz84oY2R
    gwR49H95b3mcxXefJbU4fxV2uWIytglMk+WHJ6+BMzKt/wu+DAfuMd/EG8yd
    2dW5AGoOCH6gw2GuT47K94M5jC1fbseT1rr7218++yeQYYOCn+kSIWJYAOFp
    Myf4/uYJ0jA1A2nS8/dHI/EahnzW+jk+LWExjWYUkCQRmD5tSLfC7sZ6HwjG
    nApDiLHayl6LHdHMOwpKkV56UQea7N+gJlIVVRaP5tYPyMmY5tW2k3MWzxn7
    RrcOCNbqUcH5P9/xNcscuUxN6JQMcPEqVixgc1D1DRQdeGE0pFq2/Gvvufey
    d5Nscb26+/NeaqocXNRf7jWEauDet5s9Yy3flet3m/tBZpRYtpFw0dkZWUZq
    Lqij97KW4hcaKNGQcSRQk+FjUpGyI52Ui+iptm9FhVe8ABeNarlBUJN+H5T3
    1A+K+QZBL+4scsznSKpwUaglViqgdh3MnpGq97d59jW1WXNGj05765ZrOFYB
    8vm3bThqQxWr4jBsK46TrS1IzTE0CVWoeF0nmL9++ehvMpFDlFUoQH1dfkwh
    oiOvMzrFf+GbQzP5UGV+qyYBB6RBa0Df2yldXoqBjXBpAE8Og0ANSdJpflgw
    sqTzMHxLp9PWxOjo7h9l3oJQegeVN1dwB7JcW0Jz53G1fFqxmUYcZxtgtTwl
    uZDNAEeMlxzcSW5Ydxwe/bO0cKk/LXrxpUtiKS0FYxBkcgTI54ul73Su7idf
    8HnGbgxzVY04Am6EfK1XBCbDbPOVHBWMmXbdMSh1/XSxHxJNYiDi5Tfl2XVY
    TrCI8DEAOy4ZfVeXKStxmz+wFHuGBxOwiVXZRQ98oQMhrB2EPIgBtl2/x8pS
    25BqYX/vOdSOiZiDaDTVsmWKvU1qz53/xGzxC+J5AQZJtxhO5/0vS+PNo+0A
    qla/9t1Fx414aL1PJiQw6nWByL6MTkpzdF5wazSPASH2leSiSuvYr5J6Ypb3
    nSkVWfNPNa/uQggB6MXZEN89HmXwR8b3CCKxyQKri4+9C/8KxVrTJ0PvbM8a
    CqEUnY6OZul94tnQRJQ3mB1Oc9FDIXYYn8XRnUMLCNTGlVejsuuR0n2+tXto
    Esxl2v91gdztuF4mBLrK6S2GonOFUo4Vp51vweNIh9akaNj9vsmoANVC7lvV
    G+N+LXFNOc14qZUBLr49KD7vOQ8xmP9UElKBU00B2FqaAOSQ0bAhuAr8wM23
    RJfaVdQsFfthrWe2iOCJNJr3GlFx]
oracle_build7::rac::ssh::oracle_auth_keys: >
    ENC[PKCS7,MIIEfQYJKoZIhvcNAQcDoIIEbjCCBGoCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEANZLK8nIrFXk/wN3igLe1iYfJz61Y76Ke7r9j
    K3WUi4ZUlfdwM37KCGUs5aQEmLhSwV0QQl98b156V/RsU6Su7++pTz3BuR+f
    Uud0/D5Heu2f3xOz6QrwKgUGmNPWRH6ZjP/EIM9BY0a35A3sywwg8jB0b+mB
    B+UGmWY9ZqNoNhDW6e3lkPMPA5qc10bemtJ7VlHbmfZTaZDDvBUA0tMcn2FH
    Cr5nVdqeVQ91APsAAGm5ZaYlPCwa8oyxkm14J9JYNjWWOoCYDgPjHhcfXner
    lZus3tU451UrhYDkihmJfIoLalEyN+CtscEPrvwc5NpMRlDyo94176zlJ12A
    d6dTeTCCAz4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEDmIWwZHShzTkwEn
    9nejaS+AggMQyKlUQQIaceIodN5Ox6cLmx6AC3y3Ao3Iw5YuShs/lkjlZAqk
    /q8drA/PjFPgTWGb0lPlu9FfzCJspYn1YxGsNKDtN19D/tgEke3XSFaUMC2/
    dLeFpNk0yyb4jf4qUfy/gydXAQ2xyFv+VxYTWKl3se0ST3o0xwOhOrfAK8D6
    nKc3JqQVv2tw6PCBh6DaVwrA6XfuovDm+u/bK7RLL6S4Ur2xffz8ZYaReFHO
    ZLGTPX/G0vgdk3Av8H9uBUK8tDbYx+jcv+ljeKHFmB5eDYda/3JTPZF2Tm70
    1huc+b4vEvL8ZEgvmpwqeirVlDLA3aLvMJ97w7VIo56BpHjwhVoT/lfD2TUD
    BH029SHy/pzGclo9hCe18PKht6RdcteEn68t3UIN6FeRWRbdJiayF4CxYsm+
    2D9fnkTujjIfJR4OedHKQ5J3HSMmtpWTWdQCZhlEZQIsnaevtOzGWmYdChaT
    rXPn60YCCj94cCtbNdEnYfmp1OQ9CUNBQNKboDbHICU16jKNJRoZmy8L9pyL
    YdK/lkm8YdyO/whyWvorRjf8ymjyv1kxjlf08KfLsHYOQ6ErdGw/R/0A5/RB
    iQfrbVwyK/yqRCCyZK2l+GuPvr6+S0bnm3UEwDmfpojyCImM1Xhq1hn31d3/
    HQlvOLu7eCRxebqQdtTBu1BD2n8tAxzPH8UGGnapyPgLHqKnZUlaWwkeNuBi
    DGzfmZChEvumdqy70TI+0/Lb4mA954J8nyMEnn8xksBfbN9TrBa5UqkgSvNW
    HKhCJkz1bNjqUOPBE+aGOVSCdGl9tPmDO4INwOLz8zIDTFb8OntSeIqks7fg
    WFm/o/ghJqfqyDDULLCcOdMEh81GsC7eNDt9Ds4U0ePGZtEdgCRmR7GV3BTd
    M01b9mhFgHMI+ctUhDrFBUs3VXAmRyMyrfMfnOQ3GgzgWGea7eHn0T/iSAJv
    C5v9JC3qIkc/LjSSUkuv43ECEPTnYc6gOB0SpfjDMd8SH16lD4jNfjL2PhK/
    wIb/eXFpwt4c9Rrt66pSBdybvRrCFMHAHEhWKQ==]
