classes:
  - profiles_unix::gsc::oracle7::rac

postfix::enabled: 'true'
profiles_unix::gsc::base::auth::sssd_auth: 'true'


oracle_build7::kernel::vm_nr_hugepages: 3000

access_conf::access:
    - '+:root:LOCAL'
    - '+:(sa-local):LOCAL'
    - '+:(sa-remote):ALL'
    - '+:(gg-cgit-dba-admins):ALL'
    - '+:(gg-adm-gcdunix):ALL'
    - '+:grid:LOCAL cgeisdb1a.sherwin.com cgeisdb1a-prv.sherwin.com cgeisdb1b.sherwin.com cgeisdb1b-prv.sherwin.com cgeisdb1c.sherwin.com cgeisdb1c-prv.sherwin.com cgeisdb1d.sherwin.com cgeisdb1d-prv.sherwin.com'
    - '+:oracle:LOCAL cgeisdb1a.sherwin.com cgeisdb1a-prv.sherwin.com cgeisdb1b.sherwin.com cgeisdb1b-prv.sherwin.com cgeisdb1c.sherwin.com cgeisdb1c-prv.sherwin.com cgeisdb1d.sherwin.com cgeisdb1d-prv.sherwin.com'
    - "+:sa-qualys-linux:%{hiera('access_conf::qualys_ips')}"
    - "+:sa-cyberark-linux:%{hiera('access_conf::cyberark_ips')}"
    - '-:ALL:ALL'

oracle_build7::rac::ssh::grid_pub_key: >
    ENC[PKCS7,MIIDDQYJKoZIhvcNAQcDoIIC/jCCAvoCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAUV9UwjZlPaAGPle65LqQGBiYTs1oI3daotiZ
    ZR8p0m1W3BVs9xsz8qLaJ20vuE1Jo4F7AUP3jsV25NpIWkxUDcBrKnwrMiea
    qGTkZ2ZWs/1duodDuyMmKF2CwWU/gXlkn630UKxzrXaxjOwLMIo99vvWKUqg
    6SqS8PdcOHlOrWvKnK64M+hPH1jfPDHptQ250/GDPEqxyouTuI54MXgD5OD8
    j136fnpXWFkFhhnBB/Tv+JRRwLgZjwX2kADkO7V5xujS+OXkfJFwepS6O6Fc
    BizEV6G0n45oWH6YJBHyK6ysZZn1K5pPnazZheNxvs4F6ZNbpnBI5FGq2whs
    oNJjHzCCAc4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEA8gN3CGDuHxMuoK
    C8TZE/WAggGg715/1N9hC2yjn5YFXMPG5LmF5wZqFkjH/l7ZEuLu/CuQETP5
    2/Kh+GlGkRaO6y/3r3Gr1bzAV4HpiygdxZCT+axVAvSWaP7KFLt/GOR2rg4A
    J3l9im9PEWDcUylrYzoH27cC2LQFuAupwjapkyvcpSSI1uC9rKeE4Sm45fTz
    qhWlDimeJK2DMeAJqgCtax+b2SGtOQYSPrrww/zjHj+pyu4D5v4yQNIEfGst
    +w75p9r0d85MSOtxtwKezKd140y01Nz78GD1F3Za/32NxXsgXxFe6CoMmduG
    GbYr7LiS6pH06FuWLQWj7zcXdGl4kb8knHfgORbJ353Ji0OaDuvuMLAcUhRJ
    0Y0iNo+urd9zXZ4UR1KVwz/d7IrMHJJ5zXJru562AjtnIfAE2C+tFqhAQStp
    pIRSkJvkyntISiNdFf8TZSLbo9lPfQ78iMxlnguU6VuMJfVugINUmmHhA8Ip
    jWmOOGME/agLF9ztlbMYMqZqhK33s79pyvVxrxVimqz0kgxJtCdx/dRU0w2y
    nsavh9lOvhLzxiME5b0kUMySt30=]
oracle_build7::rac::ssh::grid_prv_key: >
    ENC[PKCS7,MIIIDQYJKoZIhvcNAQcDoIIH/jCCB/oCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAaRcrB0jYmLgIKXs5XlvqBgyXv6f0r7xPyM18
    120+R1fny7oecQpdZnAPqsP6hYAGfGYGo1Gnnk4X7XSIsYIR4VzqvEG8pR54
    QBZKRXZXvCL1KXToaVabqni5bvC1uwqIohIhe8sGjM/afoXw+qnaqt1cgEfx
    wFWE9iHIiDTskhLbhqMR1Ey2ZKZew0aLec2C0fE0sgwSsWoE3OQMVe7ymoHS
    k/McuS0p5KPiz+n/aoNRQjUwlxc2eXLTOdHeV0I49ZMcfvtu/Pxv9m2MWhb8
    L+ZMCXkRdZo/tXUotMB0ah01vF7Vq+8QNKvXNCshkMWd9ih43I3p7MWLmNVM
    9yVxijCCBs4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEDh7lCzUOcbZnjA9
    eijK64+Aggag7jilq8geYMsVYTdNov1qNWkZYJP0REvyXJgTmrIUjXCc/Yhg
    MtHF1LS0XYph2zX4n31xESWBHVHiPb157Q72AAq1KiTdJ/AaOV6QenO6gy1a
    VTSdVURyep4okA/zymPWcR/px2SN5R6wQzaF2IzQmL/pGpDtFfnrYjWCeuqg
    0GKLz0B7jtlqHore8vygBVS4BNZtPHAje8GlVYpWZp2t/Uy7/kast7FixACn
    hqP45P+mbSTeLZOteMDUszdWjUPo+JTXRPiFbILI8FXRtBg6l97ocHmZGolI
    gwhC3TuDhcwXJjZmwyJgghIKCpk2C5nqrq2mn9vwdAfKGqZmYlzFONpEqT7K
    Q1+TYXsJJT7qtowLwqzARlfH/DRGtoHKEbVTSmArDW3KrSgIspUs/4xrX9fz
    ViTkPsuM7VLywnfnPAMyokibTYEpt5h4pwqwUpbojlInZ9cV5Y7HCFK2QOsJ
    r8/iCy74Nvgg5UrHeSWhpsuLNZu2LR7TedZduUf6fUZ7lEpww3KGvv/dU7Qp
    WRDGu8txrP7QoWoLk+FiEY6XcktuYRr7NGkeXvIVcBe8PH4oby90htjT/344
    9qyUheaLar/CnaCK3SXgo1D90KEOAt65fcKXDNnNxS7pXR2md7jg+CwC+xYY
    X5YofLxkj532uwsZ1gY1P14aPAqHIleODnLFrD7jPdCxwqGbA8JbAJI42T5p
    u4xpSebYFNDXWAZuZjLT7Dxl8CZc4ioek0AStpwr4Rj7pFnuAhVp7G6PcIgK
    hN7O0JJRYvjmdK45vi0UAcKCEDhH5tL3WaIApV3klo5Sia2iA4vBhpST1f8I
    Er86NXtOvQxFxCdxrYu/hZg37/E2QVMPqx3L6TuhM6AK6aKmkPvDjcrOplkF
    PCmHx4+yBTI1oUQP/F59WYes4vzQRqtgB7Zwi1kSx3QADfQt25wKkln0cuT/
    iBNIlhcJHLwb3Zf6uWJavd5Yui6mVfVPAFy4Ayeo5rPoNlLw9NvO060B0SCK
    PfUcSCBId2zO5XMmoI4RjVB99Jpkeyi7f7zR8xvkUASXEF+IF9zEmV/Ms8gA
    J57ZMDoo/ygUn9cWwv8xI4saEq4jzOb9iDTTeVe4QAVEYKtZlHZgWoWB/MA1
    EgFPEmrbjPsDUdxghkqXOOBnwPeLk9gui+mi+umhlzBpa3pHSMS++SR5E4Qi
    4Derdjyh9u9sYIiC22xC26w45QiFelndExPNDNUOTbRteUERgcJEcYveK8PF
    lGTlf3/qTDsDQ+AHk5fuIP/dCQPf1iTvoWmBPYIvFkxNDmZLSbyDDJlwX8VW
    7D6mNUnIn9EI5JFpE+n27E27X+Hg+Cq4dpnOekoL9ioLwnagP7bcPIk28W7Z
    LoFCeyqIomKotbXaW2eDgjbc1cjV5kfGHBJzMShNjv1fF4c38Am1oDUu9gsA
    RRY0uRK66ov1qJVivELBEe/Q4aD81rkah29C7ozCJN4CS1Qdf3K0xNJdtRNJ
    IBCx/858TVl0RvgIElF274O//gzwjJUpmBlYNdVR9545zsoOIV3B0YAvDmiI
    03azk9PVzpkOlqcXWrwgM1J7TJkoICW/+T8dG4XdfsAxO77Q41T69/b3tbZr
    stZ7TDhX47fEeX6gWf2gQWq3KB19ot5hhkRtfRIYF8NvnqweDa0M9irti8F0
    dSlpJsH45uSsyyG2yM+mTbw5PCHyzIvLf5/j3LS+B4TIi6ujNAp6YGJpLVbz
    E1/Dii9Xf5kBUTTxZyMKOo9zCS+l5VBYJdhB5LsHQTpQ0Ng0UdN+GOoAa/yj
    YImmEfqlnBjnHRuWh2bIyIJfkE9P7LTwERTZGdBF4PlQRXBT70G23R0uh29p
    IIRSVwIMzdKZzqp3XYtuapDrB+zSU+eaKsj++nb/RSKj/QkR03O2xshXgLgs
    AZnIyfvE0Sa1wjhpsScidie32i1HrI/7Ub1CY/m3nY38gokuRHjp54xZCHP/
    At/D2S7bOXQ4tou3lrStVH+EGkTxTggO55Yuyos6plA/3uZ7ei1ESa3+GbcM
    +PzcSrBUlmQkikx/Fpaohsh+EI5g9gYQ4jAJWdq3KmswZ8tWtdkWVCM/TB6o
    OuSd8H88EpY8OFlbCO9dZiXwF5nLem69uiZMIjchM151ptsAkJenxcFg9KAk
    oDZIHsIR4fFELjKNBUoxVv+jI/KrQ5kxvOmbJ/XssWJURN/YPvdk3/pPHMfa
    tauKfSzOBHLjwshxztap1+ugB0LLyM6CkRoq7hNayK9owA8Z9IQT2A==]
oracle_build7::rac::ssh::grid_auth_keys: >
    ENC[PKCS7,MIIDDQYJKoZIhvcNAQcDoIIC/jCCAvoCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAUIyd89lygBC4dwxSGtGNWPibZ+kWQwzXRVWN
    7yHi25+Lm3exEdEE22hFE41EKa1H2Qb2BWNLq2uAdKOaKStvh6bxKEH3x2ny
    ju3C3FNENVaGh1FCRVc79f4BtJDyhHyFkG6Ka1wQN7cQW4QslH1Gpd3PumEQ
    CthM4J7/v8QN11lCArOs70O08y3/1fumtBpMdqu9mAHAQvOQBobttNq0jXQd
    /tVGgDiLwtrmLhsBZx/vW6skYLRev9C6ae0gDQUR3BVOlo7fhhZpCRN4O/V6
    RlGVoJbpiq7EUxotF7JapFcoSDQQ7oAc6vPNbDVP31SyM51pcDyulBHrkcoH
    TVKFkzCCAc4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEELYWp7iypOuAJbXB
    ImUj0u2AggGgxQoRPD5dlcF0CdeYYgEHrImCg3OGSIrGx7QtHYHtCJxFc2CJ
    FdwavTCsH3mN3EmI006gIW19xOrblT8+nbbttNEi66sXO5CxVTatBtEVJGsB
    MJaOBJCr7jRM/T0o0OCAJBouqCNNtsk7g7UErYFrmb9Uqb8wfQsuM5sUw9S0
    esqb34ExCycD/0Fu01McdebJjV8Hb6IzhvlHpHdTCBugjoN+8OiEUZEqCQ9i
    w6lwBkGFrZbP2lIiqa7KbF0s61zEmulQgHI9+7tssj+v0uZjfF7OA+D/G1HP
    sUE+S//7UYRHB1DdR9KMJyvTvxW4dtRkBE+lyPQqITkxoUKxkFVyTHFZeuYG
    MV0k6Z+h9nZh1uZaTbu6ed50cag3On3QaIp5b0NFspsLiwzRw2rO/vYX/fCP
    h4O2mnqGCYX8jEj3MkKcV8JIoBNpMLwM56tjxQaHyKatRKHwRZfDQ3GsmRBE
    /azvPlB74MeAu+Y7iyprf73EwkcoaV6QFERi9ubV8vYXxvxsOMYBX2kqhltV
    RdUeIj2+Lv1z/JgSDdLgAkRtiws=]
oracle_build7::rac::ssh::oracle_pub_key: >
    ENC[PKCS7,MIIDDQYJKoZIhvcNAQcDoIIC/jCCAvoCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAE5ENEQDUfHluAuPQCDD6rwmLA7CLQgOWx+5G
    Qs+0jv0RcHeesZK2dqgNiQ9NQH3sNcJK8V74TuyaDnVxyuBun7TNqIjglNYY
    CPK9qDDnySmmNIISQ/b95lnkO2+xgvEbn28TOaCKoFQLxfJc1jsn9S1AYx0C
    eoeovcR2VEYfResRN9zeJbyT84QGW82Wd+NfAAp5nuChiulzA9/oiXJgYmto
    2sMOrE9zUCY0eqEm+XNcZTUYtbwDPhuGo2tYQ0G+u2nsSI5iJoFe998kcjun
    Gh2fdUZSdFUmHgQX6XKNtj2rmy7Ocd6qFO9jI0MNYCmpN14+OKaxtTWBwxZc
    cRJFQzCCAc4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEAty0JtaJO12UT1y
    ZxfeTjWAggGgvN80rmsudEO+7RrBjsMnBgy1APsa1x8XVGfp9LDMGZlcFXe1
    O4LaJKluk3zirQ9KFu2M4bZPWF/9L5ELis+OAlOSSIX4LIBXmPpnzBB3UTY6
    wTfJFxejKDDXfAaFdmE9pW4uVYAvq/QWjhcZ9ekB60+YPOsZ5tRDdUDbf/0Q
    R2A0jeIU29XcfpavS6fuP1g/M+kj75RSKioGGsdzUGKmXcugbelLswJHIAJ0
    KTLwKbMQBgfo0TphE/aIhcHK0hsi/OVzVVIlmTOWPM/EnwaQl5dTmr2TTpqE
    TdMaCVuIbPa1J/t+EiTtCslJpMvAk0UZZHaptZqWUTNz20KTN7Gj3ZjIIGMq
    krLeEWVafHw5//5ajRb+mvZDShOJJ1E9DOBNe6BFvTCiOjDKYwSIojZFbQ45
    HdGH3G6lacmGyfvWP5ZLNhzKeVQwMM+g3X7hqs84CCz98HtxYx61qLwZEcuU
    jzQhYPgbzZrSLhL28utta7u/o18nDddS5rkirt2DU4iDHGowBV47FUULn7Op
    TfvrZdfsVICqDdoZb9cWa87GQ3s=]
oracle_build7::rac::ssh::oracle_prv_key: >    
    ENC[PKCS7,MIIH/QYJKoZIhvcNAQcDoIIH7jCCB+oCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAHx3eh4vkFEBCQQu4xMA/ROciazAPIGHahoCx
    Ii4qA7nJ8L5XPkU1vG3MQ3sub2VSDtVr0RXWAbePNmAm3AqbRFL4A9OWIsu9
    i5Y7ZjIG0QcqAtR5WgxQK9qGLle/ItPq+BECKgVH5BhPPmghtOxBGpjpu0oo
    R2DXQMjlqXnmV63NifU0PjQMmG0hbRjHMluFp4eMoEnaa3WGaI1GLu9fvBEH
    QRANEFcqBQaL3d3CVqaD0Ta2AwYO8JegzqXo8BylcS3sugj9K+GASKufGTtp
    6XOZegeAvPlwVUhboeOkrf+du/d6LnuaWXdrQcEnnsmRScf8KiWREOqx/CCB
    nFNqhzCCBr4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEDHVcejzOO3X+L93
    l3X6K5uAggaQ8mOWOTjXhY7QO7JaH6eOfn4jTXgDIOg0GWAwo19IRqxJWp1P
    61O0SQQZihBc5nRW92P0RStwCJ+Tw+8slxHX34eY6rDHJka0kQ8O8zwG2XeE
    RaXSIcMWQoa1ZFKd1SgavATO9jLXGrMy0ev+kV8fGQHmC++w2XkiNdCe7JHc
    T4B02uJBCzpUQbaBde5r/meIiZS9Uy5KUVmG+YcND4fCW3Thzi10vVGaoTzL
    wgMxfkzqEtmxjaFUR1IRajHKq1r0mmoc0IBnjBOMdgxrrItRmHRSEGye7/lz
    lPY3Hb9y+kSA78atPnSpTis8NcwWA8k4Lqp4e3/22egNpjfGHYM/9lwbdnvo
    RC8QaR1PZ9swBjugqxQsr3qISdAUV9ra/9lm8b93HqpfKgDE7gGExTuvlWfX
    +ZtLIlhu5wEYTssfd+S97v6Vv5Bi8dsOwA2MXczmq5+BlpjuD6kh37pziedn
    Kjlx0RxKga5a1jvVyY5ml3F/sVMgpaDrtKjAz5btxtV/Rrx0/R4VUyGuMln+
    am7WQkkMwB6dTYIGlcuO9WME/p0qGkV2KiVOxFPM62wIVem/yLXxWePxg4Yy
    X9nyfCG7z82aexs/6FaVs0M1jcSrjpdtQRtyz0ki8Rz1DLiroEVaZvdOndoX
    rF6CGIlR/9FrbMPYuA2hOoiZn8S62MU5ctVIxaARkGXZyBl4ow7dEpPZIk37
    9FuGm+oJL56rD9LsPQtNknK5SYQiKo8cELakKpbvIY0bW6RaANb2FAxehOzB
    S5WCJBHkOUpKFZqxD/ileeHUYZs/Tk32FoihJzDVkiKIwGeAi48ecX5Cqj+z
    oqiZ5YaheNxAZyfn++x18rrHsWMiwmWMB5H3lrmGto07UirP2g5AchSYwZAK
    J0L3l04sjxWaptZWzaIHyTceT/JyKJkfyPtcgs5FNni2tRWAkeRxApcKI9SQ
    H9WaQvYPcl8DA//2N2ASx9q+IbxAMhhzTAazUyPgR20ZT4R/zDq6IvoXeQ4r
    kYa+CKiJnMnMvUS9y+wF4PlChqZ7l98K6/2SGJ7Oo7BQkSc7wbA76oPxFiHR
    e49RRPsl6Qqdwy1A1flcAFBhSeLKpSt6wL9zip/3CZr4kpBtLNRomktVf81g
    GpvLnF3JU9mQ4n2NhwBNXJZ7Y55WdSo0O7PJkKMzlB6EuLLwsQ0HuQ//v6Rv
    a0M02SJuG1e245Qq8okNR10zvmYX+OHjD7pJueFU24a3xQEoNeDu7ldx5wEo
    741ydvyogPPhVXJ3AX2lfjmXw1l/6M2BVbcVALl94pvwlg62tmdK5n5ITIdW
    arfseRtwxhzw7f1lBTMyEfRv8LIt2Im0T/osn/rEIezNHPFfA9Uh9w0j+zrd
    9e6i/DGSLDmE/Qf11iqtS/Nzo8OUhpglyHDptyIOLtkDJh2r6M2EYkfQifph
    yLvf8LrfQNsBqqNR+OEqe3STkm1Osl44ULf8UKrVk8gxoIiwfH+lKtRpyLLx
    uICxiVNFv5G4FBR2M7gxYXqzJFoHwwFilsGiIF0f3LacpI/prFtypi11x3dP
    hPwGEayBnerVwSZzTmMLvry1B9P6yX0fimqQDbY4uR5nKwYPZWSU9b6QOO9J
    u/M+usXMqTiRyqr4Dpx9G+KjBcRS7nHz5kKRo55cUEqZxwdcKBOxhMG5yWKI
    jIatjgicypj3OScfAY8ZwOaNBivO14d0plVKA9RhQkiyzpxxX+ZwiHSYNfUK
    tDGMhYf8gPUPr48E3CK2SJPesZTQ4yRntA0Sdv93yqFEbkDxu13P5MS6rwE8
    QJhTJZbHILbu03omx8W+3QIWW/Hh3b8ryZYS+zBwx3V2+iqHOJPmvoV0QGC4
    BL2YoHm4BDyzfkiPu0NG2PQ2Y99TjsdEytFIkUKWx3CbpPWXQzMyCCxqhpTw
    KrgIbKsYmDOLbxtituoIdwtL1aMhbm5UBBIgJIQktAg6OPv3cHvMsnRIG42v
    jbUvQl8wap9jSVtCi3ltB+nPcuOS3/bXH7hDhOgOsPeDcL3TxOpiboOpN8UN
    jFJkmi10C7J5gv6zhJQYSLPzj4adpauGzU86WFt9x/DnP24dQb8WPqqczi/B
    IytA7BQA9m4uhfRXoxgtmuorar5q5EhMBz39kvIfd4W4CMnL+EmS8KR8bqWs
    mCQF+e+x5TSsSJZdoi3ayRrXRzMe6IyAr2sOUSa04KSNcH9BC5oybdS555rW
    XkHeIHVKtRN3dznmM21ShPBgp0tMvKli]
oracle_build7::rac::ssh::oracle_auth_keys: >    
    ENC[PKCS7,MIIErQYJKoZIhvcNAQcDoIIEnjCCBJoCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEANaQ1wDxUuPe2wW6pL96PuqO8wK7dgdu26XA7
    aSGcfW+vq/j2H2r3KtZLUrYqgeHMX8+E93+3s+rAeHlaTyXd+1wknX2t+lRL
    2Kgxq5u52CYGR1MyqkNIQpXY6UB4JIDhM7ll2xerSit57iplk/AkOgAiGFll
    CXnY8KV+HOx+rlPk1VA4ZNO6BWwSHVLpU22meI3x+ffDfs1Qj6mg3YM6+ypm
    2Icz0lZFspBdp58+3jJSsTwndq2iwWnZuhDKkzhEGz5LXYCTYHryiiPVMYUJ
    aEr1ibsRiket+41Ok+MzXG0hkwoUpNDyF0uBE53aGmXMyFDyDdsgxguEk4vq
    BRRbbzCCA24GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEG7HF0A43KwQxCK5
    Ml4TIZCAggNAkGI4xtRAit+htm/TGenA/o5QHDNid1q3yGLN6x8d4hruATyd
    UTtnymANL4d947KT+qCzDgAdCe9JFDukrGPi5ymbQXWt1Wz3sGCg4WMv8Xq7
    l8cKdM8svOdKawvQHaaJf1KXUQ3Wk3rnZ/SJYhqBhUmhYoQLDPPFF9tOWKj1
    nglTWzFbcwVXo5lIvyvuZHb34CT5jUrTddmhvS2DqEx2JffzNSeEwsT95G3f
    ZSJajJU9fd2Kvaqd6nOxbvKBEhdBLp942c8aidhg4tK5t8d52kJTOD312bqU
    iJh3Ji6tP7WOI8BUxr3wrzUR60OCC3x84Sk0SUL7QPAIKwUZyF+BuVhedA28
    n6qy0JhJOci+Ic+2H4leiB/eIngtxvM3lKMuA70pSFfNEJMCfXJ0UMbtFUup
    QZwv/siDBc7mDkmfyd2/u8YzWQZJeNk6GmuCNDWKvKRCzkmZ/0oE8GzxvWoT
    f/7IncgBKOuClfPhTUDGZ9h+iRTVnEEJZoT/7ucCPfR7V3tSlib6XPhXeIJz
    JPyEFqsEsqA4q5sp7g7wwxwYzrBPXDquW4PHOXLnNXe5lVgy/Epq6PyZfM91
    U5o056VB32LKdohXuCGOOfDKv/O21ENTerYRrrV4sFsaTDCMQms9WE9CW0F4
    jsQTN7BffvyloTZgyEE90nniuhgNrt2Cs1LndJNIIVsLIMF2mSXMphtI+RL4
    tnOlPmZcLFa7Xk+di8ql+tkEYmH/NZU3uWPhmvEUsKdZSwhF2U982UwMvT0Y
    BfsT/fzm96BLY+2HinllgInLSrHDDJquP9isAwo2JIi3CdFtLfm+2HCFFliH
    FQkEJ7qe3LtUjrCVmx97/mkWuijiq1Sg89N6nr02cW5PI1CJODYe6+a20C9t
    SOhyncUt07AcTKAkNGHzBRX6R3iTdMGcqC98oCLrGafJz6O9k9IWC56fhdvo
    rjI92pgQjkTwpbiKL2k+UjLAcKvgztXxEjCvqqGuKG3t0VBT8e4Kk29KKr1R
    0w1UAjiPmrJk1ylylHgI+GlfU1fSs0bVbYqrz5jfrNlTOHCrPecXCBgI/Ox4
    V8t3UvtaNdHWs+Zw5lz/MPHlEbNsePJ8+crenjxDpA==]
