classes:
  - profiles_unix::gsc::oracle7::rac

postfix::enabled: 'true'
profiles_unix::gsc::base::auth::sssd_auth: 'true'


oracle_build7::kernel::vm_nr_hugepages: 3000

access_conf::access:
    - '+:root:LOCAL'
    - '+:(sa-local):LOCAL'
    - '+:(sa-remote):ALL'
    - '+:(gg-cgit-dba-admins):ALL'
    - '+:(gg-adm-gcdunix):ALL'
    - '+:grid:LOCAL cgeisdb1a.sherwin.com cgeisdb1a-prv.sherwin.com cgeisdb1b.sherwin.com cgeisdb1b-prv.sherwin.com cgeisdb1c.sherwin.com cgeisdb1c-prv.sherwin.com cgeisdb1d.sherwin.com cgeisdb1d-prv.sherwin.com'
    - '+:oracle:LOCAL cgeisdb1a.sherwin.com cgeisdb1a-prv.sherwin.com cgeisdb1b.sherwin.com cgeisdb1b-prv.sherwin.com cgeisdb1c.sherwin.com cgeisdb1c-prv.sherwin.com cgeisdb1d.sherwin.com cgeisdb1d-prv.sherwin.com'
    - "+:sa-qualys-linux:%{hiera('access_conf::qualys_ips')}"
    - "+:sa-cyberark-linux:%{hiera('access_conf::cyberark_ips')}"
    - '-:ALL:ALL'

oracle_build7::rac::ssh::grid_pub_key: >
    ENC[PKCS7,MIIDDQYJKoZIhvcNAQcDoIIC/jCCAvoCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAUV9UwjZlPaAGPle65LqQGBiYTs1oI3daotiZ
    ZR8p0m1W3BVs9xsz8qLaJ20vuE1Jo4F7AUP3jsV25NpIWkxUDcBrKnwrMiea
    qGTkZ2ZWs/1duodDuyMmKF2CwWU/gXlkn630UKxzrXaxjOwLMIo99vvWKUqg
    6SqS8PdcOHlOrWvKnK64M+hPH1jfPDHptQ250/GDPEqxyouTuI54MXgD5OD8
    j136fnpXWFkFhhnBB/Tv+JRRwLgZjwX2kADkO7V5xujS+OXkfJFwepS6O6Fc
    BizEV6G0n45oWH6YJBHyK6ysZZn1K5pPnazZheNxvs4F6ZNbpnBI5FGq2whs
    oNJjHzCCAc4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEA8gN3CGDuHxMuoK
    C8TZE/WAggGg715/1N9hC2yjn5YFXMPG5LmF5wZqFkjH/l7ZEuLu/CuQETP5
    2/Kh+GlGkRaO6y/3r3Gr1bzAV4HpiygdxZCT+axVAvSWaP7KFLt/GOR2rg4A
    J3l9im9PEWDcUylrYzoH27cC2LQFuAupwjapkyvcpSSI1uC9rKeE4Sm45fTz
    qhWlDimeJK2DMeAJqgCtax+b2SGtOQYSPrrww/zjHj+pyu4D5v4yQNIEfGst
    +w75p9r0d85MSOtxtwKezKd140y01Nz78GD1F3Za/32NxXsgXxFe6CoMmduG
    GbYr7LiS6pH06FuWLQWj7zcXdGl4kb8knHfgORbJ353Ji0OaDuvuMLAcUhRJ
    0Y0iNo+urd9zXZ4UR1KVwz/d7IrMHJJ5zXJru562AjtnIfAE2C+tFqhAQStp
    pIRSkJvkyntISiNdFf8TZSLbo9lPfQ78iMxlnguU6VuMJfVugINUmmHhA8Ip
    jWmOOGME/agLF9ztlbMYMqZqhK33s79pyvVxrxVimqz0kgxJtCdx/dRU0w2y
    nsavh9lOvhLzxiME5b0kUMySt30=]
oracle_build7::rac::ssh::grid_prv_key: >
    ENC[PKCS7,MIIIDQYJKoZIhvcNAQcDoIIH/jCCB/oCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAaRcrB0jYmLgIKXs5XlvqBgyXv6f0r7xPyM18
    120+R1fny7oecQpdZnAPqsP6hYAGfGYGo1Gnnk4X7XSIsYIR4VzqvEG8pR54
    QBZKRXZXvCL1KXToaVabqni5bvC1uwqIohIhe8sGjM/afoXw+qnaqt1cgEfx
    wFWE9iHIiDTskhLbhqMR1Ey2ZKZew0aLec2C0fE0sgwSsWoE3OQMVe7ymoHS
    k/McuS0p5KPiz+n/aoNRQjUwlxc2eXLTOdHeV0I49ZMcfvtu/Pxv9m2MWhb8
    L+ZMCXkRdZo/tXUotMB0ah01vF7Vq+8QNKvXNCshkMWd9ih43I3p7MWLmNVM
    9yVxijCCBs4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEDh7lCzUOcbZnjA9
    eijK64+Aggag7jilq8geYMsVYTdNov1qNWkZYJP0REvyXJgTmrIUjXCc/Yhg
    MtHF1LS0XYph2zX4n31xESWBHVHiPb157Q72AAq1KiTdJ/AaOV6QenO6gy1a
    VTSdVURyep4okA/zymPWcR/px2SN5R6wQzaF2IzQmL/pGpDtFfnrYjWCeuqg
    0GKLz0B7jtlqHore8vygBVS4BNZtPHAje8GlVYpWZp2t/Uy7/kast7FixACn
    hqP45P+mbSTeLZOteMDUszdWjUPo+JTXRPiFbILI8FXRtBg6l97ocHmZGolI
    gwhC3TuDhcwXJjZmwyJgghIKCpk2C5nqrq2mn9vwdAfKGqZmYlzFONpEqT7K
    Q1+TYXsJJT7qtowLwqzARlfH/DRGtoHKEbVTSmArDW3KrSgIspUs/4xrX9fz
    ViTkPsuM7VLywnfnPAMyokibTYEpt5h4pwqwUpbojlInZ9cV5Y7HCFK2QOsJ
    r8/iCy74Nvgg5UrHeSWhpsuLNZu2LR7TedZduUf6fUZ7lEpww3KGvv/dU7Qp
    WRDGu8txrP7QoWoLk+FiEY6XcktuYRr7NGkeXvIVcBe8PH4oby90htjT/344
    9qyUheaLar/CnaCK3SXgo1D90KEOAt65fcKXDNnNxS7pXR2md7jg+CwC+xYY
    X5YofLxkj532uwsZ1gY1P14aPAqHIleODnLFrD7jPdCxwqGbA8JbAJI42T5p
    u4xpSebYFNDXWAZuZjLT7Dxl8CZc4ioek0AStpwr4Rj7pFnuAhVp7G6PcIgK
    hN7O0JJRYvjmdK45vi0UAcKCEDhH5tL3WaIApV3klo5Sia2iA4vBhpST1f8I
    Er86NXtOvQxFxCdxrYu/hZg37/E2QVMPqx3L6TuhM6AK6aKmkPvDjcrOplkF
    PCmHx4+yBTI1oUQP/F59WYes4vzQRqtgB7Zwi1kSx3QADfQt25wKkln0cuT/
    iBNIlhcJHLwb3Zf6uWJavd5Yui6mVfVPAFy4Ayeo5rPoNlLw9NvO060B0SCK
    PfUcSCBId2zO5XMmoI4RjVB99Jpkeyi7f7zR8xvkUASXEF+IF9zEmV/Ms8gA
    J57ZMDoo/ygUn9cWwv8xI4saEq4jzOb9iDTTeVe4QAVEYKtZlHZgWoWB/MA1
    EgFPEmrbjPsDUdxghkqXOOBnwPeLk9gui+mi+umhlzBpa3pHSMS++SR5E4Qi
    4Derdjyh9u9sYIiC22xC26w45QiFelndExPNDNUOTbRteUERgcJEcYveK8PF
    lGTlf3/qTDsDQ+AHk5fuIP/dCQPf1iTvoWmBPYIvFkxNDmZLSbyDDJlwX8VW
    7D6mNUnIn9EI5JFpE+n27E27X+Hg+Cq4dpnOekoL9ioLwnagP7bcPIk28W7Z
    LoFCeyqIomKotbXaW2eDgjbc1cjV5kfGHBJzMShNjv1fF4c38Am1oDUu9gsA
    RRY0uRK66ov1qJVivELBEe/Q4aD81rkah29C7ozCJN4CS1Qdf3K0xNJdtRNJ
    IBCx/858TVl0RvgIElF274O//gzwjJUpmBlYNdVR9545zsoOIV3B0YAvDmiI
    03azk9PVzpkOlqcXWrwgM1J7TJkoICW/+T8dG4XdfsAxO77Q41T69/b3tbZr
    stZ7TDhX47fEeX6gWf2gQWq3KB19ot5hhkRtfRIYF8NvnqweDa0M9irti8F0
    dSlpJsH45uSsyyG2yM+mTbw5PCHyzIvLf5/j3LS+B4TIi6ujNAp6YGJpLVbz
    E1/Dii9Xf5kBUTTxZyMKOo9zCS+l5VBYJdhB5LsHQTpQ0Ng0UdN+GOoAa/yj
    YImmEfqlnBjnHRuWh2bIyIJfkE9P7LTwERTZGdBF4PlQRXBT70G23R0uh29p
    IIRSVwIMzdKZzqp3XYtuapDrB+zSU+eaKsj++nb/RSKj/QkR03O2xshXgLgs
    AZnIyfvE0Sa1wjhpsScidie32i1HrI/7Ub1CY/m3nY38gokuRHjp54xZCHP/
    At/D2S7bOXQ4tou3lrStVH+EGkTxTggO55Yuyos6plA/3uZ7ei1ESa3+GbcM
    +PzcSrBUlmQkikx/Fpaohsh+EI5g9gYQ4jAJWdq3KmswZ8tWtdkWVCM/TB6o
    OuSd8H88EpY8OFlbCO9dZiXwF5nLem69uiZMIjchM151ptsAkJenxcFg9KAk
    oDZIHsIR4fFELjKNBUoxVv+jI/KrQ5kxvOmbJ/XssWJURN/YPvdk3/pPHMfa
    tauKfSzOBHLjwshxztap1+ugB0LLyM6CkRoq7hNayK9owA8Z9IQT2A==]
oracle_build7::rac::ssh::grid_auth_keys: >
    ENC[PKCS7,MIIDDQYJKoZIhvcNAQcDoIIC/jCCAvoCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAUIyd89lygBC4dwxSGtGNWPibZ+kWQwzXRVWN
    7yHi25+Lm3exEdEE22hFE41EKa1H2Qb2BWNLq2uAdKOaKStvh6bxKEH3x2ny
    ju3C3FNENVaGh1FCRVc79f4BtJDyhHyFkG6Ka1wQN7cQW4QslH1Gpd3PumEQ
    CthM4J7/v8QN11lCArOs70O08y3/1fumtBpMdqu9mAHAQvOQBobttNq0jXQd
    /tVGgDiLwtrmLhsBZx/vW6skYLRev9C6ae0gDQUR3BVOlo7fhhZpCRN4O/V6
    RlGVoJbpiq7EUxotF7JapFcoSDQQ7oAc6vPNbDVP31SyM51pcDyulBHrkcoH
    TVKFkzCCAc4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEELYWp7iypOuAJbXB
    ImUj0u2AggGgxQoRPD5dlcF0CdeYYgEHrImCg3OGSIrGx7QtHYHtCJxFc2CJ
    FdwavTCsH3mN3EmI006gIW19xOrblT8+nbbttNEi66sXO5CxVTatBtEVJGsB
    MJaOBJCr7jRM/T0o0OCAJBouqCNNtsk7g7UErYFrmb9Uqb8wfQsuM5sUw9S0
    esqb34ExCycD/0Fu01McdebJjV8Hb6IzhvlHpHdTCBugjoN+8OiEUZEqCQ9i
    w6lwBkGFrZbP2lIiqa7KbF0s61zEmulQgHI9+7tssj+v0uZjfF7OA+D/G1HP
    sUE+S//7UYRHB1DdR9KMJyvTvxW4dtRkBE+lyPQqITkxoUKxkFVyTHFZeuYG
    MV0k6Z+h9nZh1uZaTbu6ed50cag3On3QaIp5b0NFspsLiwzRw2rO/vYX/fCP
    h4O2mnqGCYX8jEj3MkKcV8JIoBNpMLwM56tjxQaHyKatRKHwRZfDQ3GsmRBE
    /azvPlB74MeAu+Y7iyprf73EwkcoaV6QFERi9ubV8vYXxvxsOMYBX2kqhltV
    RdUeIj2+Lv1z/JgSDdLgAkRtiws=]
oracle_build7::rac::ssh::oracle_pub_key: >
    ENC[PKCS7,MIIDDQYJKoZIhvcNAQcDoIIC/jCCAvoCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAZxMkyc8G+9RYCW2VcuBPglBAC1EaZDo3ILOB
    SUtXy+529z8oZxh5e4rvKJ2RBcOM+LNdmqf9uyGzrmff394be4JmgQujv4pU
    crCQ/R8P4E7EWehlpwwSfqmZAFFAePEwggvSdDM73bE2+7LvDKoSsGzMi+aP
    O/0ukZjYQG04+omuQsvTvGwtWltXbxRLuiFmQps9zx43r0FnJz4FO2pwnbGU
    UG5jgF+0vPjCTomIZNNCNe6KljnYhFtqgJc+QpWpLDu4BMC9YKw1tyNJEfGp
    OxIdIrFv+Z3qhzlxiDWnrVHFdB+tYDj+HiQiGA3xUShXezShhIlc8+S8Zvkv
    DIzzKTCCAc4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEI7mBUkZ9nGcS/SL
    Pj/lXfaAggGgtTUyNr21Gy1jsnlXtmv2DZKTrJuqbggogB87H9fTSvxnsg6j
    g/lGTEcBeezyo5DIDYEoUg5NMramfDYnA2Nmek/0k6JwGs0bIItzjDbj8Y6Z
    FBppnXN2oOc896qzj9nnfLCTT2GXz8yRvz2jw+t7YjslnSqEDNIysS5hDhaB
    8IJc5NvdKqMRK0KWJ0qqP9b6bclVufQw3OaMzvN1bIMDOrV7BB8por5bxuVw
    Yck6fjvlgJcPqeySUotkUErtGVbn9bWbST6yANSsmOwZg6FZsjMqVjIathGz
    XPUXyGOwsMGqn/uidd6jRwp7XYCGhEWXbQjO4r5+JkwD9Mw1PglT7qxoX6kX
    TsxkvEc0ja775iGouTw/MdAGKiDpfDWEeBmNjmOWwRRJiSOmYijmxSPSufSS
    ebFilv6U/ItIVSyLYa0VIBd+PQmSJo32JGvDd1Tah/R9OOYTr0rDFfvl9SvO
    YyO4lq726wG0/mdAQ9TyZSHBHPPvfANf1hIeyvsveck8ORX4rXcAkqSpGU8Z
    IGrFYBTAn6UeKFmlaiOoI9e4Lxk=]
oracle_build7::rac::ssh::oracle_prv_key: >    
    ENC[PKCS7,MIIH/QYJKoZIhvcNAQcDoIIH7jCCB+oCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAj+ysjxtiagNdY7JgDKjuDLIqkFiNdRI8ZfuP
    gL2yYkV8EsqXxHIXX2MdTyx4LjrSFJkB/Cvql3KFp/c8TP4E5V/ffCIoI2Tk
    0y5KSIJ/CTLaQ+kYCpOczBMQENRvUF8V55uyRjGOa11Ro1F0lL8+nUusEiJq
    mjnr7la6paJpa6zoi7mO9vm9m1kVDl1FaLVVKxKIiHbyhtP8dJ/NvgaWFplE
    zOpcTufS+dIL/P5pmxr+YawYeXjbnydNQbooQjxDaJ5CvZWj72U+J1DvRS2p
    +ugz7J6skvAEjNUmI61fxLc36/a53FRwhrIhg9rnYmzVtw7f9tlFzNwsW9xh
    zQqfSjCCBr4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEJo3E8gGXpulgPBu
    J3HGIOuAggaQFhU2WUt24EZAaZOUoyGDemtOyyRdRjzAz155BN6Pfibdg9sC
    DC6oill/JH6tnppal+kLmZmV8MDp1dJg9UKWL8HwhFYgbp4pCNV8Sc6s7cbE
    GlHS/FTzJ+sYAbYDA8duKCXUJiLKQQC6do0PNDxvd3WKjRKh8CZQeNcCCAgC
    7UIGOFj2YowJsRhZ2NOTnLZy7FGfitDAcDAUG6B9+cD0PGOV8qZjzCr11tgA
    3KTZUDiKgr7Zc/yYiJE+coS4AwPzHkJ2l/8g3ohp+6xEfVhDvKypJBdtgjOE
    +WtFXqvgom3b7LpBuRmxce9Kwu0GJf1FEkjsCxZe6CiGOyOMLjx+5iqap4Io
    D72KzFmDOVbjBDJj6h2wDsonn2hqOnCP6bC4ubD2u0k+9TU2sge5ZtFvX9ls
    qUOBnmuo/CJlhA9eMuvkVMHVXnrtpRjcAwtmm3VAH865kFI2y4dX4ehR/GnA
    UML1YsZ4kuuVoeH9WWVBll+A9iJ9PbUVAVBkDZslGw5N0diWa31K+Jpi2d6Y
    l++nxPtRs7SS/8R4zKqlqDWc/GXYx4ch6yLX6fLh85ivGZX8//qI6YJ8+jhZ
    kaxRdQc8JG0xCcZMO68VY8nZA3GD/Q9N+nkhPiDzjnrkLSPE0wmoSZ6FqIPH
    1y//6iufCEqgycaY+iTHiUkFiBxaPaD488XSSbM+FpJBjbJJnrJQ40u9V8Ry
    TsutDmipjWZ5YWVTm2RNKzohv750Bd3z0PM8Pjr81TI/D7fMDPwyb1Y24xuz
    M0qL1Fb+8GbYiF23BhbqzmhWAOEwZEcvWUjnJHegfqUC9jF2W6YxAkW4sjzp
    qnQdvzn1RMycDkyQTvf2cHgrAM2L1z02KbKdQ/49ceTH+NOh1vH/8OJMXvZy
    VethC28nBvtq5/Ek4OL7C0iAVn6D3I/aO2aRmpuJVoNsJekbKfjqlxh+u3fg
    /6ZtYAN1v2EP1Qjl6tQO6yF+ziWWVXRZP9Lq7XcWYtAeiYQWxBBu/RpGHyYD
    PEzoK+t+B6OYNUf6105RUApASSf7Svk7t81GZUydnng0QgD1OtFG01Cwyn8r
    GTdoLwwpH8r0aiDKinf0KzGi7xfs6/VsyqpkC9PPcacjiw9a+dii5OEzZIQd
    SNkUNV9kcs7lZ6TaQyClWfpKMgcvDOgu3g7K0frj4NeFkMscupx3H1W99Eoe
    OuDUEnT08+1qj2vb3N6MD1nL+3Lh/ghhUZYeo09U8LaewZWmR5hf21kofh7Z
    tSi+PRHR31lSteRoMJY7WF9G+h0WDT56ugZb12prhrwNaWlU86qnbn5tf3UN
    6+TBNnmlTZ3L6kwgpLfZNdid82kStZqLcwHIkDedXdBTVKYQa1Vmmt56ZnpN
    H5QsVJj0CnhwlsG9F3m77Px+GK77go0Dam8v0geC0zBrrFK2qFG+baegy/EU
    aS3FvzayfKcnRI4ukR6gSWH8aiIufZz5sM8gBSnH5XVEq7fqoowW555AYGgn
    FCLVyx2eox0keQatCZcIK91w1o6HOYRMzTIiJOr/sJCycntdqo47Cvmn9eBw
    f9dPik5KpEd3V4bQsskRQmqEyNlmCorHA9iy5Pjh2d0bv5fjH32RJouUtKLb
    nFmJynuM82Y8kyRzg9exfEk2LgqWBBGy53/vX/JQtLBASKbAtJefoKppK5gj
    FChmyZiJb9pXkO0kGufI0Kmd/p0BVtTTOUEamcrcuRMYTBqDlZumZzqQAKx/
    3+xs969zEsa0hte6rIVza4Kltn+V1iRZeQG5PMdaYu2iXfYIplHrI7RolUg3
    n3BzCBPuWin4d/ZOIlLSGf5fp/Soq3doEIk6VX0SxsC0uB6ZSVaMFy4OFWse
    dVgcG3zpC3ZuN05hjOi8ISTZWnPeZH8PMtfZh7MhbIE05R4klx/v8G1ZD2v5
    AVmz5NVFNwp0ht7woa5CF2CADTMRptVH9uy6K+mi4gG/nC5g8fyKKWvzYz3R
    +7vkO7Mnv7MS3DOy3JoV0iRqYBhqjdJ/IbJRti2XnCyPLnae8J3kxuysqhnD
    YR3iCf4dk06f1eQQZ1067MZEkzMeCe3xklWCesgyfN+G6cQUhfJ1kAaFAKx/
    GQgXKaJOabiDWwZJWda0y89S6fMpgP2dMgGl9ekGrQj6E2DgphnbyIgocM2g
    znARxyAW22aydrU6Vtzh8qXzjWaFYljZJBTPsqqfDFUHRaMvyBbhPmjxop4K
    dSsYFQ+REroOJDUY7oUDFlchN7ygfQmC]
oracle_build7::rac::ssh::oracle_auth_keys: >    
    ENC[PKCS7,MIIH/QYJKoZIhvcNAQcDoIIH7jCCB+oCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEADXrr0DF7f3awglPuzvdORBrozI4bj7rwJnnr
    IcdFxFZPU5Qc84W36tkCZWDNKKC2x9wzlAhLLxCMZWIbMJ0Z6HeakKLTSHyi
    61mEklMGq+WMg9crunEWefNteU3K2j4wrWgqtpQvKijk+EjzlKqdsd33YMgx
    H4kNAGSk0x/3yXIgMISA4Hw2x/YgaIkn7pRj1N0T1yIWNZ7Veh8OJaz5YW6b
    cttEhqut4Ps5z99Tu95bPR5rDvU/RlsSbig2SJ8oYxjFWW9DgFNOcVKKrzE5
    pZip4Bj/4yOiVDWzqdMZalhhY43iJV7euZPX4gQqL6hSKaVWDNw1PfBT3auC
    UuCusTCCBr4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEECR61hS3hJ2+E5mk
    sqYwdN+AggaQfRAID8gqv9keJk3FW5dMnj+hser3XZITwfs6dW/bjGAY7lmg
    Yx1uLP8SfwGJLlS0Sa3408w8Zsm8oiHSrr+zBoDrNyd1RMIRde5wAvHdC4hl
    xzjCVRIceZzAeYLpx5xlbbuUiNG6+k61Wan0Qr50tF02YTOBZgnok8wIIByQ
    ttFVvHNanZF8SGhdemza4jhq9pirhbHa/VAItHo6/5wS8Vj5og/aEOiGstc3
    ll4Cd1OPZTVmahlC3e8h6YToYJws/uwsbVSI/Y22DkDlqxt6bzKgB5HJZlmM
    RszJgbUjCjEK1LoTI+t1dBm4bgauHdtfLku0DJXyMFG56qdZkIsmiYIuI8NF
    ibOqf681FXaxZSsuPDqDA+Nk2AFcVnlJSI9HWHJlWR+KFsVvKOq2vW6D+v67
    I0S/1PUKtKzWFPTrOrQWDpznTz+pHE2tZIaQPlqFW8pZvehlviMxpzdqlKtN
    /ErZwIeRLRiagh9WusP0AURzGlqQ162BLgsoYWDWxLSZ9Nlf8ZPMzE1tVGLW
    XH0pflHGu8m1QWcOIqlV1pQoAgzl6T9sHV729ECLVlLvTidj0Lte3SRlCUrL
    jaSdyc2s+E+uVgWDIqXmeMff6B5c26ILK9q4xoV7h1zqpRLR+D7HZ4SWlRib
    hGBSMe5yCyqYs3aqU8BNxhqUhUW8gMRm3wmx/TFu9LP/R4/DMOJq2BMMvf03
    ThTC58GPyWUUmeV2NlP9fyAz3s0YDnX8ipmeB0YADP6ugkY1buGnwhG5mUZ+
    q8T77soGzkNlrkku0m9se9w7tgSeNKl+6yNFfDxNtYhLvMtDCQxHhyaXrBUv
    UX1KDtOcdP7DlZgscTMrHGJuRo+QJ+rBPo5sKosVWThY8fwl8jjy83Wfa/Ds
    g9La/O1CS1CjZ9yOiqoL6AwzbHulvXF9guPBqSWz+8FsFFco8bfiYVutfqvD
    o7zbPq2BY3tflS6p8Eif13adcO6oDXoxQyAptPZxoqRGtaSfmke6r7VH+4/Y
    1zTmA7Xdqb0ZKXlOt/X4GoH6caIQsS4o8xp3dSpGPKdajCofdqscVhthcNF1
    ttSQDwmE5chtZzUywACGm32bacFGwh9J7Aq4gVUAvH0qvUFqb5dO00T9d11H
    vNA/TNLGYXfWzdpe3jewtiOt096v90oTtFc1HthPlL+VBwgokkHxHj3d+Tbm
    H+GZKx8KTjb9DKMeFWkaNF65lskZ84vCwj52rfFQorncAWYViVk43gIM+vIR
    NDwb+zQhdPp9KIZhteELy5C8Tj+bhDeN0gzgRn0HWA2dDWuwh/E03qlLk81e
    DEL8rMIrUSwATmEeeOufhKFh7SjU6/Lz5hYhdLg9Sx8GC2f2M1XYbK6bEwp1
    lV1ejmBoLWsQCJnkw06UE/wHS8OQAaQM7GskMTvW+ExQDH8QynIckDH0qtcc
    HbaYQ/W+zff15Gc582u3L7sbRcU18Opt5K0wuCPDOgZlZw+lvHn/lKgFdPs5
    AmSDhGb47knAEPMH20qVMO9DFiW//+qd84fGPsbJma+JIe2ePieg8GLtlar1
    PG3meL27S8MYWk5QJDZKjEtBpz62dI3/LtqAdVTGKhcp07cEC2O8Xtr0k2EI
    UmhTbUcKgugdOEQE68Ny8V+KDBe6fM4idDsACMcLnchvcZ8nazsA/t5F7i2t
    tZQjJUQ5Wadik03tNw0nK332XEINcJgzj3DJNaElTVkG5oETBnwvLbrASq50
    2Z70hNjgLSIzMURzc1jIMoqlyC8UDWx3MFv1ujY59+VYpjI7C3CSPLkhi9VM
    FvnZ22Pe0lbzvJHykGakhnro32i/VJ5P1LAqDuvrwk/z7/6ul0UCsJ5f+Lv3
    pA8n8N9JrMzvmahte0ZV6+fi9uBcE2DZbjLeuFKxqXSGZP7ebZpoibiPMhEu
    fQgzl6ifEx7fWGGrG7cHtiYzpArUYt3x6Tpi+nBOwYhWcjHoRVXim8Le6P26
    uDceUAYQR4+DDJ2Cc+r4gjZ7sZoUPuNTQs7+rJL1dDGS+eU/NSUkqQ09Qq7b
    rXEKFA0n7i6+vPHVtiffBA1KeROveymPpASltTXJA0kMbKCDtB6rQzVBLsp/
    PSIUZVRsuR+SpblGKzgmgfSnDYqGmv+1s8JVPZZMfjQVFz86PmQV5LzoF2X3
    fAYz3oPEpNo7v1EKKN0qywFmyTlUKrr0qKGmoDTa5cp29DCZjpJVbxHa7AgO
    y7nQ6//m5W1jZGG3N+hLlQOTkvrYMRl2]
