classes:
  - profiles_unix::gsc::oracle7::rac

postfix::enabled: 'true'
profiles_unix::gsc::base::auth::sssd_auth: 'true'


oracle_build7::kernel::vm_nr_hugepages: 3000

access_conf::access:
    - '+:root:LOCAL'
    - '+:(sa-local):LOCAL'
    - '+:(sa-remote):ALL'
    - '+:(gg-cgit-dba-admins):ALL'
    - '+:(gg-adm-gcdunix):ALL'
    - '+:grid:LOCAL cgeisdb1a.sherwin.com cgeisdb1a-prv.sherwin.com cgeisdb1b.sherwin.com cgeisdb1b-prv.sherwin.com cgeisdb1c.sherwin.com cgeisdb1c-prv.sherwin.com cgeisdb1d.sherwin.com cgeisdb1d-prv.sherwin.com'
    - '+:oracle:LOCAL cgeisdb1a.sherwin.com cgeisdb1a-prv.sherwin.com cgeisdb1b.sherwin.com cgeisdb1b-prv.sherwin.com cgeisdb1c.sherwin.com cgeisdb1c-prv.sherwin.com cgeisdb1d.sherwin.com cgeisdb1d-prv.sherwin.com'
    - "+:sa-qualys-linux:%{hiera('access_conf::qualys_ips')}"
    - "+:sa-cyberark-linux:%{hiera('access_conf::cyberark_ips')}"
    - '-:ALL:ALL'

oracle_build7::rac::ssh::grid_pub_key: >
    ENC[PKCS7,MIIDDQYJKoZIhvcNAQcDoIIC/jCCAvoCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAUV9UwjZlPaAGPle65LqQGBiYTs1oI3daotiZ
    ZR8p0m1W3BVs9xsz8qLaJ20vuE1Jo4F7AUP3jsV25NpIWkxUDcBrKnwrMiea
    qGTkZ2ZWs/1duodDuyMmKF2CwWU/gXlkn630UKxzrXaxjOwLMIo99vvWKUqg
    6SqS8PdcOHlOrWvKnK64M+hPH1jfPDHptQ250/GDPEqxyouTuI54MXgD5OD8
    j136fnpXWFkFhhnBB/Tv+JRRwLgZjwX2kADkO7V5xujS+OXkfJFwepS6O6Fc
    BizEV6G0n45oWH6YJBHyK6ysZZn1K5pPnazZheNxvs4F6ZNbpnBI5FGq2whs
    oNJjHzCCAc4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEA8gN3CGDuHxMuoK
    C8TZE/WAggGg715/1N9hC2yjn5YFXMPG5LmF5wZqFkjH/l7ZEuLu/CuQETP5
    2/Kh+GlGkRaO6y/3r3Gr1bzAV4HpiygdxZCT+axVAvSWaP7KFLt/GOR2rg4A
    J3l9im9PEWDcUylrYzoH27cC2LQFuAupwjapkyvcpSSI1uC9rKeE4Sm45fTz
    qhWlDimeJK2DMeAJqgCtax+b2SGtOQYSPrrww/zjHj+pyu4D5v4yQNIEfGst
    +w75p9r0d85MSOtxtwKezKd140y01Nz78GD1F3Za/32NxXsgXxFe6CoMmduG
    GbYr7LiS6pH06FuWLQWj7zcXdGl4kb8knHfgORbJ353Ji0OaDuvuMLAcUhRJ
    0Y0iNo+urd9zXZ4UR1KVwz/d7IrMHJJ5zXJru562AjtnIfAE2C+tFqhAQStp
    pIRSkJvkyntISiNdFf8TZSLbo9lPfQ78iMxlnguU6VuMJfVugINUmmHhA8Ip
    jWmOOGME/agLF9ztlbMYMqZqhK33s79pyvVxrxVimqz0kgxJtCdx/dRU0w2y
    nsavh9lOvhLzxiME5b0kUMySt30=]
oracle_build7::rac::ssh::grid_prv_key: >
    ENC[PKCS7,MIIHzQYJKoZIhvcNAQcDoIIHvjCCB7oCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAcfitTMDJ8RwDqRn0HjW5pKogmPwc3GmBkwHK
    RRbEsXVBWlVBjkmTL222qDOXwviSdxWhF9kmonJ/243GQY6+hvo2usazG1MP
    LwXK6SCeYd98ZpOQZmHxtFfiG+Gr0IV1jXXEmW4QaPSufNhe+SsCCze2IcT8
    NLlvJMiPPYTpy06Ou2lZ0seuQXZHtnghAikEA8E5iT2MRhHg2MThG3UuPMBG
    wbNaHLF65aWhTaxo4FhHovFx8bFsT1R4dxbz4+4J7D6dFpYmTwRltbz9tXS2
    OGnnIpI1gfsdMiIHeerfHfBu3Yn1rY3Gy7ySpHX1prQd7NVNQaK8nSVsfBc/
    ez11wjCCBo4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEKySliEEdEYRHHO2
    TzfHQTCAggZgBHcdey9b2Ex714FqWWRxAjb4n0satoLgbknxFTqvj/XILGtx
    RV9IUUaMJrOSepb3hs6/u176CCEk4Hc2O/XrN+/LkQcDgwySLiLTzIVK6n6Y
    MN487s1iClQTd1CG6AEO9WXHYWbjf1q+1h9uElEZ22v6HmzTFVadthDO9TGI
    CuAV3NBlUxtvNdKbfkmlD4H7duWPeje5Y6f5bMOOGnPVYCj8kf0jmlD6rZaq
    6q+tPfl5dlInWEA3oepbQ5sBhdNFtlaj/sd528DkoaSKRSZVpBhgiwLxs/+I
    9Z5KAxvxaXvkR++vehPHjBGdelWBsCqcXA8P5Z9EqPGoHEDTvWoJ33RqXz+4
    SkLUlEP8zxcs940OGKRlvEaTKK/DYptd//rt3A1AmjiLgs86+RlBWRBdCOgJ
    XjmdAAVQLPhoOGLc/KbfuZN3FW2Numux//dqmh/VjzEe/p9KARei7i+vZHQ5
    Bgn3u5nyOUWswNrKNaujgAmY85r5j71uNuHIM4TArxY5/nmC/+WYUF9sOAaD
    9MvwAHMxEhwlIXAj9+9dTM41MH2Zhq7Dh0RNk3T7desDD1IVZFTpGmRcAz4A
    hXF7F/NOtyLBaBEeGp4ZKufkw6e+wKg/0DIkNqoQO5FdjgfUxtwgXe/GrKPE
    mv7N5EDRRnhn2o/fA2ogSWPQCt39RGaN3RlAM0F1HWqD4c44PrVfdLSldwy5
    U9NGI6nroiOnDjEv/+F0n33CxtzJ9WTnK/5OS399DNhqMUqZKom64UOWxq/E
    2U6wijtGo1PRQmOMXM4uf6DLUtAiOCob3qVAJIWK9nzz3KtXXsg6uEfGmSig
    Bu6vIgSW3VjXuwEfyt2Th5a3musFupYGxqmeNpnqQBq1kjYKTz9NN6VDLBkG
    MPAapsdn0F3VKdODkBL/NxVKvhp8MmpUjggWmXi42nrpdwCV1tx6SmJL6KWb
    FZ99l+EyFKUrtfK5La17c83RSd8M5Pn3seagZn8+VNbp+qJws18VKh5d7cMy
    2TWKR9y1hfljo1Aj0kkV8pMa19MKFvsBVlDMXJIDnhSpegA9CDCmP4JWS+gT
    nxOJF2lt9LUJMJMus4/wmgqaQCD+ejvvYPzgTJ2zVVqn9tHFFpwp0Ppm44oX
    9JQttqn43XrRUjOMBCTlRtsx82wAxQ70xA/EcBhtFs0V4YKa5kQkykRynflx
    2ZLsOTovZt006sdCY9SQREGSuu+w0ZtZYprqi3ncw7joZwTdYrJRS4Ac5kJB
    4NSLm3Sx5qvv709myBuK1DOmrfJRV1JQb2AcE+MoIl+Lye4PfKpQ9E6U9Bph
    A2KFVzXbGzLDnzHyfC8odU9TcxSrPvueHeCxTs7vHMoJpRqHo10DLAMGPLa1
    ROeoSDfsIX95gh2guwzfNrtHFrdR2QQrqwXa79Bl5z6n4o6j7FoTmLyFP2fG
    HLiRFTV1N0BeLIU/96RozvCwzBNFE8bOD1fYuXBdnRluX805EX8WhFLLTWNb
    nmYemqWB2huKyveF4kcNb2dpkh10LcaQ5CIcuF14ivqXsBseoR31ooEliDha
    hkiil2EN+mndufqUCjq9csc5GhoksdfPTlPIBQPydyPCWvURUjZKXtIBPcZc
    3BvfmN83iinz69c7RSdxf5WXgTSgTwjNCsHEm7sH3dAIo63sw24p4wA2MtrB
    UlkVHJ/1iPrfKAOtPK+aPTcJ/yDlsdLs03qaqs3iaXj5tN43nNrG3Lznet8S
    e3w656QQ/Utrdhd1NZ798bZrT2qiDZbz7GQYbRqhjgc3Sj8BGVmgLzJp19+w
    /2UaKAHth9arTDLG+ki+HJMy53ncyUKtqRuxk4DvmHExv6udzNi8jsY7ZPOA
    WdzDUI1vmCTTLKfY7PmmttEGVQQN9zeclISu1mwFso85+AWJp5MnRiqsHDet
    mCbIECOo7QdkZUGdoIQbuV529LJ10DOmAtJFoITwH5DraLE/V7sxO5/irSKq
    m8aQltBUW9AjeOVgOyw/JshLAPsTei6TqO7KYyrdNSGP9tGull9ZqthgtGsL
    f01v2M1lVzMcslf10P1bBtfNKLG3nUYWsgicJV1GDQM3n6NEcJDjMCDnv19v
    07tMT4TLIbGAhguLXxO4mP48xEaFH/P7w65QL8JmGyaOHC9L/qq/nofXMCsL
    ylq5bDTdjdjeeFyboWU2jQmZlq6p]
oracle_build7::rac::ssh::grid_auth_keys: >
    ENC[PKCS7,MIIDDQYJKoZIhvcNAQcDoIIC/jCCAvoCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAUIyd89lygBC4dwxSGtGNWPibZ+kWQwzXRVWN
    7yHi25+Lm3exEdEE22hFE41EKa1H2Qb2BWNLq2uAdKOaKStvh6bxKEH3x2ny
    ju3C3FNENVaGh1FCRVc79f4BtJDyhHyFkG6Ka1wQN7cQW4QslH1Gpd3PumEQ
    CthM4J7/v8QN11lCArOs70O08y3/1fumtBpMdqu9mAHAQvOQBobttNq0jXQd
    /tVGgDiLwtrmLhsBZx/vW6skYLRev9C6ae0gDQUR3BVOlo7fhhZpCRN4O/V6
    RlGVoJbpiq7EUxotF7JapFcoSDQQ7oAc6vPNbDVP31SyM51pcDyulBHrkcoH
    TVKFkzCCAc4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEELYWp7iypOuAJbXB
    ImUj0u2AggGgxQoRPD5dlcF0CdeYYgEHrImCg3OGSIrGx7QtHYHtCJxFc2CJ
    FdwavTCsH3mN3EmI006gIW19xOrblT8+nbbttNEi66sXO5CxVTatBtEVJGsB
    MJaOBJCr7jRM/T0o0OCAJBouqCNNtsk7g7UErYFrmb9Uqb8wfQsuM5sUw9S0
    esqb34ExCycD/0Fu01McdebJjV8Hb6IzhvlHpHdTCBugjoN+8OiEUZEqCQ9i
    w6lwBkGFrZbP2lIiqa7KbF0s61zEmulQgHI9+7tssj+v0uZjfF7OA+D/G1HP
    sUE+S//7UYRHB1DdR9KMJyvTvxW4dtRkBE+lyPQqITkxoUKxkFVyTHFZeuYG
    MV0k6Z+h9nZh1uZaTbu6ed50cag3On3QaIp5b0NFspsLiwzRw2rO/vYX/fCP
    h4O2mnqGCYX8jEj3MkKcV8JIoBNpMLwM56tjxQaHyKatRKHwRZfDQ3GsmRBE
    /azvPlB74MeAu+Y7iyprf73EwkcoaV6QFERi9ubV8vYXxvxsOMYBX2kqhltV
    RdUeIj2+Lv1z/JgSDdLgAkRtiws=]
oracle_build7::rac::ssh::oracle_pub_key: >
    ENC[PKCS7,MIIDDQYJKoZIhvcNAQcDoIIC/jCCAvoCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAE5ENEQDUfHluAuPQCDD6rwmLA7CLQgOWx+5G
    Qs+0jv0RcHeesZK2dqgNiQ9NQH3sNcJK8V74TuyaDnVxyuBun7TNqIjglNYY
    CPK9qDDnySmmNIISQ/b95lnkO2+xgvEbn28TOaCKoFQLxfJc1jsn9S1AYx0C
    eoeovcR2VEYfResRN9zeJbyT84QGW82Wd+NfAAp5nuChiulzA9/oiXJgYmto
    2sMOrE9zUCY0eqEm+XNcZTUYtbwDPhuGo2tYQ0G+u2nsSI5iJoFe998kcjun
    Gh2fdUZSdFUmHgQX6XKNtj2rmy7Ocd6qFO9jI0MNYCmpN14+OKaxtTWBwxZc
    cRJFQzCCAc4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEAty0JtaJO12UT1y
    ZxfeTjWAggGgvN80rmsudEO+7RrBjsMnBgy1APsa1x8XVGfp9LDMGZlcFXe1
    O4LaJKluk3zirQ9KFu2M4bZPWF/9L5ELis+OAlOSSIX4LIBXmPpnzBB3UTY6
    wTfJFxejKDDXfAaFdmE9pW4uVYAvq/QWjhcZ9ekB60+YPOsZ5tRDdUDbf/0Q
    R2A0jeIU29XcfpavS6fuP1g/M+kj75RSKioGGsdzUGKmXcugbelLswJHIAJ0
    KTLwKbMQBgfo0TphE/aIhcHK0hsi/OVzVVIlmTOWPM/EnwaQl5dTmr2TTpqE
    TdMaCVuIbPa1J/t+EiTtCslJpMvAk0UZZHaptZqWUTNz20KTN7Gj3ZjIIGMq
    krLeEWVafHw5//5ajRb+mvZDShOJJ1E9DOBNe6BFvTCiOjDKYwSIojZFbQ45
    HdGH3G6lacmGyfvWP5ZLNhzKeVQwMM+g3X7hqs84CCz98HtxYx61qLwZEcuU
    jzQhYPgbzZrSLhL28utta7u/o18nDddS5rkirt2DU4iDHGowBV47FUULn7Op
    TfvrZdfsVICqDdoZb9cWa87GQ3s=]
oracle_build7::rac::ssh::oracle_prv_key: >
    ENC[PKCS7,MIIHzQYJKoZIhvcNAQcDoIIHvjCCB7oCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAE3ZcLxW/jpCSF+vlogj3A8bqQNFw8gZ0Ah3/
    KYlyZRGQ52c4plHBuFwSaPUGki2EdsXH2Qw3zQre/fbZOKayQalGWe5EPNrX
    peOQP6IEIhf4l7+EyUxdSt7EiT6DNJMV5ISyfpcma8fArbN5Sy3UP/m/mGHU
    gaS/Y5xejwAN/SjYdXlqZMpBmiICHT9MOSSHVCG6uG+mJfzYBI5VZLz+yXSb
    V2VXtTHA7kZyub5SCAezE4OglnpCXnEvKvQTtj41yFzhyjvjdFW2A2dwmNWh
    lpI19jG8qJOHKf/OuK72+oA7W5x+PEN/pS/CsXwWm67HyMWpylAD1hAltxts
    /YsuITCCBo4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEGTehASLtB6XwfKV
    CWyV4cOAggZgKdN0698OaHKuXg+XjQc/4PkeDlAByBJt4+Xx1adDRhRnIoEV
    SQeTLaDY0is+H1ohWtcSyV8PfgqczDgrtzD307tvEeg3802wZ+XJc6gtMJxJ
    vNe6hUJfyBvFu/XdG5GGH8XVigiwY5eI/hvKlbI8D5W+hvVXh5yJDxn30vVN
    RQ6qtoBbnFqqqPCAbVmnWv3r0hpCb3fsuzdCGy9A2mCjhHQvU3B0lr5kIBJG
    apVfW9S8Gg/JrUWFSzCeD1gbDpUR4vYZg0J99rIfvb8874ALUCOxtPm55Ytj
    O/OcPw6qEPh81g9h55oBpfkY9Kagtveof/VmqCin7uhuA38V6TUuNmv5f02N
    69lhvkEkJEBq4MnsQxXH5/RxpFyPf7L88WXeFZR2KjVEdQU1ks1fE3XsIwOu
    UEJta4XiITnZ26h3n7rnCREtE031ml0xKtBNW95mwAE8VR46YmV29ANN0IWW
    ZzAuRe7H+zwFHGhgss3dTiI30+iqhz8P0yJsfUbUd9Ac/nR8KcgMV/n2w3ci
    M+B3xPmeo9mNvyO5w249f1dNqfBMbuiYdsUe18qWR8xxnjgBOr4O9c9+xgg5
    tx8LJDRhT3NeXJFe+r2hqhdjzSueqE2CAryQAxJx7D8IZ3QvPO0aF+wCW+04
    3cPE2Ze8GC+sqOYVmF+vsDLT1NijENlPgZmPtzq9AtQGyJqDL1c5GHutMVJH
    Ot51vcZd1mh7XWLRaaYihIyzevfdDmxu6B1I/bP1DkOlQeCSeJ1uARFzBcyy
    KKkh5CByTnxGOqkr8b4wsZbibOMAsqwtqjSaTPIn0/lGDf6GgcNRa6mvcpuY
    clQXsAXuIr46qbZmS3PphFZJwXMcbbH5xAmq0EsB0bVe24vzFTuptD+iRbgW
    cKtZZhxt6iHms97uJW1Oh7ZSWZqcebnaG6jAssDyEgV9PbtbEzCQTKfpWybq
    /dw5ovfge2w/0bdB0CSypDZXkpd06WhIfL6B/h4X15jhnqRY05hgiWLXPFCC
    6aBQX+E6zb7Nrm/5c7br+R7hvBiCoRys114I4MTGdqxCxnoXH/qxx+qYpOpL
    yT+7fqxuqTozEcaVfUhmbPdBB7F/e7yi1rZjzRIsm3BBx/dLgeb61FAAe6Fy
    DHLeKQWEe00eXf/w+wlxMZBpJ8Pcx+UuOcbV+Ub4Rb5yGnEFHqfoLPWXQhrb
    C0qsBaIBlU42FSL3cOucdoIYg5oYW811znqwJSP74e+LDX35pUVoiUvSZd9L
    UFC88MMZUeo1vG8OjQsllAswJtDG1ORS34GV9fpNwXvbkxe0SdrwUYSg4Tlz
    o6Q4xOgDPEWCdo+1AYOQk3mK7b0KE3rJuH/7pnJZ7cfOeAyEZnubunL4Xac7
    UtbUzVEvEnsrxx5nhBTYFvahUJoS3cadYAqjVajRE/7PRyDdEu4vRIcl7O5l
    Z5HzGS/bnTZr3X46Tb7t+t8+NN4CfTwcnX9xuEwMHhQ3JJU1m4Lg4vbSvkt3
    zwPmakepYpaGtS/uc2S2uFX7ENjfwKIORVFqN545SO/K2iIcaOTxbHDUgTOu
    KbVGMp2uYYfvGtK1n6Og6jJ1aORFH47AJl/Vl2owRfcAnBkMNPN0dq/GoJa/
    M2TqpbqNAOHqMafhPMiHjmC5covMpYQZAcodDwno/ia3u8juN1ELOE/av0MA
    1uC+4EuMBOxrnNlyESag7GjBQOu1oY8NUvRUp9rduUT3a0EHh1ttoOq/6QtB
    QiAROPo9PIQW/iB1mM6OyAYx/6JLfepArKnc6MxwPef92fUzUWE//2MiDBc1
    1Ym1m6Wla9rVoeLdApvtjOcuoPjhMhcLgsgPZkLm6susSKoC7DBxK8Nn+IUB
    vESsZ3C2fC1uFQFoaagmgoDENuhFhoCrJO61q2D+o9Z0bNSzmeaFUNmgZ9oJ
    KeM5bzrbUATv8O491BAClVDNWPyxrBrjAm2v52rkw3HES7GdUDP6RAaiQvKC
    Z2gPBb08oT44oNsvvFfKezD+kbaRUzvcd4KKxdWpV4IfCPiXUCcJ1V1GOCud
    N7NgnJFDdqhPdegSNuS/TvRQ+kbz6aWhcAh2OJ3l4W80qblFoAra1YYg4qhb
    ngi0Gj3jT1w2+hghRtmeriVA+a86iU0ETp9ZpdwkuRl1XuMoZPLIPGxKFt4T
    F8uNVMj39OMZf7A+Mx+GL+LvfC1I]
oracle_build7::rac::ssh::oracle_auth_keys: >
    ENC[PKCS7,MIIErQYJKoZIhvcNAQcDoIIEnjCCBJoCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAfG9n8diBsflGkPK2cBFuHIRun+I8js4uR48J
    FgaKVjRVKB996ZFneMd0ED1kIQ4N2Oh+xhBQOrbiC7si9ePL5QICqRuE0NDF
    IpXNj31PsLxV8zMFRAQ2aXObPmlurp9QJu7lqK6VZbSKKEhaQMqY9qCqoICj
    8cjeU7vCmGpZOguh/NO2kxn4ScZ9rnOhO5phypj3+7OdbfPfySTP6bSNp6ky
    soZW6gCqn5+dAW5L8ek3VxfkmXWySkRd5UW7AedB3NvEvey1YCIkZd8cBTbG
    0b4QpSjdbxCugJIVYjiH7UmMZKgMqwBBfmWpVxeTH5c2x4dUCGuAp+BZcqKW
    3eVXVzCCA24GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEDc8NmVOcpQU5Kdo
    k0aQ+6yAggNAHjkTtTAEI+luxnw14OKQFeKkN6t20MIZiu9gKJccIOxFgFD3
    i0eXQxyzYxEEDi7nqIdqREMwYsrOUxXZNmvSLQACEmg128PMjhvv3zsGwXu2
    /Nh5IDGSYJmDzZx+DTehyJYR65W8BIrathlZcvXiRSJ4dc8FnR0XZV3s7oIB
    q5C3ilKsdwI1eRlc6Ay7ihUfZeWFF4/mBygmeaRXp8ML/g7OyUfw45mrP19H
    C22aaw/w3MOA3L2FhP5FQKRhV2/BLmmoCZ5jJpFjmvu3wW3y+RYwQrNvLMFM
    UTN/+8gHNtAzKoMbpdEyj0spURaQUiagqzeN7iYAhaPN9oHrBHRnnOsbicOF
    Wp5qfBrLXW+KZAKWo6eHGSTqqmtrK4jecDoJ0SHBBkF4rBlskTP3NGzucw9C
    66JqaYuIG0YYfj2Fh4B+lJgTWmFc2rdmateTK3BnIJ5LP+X6wVtB2B8OCmJa
    dBX/O0+UDwzPRUJW+GOczGheygoRyafmUCF3FH8ThBIvwbf1rIP8WQ9iqPz2
    1N35RaIf1rzA7leXkPAd/YmHrbca/24JcGYpsKPHN3PNZczIUIjtZP9PLfGj
    /sHFGUkfzi5V/rbJQ6R5wvhyj6mqxnbS/wgG0M5OBYJwjxS29wUxV821JTDY
    T/o/Y0t54j01T+NAD9veyif/aKNaJoBhPfbjACCrH590CE0awdqUpYh2GcxQ
    lRcq3/jdVyUeGKrFKqQujwFLxlE44fodGa191SVeFqAHP50ng2P0Lm66cSUl
    CxCRcZd0yM8wwrtuO07dVcLAW99mgmvvnTfZr2492p8ERlAfklpDxtFR3OnQ
    8xakAYWL0eISVtVrhStbmuZKwCysMrgVXC/7lHuR3BoDN4Q6JyE2NErGtvmW
    U309t4HaG3HAUMGeZKpwghyEErY+Xkbk7FP0tVaDD6JaTbElKgAxl3Mb0il6
    oO8DDua7znG+QpHCM4zsigw6wZvm0FG4RGOKN777s/WdJ1hgdEDKCt82+x/t
    g5oQkzmpDJo0lcYkGGZb+F6ixHzD0Qa9pF2AD3dphtLxZ4tR+LeMXb+cg5Vx
    jT3KT/e3U74okt9BnOJ0mRF7tnPUZpMwOcKRol9opA==]    
