classes:
  - profiles_unix::gsc::oracle7::rac

postfix::enabled: 'true'
profiles_unix::gsc::base::auth::sssd_auth: 'true'


oracle_build7::kernel::vm_nr_hugepages: 3000

access_conf::access:
    - '+:root:LOCAL'
    - '+:(sa-local):LOCAL'
    - '+:(sa-remote):ALL'
    - '+:(gg-cgit-dba-admins):ALL'
    - '+:(gg-adm-gcdunix):ALL'
    - '+:grid:LOCAL cgeisdb1a.sherwin.com cgeisdb1a-prv.sherwin.com cgeisdb1b.sherwin.com cgeisdb1b-prv.sherwin.com cgeisdb1c.sherwin.com cgeisdb1c-prv.sherwin.com cgeisdb1d.sherwin.com cgeisdb1d-prv.sherwin.com'
    - '+:oracle:LOCAL cgeisdb1a.sherwin.com cgeisdb1a-prv.sherwin.com cgeisdb1b.sherwin.com cgeisdb1b-prv.sherwin.com cgeisdb1c.sherwin.com cgeisdb1c-prv.sherwin.com cgeisdb1d.sherwin.com cgeisdb1d-prv.sherwin.com'
    - "+:sa-qualys-linux:%{hiera('access_conf::qualys_ips')}"
    - "+:sa-cyberark-linux:%{hiera('access_conf::cyberark_ips')}"
    - '-:ALL:ALL'

oracle_build7::rac::ssh::grid_pub_key: >
    ENC[PKCS7,MIIDDQYJKoZIhvcNAQcDoIIC/jCCAvoCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAUV9UwjZlPaAGPle65LqQGBiYTs1oI3daotiZ
    ZR8p0m1W3BVs9xsz8qLaJ20vuE1Jo4F7AUP3jsV25NpIWkxUDcBrKnwrMiea
    qGTkZ2ZWs/1duodDuyMmKF2CwWU/gXlkn630UKxzrXaxjOwLMIo99vvWKUqg
    6SqS8PdcOHlOrWvKnK64M+hPH1jfPDHptQ250/GDPEqxyouTuI54MXgD5OD8
    j136fnpXWFkFhhnBB/Tv+JRRwLgZjwX2kADkO7V5xujS+OXkfJFwepS6O6Fc
    BizEV6G0n45oWH6YJBHyK6ysZZn1K5pPnazZheNxvs4F6ZNbpnBI5FGq2whs
    oNJjHzCCAc4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEA8gN3CGDuHxMuoK
    C8TZE/WAggGg715/1N9hC2yjn5YFXMPG5LmF5wZqFkjH/l7ZEuLu/CuQETP5
    2/Kh+GlGkRaO6y/3r3Gr1bzAV4HpiygdxZCT+axVAvSWaP7KFLt/GOR2rg4A
    J3l9im9PEWDcUylrYzoH27cC2LQFuAupwjapkyvcpSSI1uC9rKeE4Sm45fTz
    qhWlDimeJK2DMeAJqgCtax+b2SGtOQYSPrrww/zjHj+pyu4D5v4yQNIEfGst
    +w75p9r0d85MSOtxtwKezKd140y01Nz78GD1F3Za/32NxXsgXxFe6CoMmduG
    GbYr7LiS6pH06FuWLQWj7zcXdGl4kb8knHfgORbJ353Ji0OaDuvuMLAcUhRJ
    0Y0iNo+urd9zXZ4UR1KVwz/d7IrMHJJ5zXJru562AjtnIfAE2C+tFqhAQStp
    pIRSkJvkyntISiNdFf8TZSLbo9lPfQ78iMxlnguU6VuMJfVugINUmmHhA8Ip
    jWmOOGME/agLF9ztlbMYMqZqhK33s79pyvVxrxVimqz0kgxJtCdx/dRU0w2y
    nsavh9lOvhLzxiME5b0kUMySt30=]
oracle_build7::rac::ssh::grid_prv_key: >
    ENC[PKCS7,MIIIDQYJKoZIhvcNAQcDoIIH/jCCB/oCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAaRcrB0jYmLgIKXs5XlvqBgyXv6f0r7xPyM18
    120+R1fny7oecQpdZnAPqsP6hYAGfGYGo1Gnnk4X7XSIsYIR4VzqvEG8pR54
    QBZKRXZXvCL1KXToaVabqni5bvC1uwqIohIhe8sGjM/afoXw+qnaqt1cgEfx
    wFWE9iHIiDTskhLbhqMR1Ey2ZKZew0aLec2C0fE0sgwSsWoE3OQMVe7ymoHS
    k/McuS0p5KPiz+n/aoNRQjUwlxc2eXLTOdHeV0I49ZMcfvtu/Pxv9m2MWhb8
    L+ZMCXkRdZo/tXUotMB0ah01vF7Vq+8QNKvXNCshkMWd9ih43I3p7MWLmNVM
    9yVxijCCBs4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEDh7lCzUOcbZnjA9
    eijK64+Aggag7jilq8geYMsVYTdNov1qNWkZYJP0REvyXJgTmrIUjXCc/Yhg
    MtHF1LS0XYph2zX4n31xESWBHVHiPb157Q72AAq1KiTdJ/AaOV6QenO6gy1a
    VTSdVURyep4okA/zymPWcR/px2SN5R6wQzaF2IzQmL/pGpDtFfnrYjWCeuqg
    0GKLz0B7jtlqHore8vygBVS4BNZtPHAje8GlVYpWZp2t/Uy7/kast7FixACn
    hqP45P+mbSTeLZOteMDUszdWjUPo+JTXRPiFbILI8FXRtBg6l97ocHmZGolI
    gwhC3TuDhcwXJjZmwyJgghIKCpk2C5nqrq2mn9vwdAfKGqZmYlzFONpEqT7K
    Q1+TYXsJJT7qtowLwqzARlfH/DRGtoHKEbVTSmArDW3KrSgIspUs/4xrX9fz
    ViTkPsuM7VLywnfnPAMyokibTYEpt5h4pwqwUpbojlInZ9cV5Y7HCFK2QOsJ
    r8/iCy74Nvgg5UrHeSWhpsuLNZu2LR7TedZduUf6fUZ7lEpww3KGvv/dU7Qp
    WRDGu8txrP7QoWoLk+FiEY6XcktuYRr7NGkeXvIVcBe8PH4oby90htjT/344
    9qyUheaLar/CnaCK3SXgo1D90KEOAt65fcKXDNnNxS7pXR2md7jg+CwC+xYY
    X5YofLxkj532uwsZ1gY1P14aPAqHIleODnLFrD7jPdCxwqGbA8JbAJI42T5p
    u4xpSebYFNDXWAZuZjLT7Dxl8CZc4ioek0AStpwr4Rj7pFnuAhVp7G6PcIgK
    hN7O0JJRYvjmdK45vi0UAcKCEDhH5tL3WaIApV3klo5Sia2iA4vBhpST1f8I
    Er86NXtOvQxFxCdxrYu/hZg37/E2QVMPqx3L6TuhM6AK6aKmkPvDjcrOplkF
    PCmHx4+yBTI1oUQP/F59WYes4vzQRqtgB7Zwi1kSx3QADfQt25wKkln0cuT/
    iBNIlhcJHLwb3Zf6uWJavd5Yui6mVfVPAFy4Ayeo5rPoNlLw9NvO060B0SCK
    PfUcSCBId2zO5XMmoI4RjVB99Jpkeyi7f7zR8xvkUASXEF+IF9zEmV/Ms8gA
    J57ZMDoo/ygUn9cWwv8xI4saEq4jzOb9iDTTeVe4QAVEYKtZlHZgWoWB/MA1
    EgFPEmrbjPsDUdxghkqXOOBnwPeLk9gui+mi+umhlzBpa3pHSMS++SR5E4Qi
    4Derdjyh9u9sYIiC22xC26w45QiFelndExPNDNUOTbRteUERgcJEcYveK8PF
    lGTlf3/qTDsDQ+AHk5fuIP/dCQPf1iTvoWmBPYIvFkxNDmZLSbyDDJlwX8VW
    7D6mNUnIn9EI5JFpE+n27E27X+Hg+Cq4dpnOekoL9ioLwnagP7bcPIk28W7Z
    LoFCeyqIomKotbXaW2eDgjbc1cjV5kfGHBJzMShNjv1fF4c38Am1oDUu9gsA
    RRY0uRK66ov1qJVivELBEe/Q4aD81rkah29C7ozCJN4CS1Qdf3K0xNJdtRNJ
    IBCx/858TVl0RvgIElF274O//gzwjJUpmBlYNdVR9545zsoOIV3B0YAvDmiI
    03azk9PVzpkOlqcXWrwgM1J7TJkoICW/+T8dG4XdfsAxO77Q41T69/b3tbZr
    stZ7TDhX47fEeX6gWf2gQWq3KB19ot5hhkRtfRIYF8NvnqweDa0M9irti8F0
    dSlpJsH45uSsyyG2yM+mTbw5PCHyzIvLf5/j3LS+B4TIi6ujNAp6YGJpLVbz
    E1/Dii9Xf5kBUTTxZyMKOo9zCS+l5VBYJdhB5LsHQTpQ0Ng0UdN+GOoAa/yj
    YImmEfqlnBjnHRuWh2bIyIJfkE9P7LTwERTZGdBF4PlQRXBT70G23R0uh29p
    IIRSVwIMzdKZzqp3XYtuapDrB+zSU+eaKsj++nb/RSKj/QkR03O2xshXgLgs
    AZnIyfvE0Sa1wjhpsScidie32i1HrI/7Ub1CY/m3nY38gokuRHjp54xZCHP/
    At/D2S7bOXQ4tou3lrStVH+EGkTxTggO55Yuyos6plA/3uZ7ei1ESa3+GbcM
    +PzcSrBUlmQkikx/Fpaohsh+EI5g9gYQ4jAJWdq3KmswZ8tWtdkWVCM/TB6o
    OuSd8H88EpY8OFlbCO9dZiXwF5nLem69uiZMIjchM151ptsAkJenxcFg9KAk
    oDZIHsIR4fFELjKNBUoxVv+jI/KrQ5kxvOmbJ/XssWJURN/YPvdk3/pPHMfa
    tauKfSzOBHLjwshxztap1+ugB0LLyM6CkRoq7hNayK9owA8Z9IQT2A==]
oracle_build7::rac::ssh::grid_auth_keys: >
    ENC[PKCS7,MIIDDQYJKoZIhvcNAQcDoIIC/jCCAvoCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAUIyd89lygBC4dwxSGtGNWPibZ+kWQwzXRVWN
    7yHi25+Lm3exEdEE22hFE41EKa1H2Qb2BWNLq2uAdKOaKStvh6bxKEH3x2ny
    ju3C3FNENVaGh1FCRVc79f4BtJDyhHyFkG6Ka1wQN7cQW4QslH1Gpd3PumEQ
    CthM4J7/v8QN11lCArOs70O08y3/1fumtBpMdqu9mAHAQvOQBobttNq0jXQd
    /tVGgDiLwtrmLhsBZx/vW6skYLRev9C6ae0gDQUR3BVOlo7fhhZpCRN4O/V6
    RlGVoJbpiq7EUxotF7JapFcoSDQQ7oAc6vPNbDVP31SyM51pcDyulBHrkcoH
    TVKFkzCCAc4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEELYWp7iypOuAJbXB
    ImUj0u2AggGgxQoRPD5dlcF0CdeYYgEHrImCg3OGSIrGx7QtHYHtCJxFc2CJ
    FdwavTCsH3mN3EmI006gIW19xOrblT8+nbbttNEi66sXO5CxVTatBtEVJGsB
    MJaOBJCr7jRM/T0o0OCAJBouqCNNtsk7g7UErYFrmb9Uqb8wfQsuM5sUw9S0
    esqb34ExCycD/0Fu01McdebJjV8Hb6IzhvlHpHdTCBugjoN+8OiEUZEqCQ9i
    w6lwBkGFrZbP2lIiqa7KbF0s61zEmulQgHI9+7tssj+v0uZjfF7OA+D/G1HP
    sUE+S//7UYRHB1DdR9KMJyvTvxW4dtRkBE+lyPQqITkxoUKxkFVyTHFZeuYG
    MV0k6Z+h9nZh1uZaTbu6ed50cag3On3QaIp5b0NFspsLiwzRw2rO/vYX/fCP
    h4O2mnqGCYX8jEj3MkKcV8JIoBNpMLwM56tjxQaHyKatRKHwRZfDQ3GsmRBE
    /azvPlB74MeAu+Y7iyprf73EwkcoaV6QFERi9ubV8vYXxvxsOMYBX2kqhltV
    RdUeIj2+Lv1z/JgSDdLgAkRtiws=]
oracle_build7::rac::ssh::oracle_pub_key: >
    ENC[PKCS7,MIIDDQYJKoZIhvcNAQcDoIIC/jCCAvoCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAE5ENEQDUfHluAuPQCDD6rwmLA7CLQgOWx+5G
    Qs+0jv0RcHeesZK2dqgNiQ9NQH3sNcJK8V74TuyaDnVxyuBun7TNqIjglNYY
    CPK9qDDnySmmNIISQ/b95lnkO2+xgvEbn28TOaCKoFQLxfJc1jsn9S1AYx0C
    eoeovcR2VEYfResRN9zeJbyT84QGW82Wd+NfAAp5nuChiulzA9/oiXJgYmto
    2sMOrE9zUCY0eqEm+XNcZTUYtbwDPhuGo2tYQ0G+u2nsSI5iJoFe998kcjun
    Gh2fdUZSdFUmHgQX6XKNtj2rmy7Ocd6qFO9jI0MNYCmpN14+OKaxtTWBwxZc
    cRJFQzCCAc4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEAty0JtaJO12UT1y
    ZxfeTjWAggGgvN80rmsudEO+7RrBjsMnBgy1APsa1x8XVGfp9LDMGZlcFXe1
    O4LaJKluk3zirQ9KFu2M4bZPWF/9L5ELis+OAlOSSIX4LIBXmPpnzBB3UTY6
    wTfJFxejKDDXfAaFdmE9pW4uVYAvq/QWjhcZ9ekB60+YPOsZ5tRDdUDbf/0Q
    R2A0jeIU29XcfpavS6fuP1g/M+kj75RSKioGGsdzUGKmXcugbelLswJHIAJ0
    KTLwKbMQBgfo0TphE/aIhcHK0hsi/OVzVVIlmTOWPM/EnwaQl5dTmr2TTpqE
    TdMaCVuIbPa1J/t+EiTtCslJpMvAk0UZZHaptZqWUTNz20KTN7Gj3ZjIIGMq
    krLeEWVafHw5//5ajRb+mvZDShOJJ1E9DOBNe6BFvTCiOjDKYwSIojZFbQ45
    HdGH3G6lacmGyfvWP5ZLNhzKeVQwMM+g3X7hqs84CCz98HtxYx61qLwZEcuU
    jzQhYPgbzZrSLhL28utta7u/o18nDddS5rkirt2DU4iDHGowBV47FUULn7Op
    TfvrZdfsVICqDdoZb9cWa87GQ3s=]
oracle_build7::rac::ssh::oracle_prv_key: >
    ENC[PKCS7,MIIH/QYJKoZIhvcNAQcDoIIH7jCCB+oCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEANzdH3Li7iIA8bVvvNelFvSHRFwqGLr5WQ/84
    I3GGWFMWJz+slDBi9LcV54SdonoT6q2W+ZC2+sPOWOdHn+CCDiLrCLmtdcGv
    KthYgeQefU7fAJnP2J9fR+PmvZHVbSZAohevO6Fk6lrAR5ixsk8F/RfFlThH
    MVVHHOQoEWJPuvXscfHEaND77NKxjAuLD9SNVc7ABUCAy3JlNRJSqrFVgA0b
    tSHc6s+m4wG9mRe98G1U/I8WadnjxX/+EtpXqXMcVAq3emTAeh79wcPjleQe
    20kGUIZsmhdG7Vk0ws8w5h969P6y5nyulP5/tNfdu8PKZOmRwsDw3lKTeKxR
    1n2w0jCCBr4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEJejvnWLM7fxP3P0
    PJ3R3UOAggaQkv2rANtdnO8kQiy54/LSvSnMgOlxWt69UgF2KpXgCdoHNr1y
    lTasZnQdG/keOKvN1qGIljUxq8eZYfTryVWqYWkefmSMa4BlcqgdIgV1qbXU
    HW50sU8Pp4sV4DtQVg3q6pVmHDmLQmKDiuqLlAv4ICdZAz9Tyeg0WvHBkolP
    Xy2AMyVnFrsBwJTYm3UYJaN5cuIQPJJzfQKqToD2Xvu2pbvqM+IVgU7HNSsE
    YUWTjG7dhSFFylcPtvYedbnm95YWFHiUBvbYL2eApZL+tsJ3jIAL82smgw0r
    wFI3pCW69csgGlzNcwP0ay6Z3Mdly5QmoYHy9VF5o+kzSgBzdjjEEcCYgbUW
    1YR5wvqFs8ySBIm/wzNaRLyIYUSz4ds/UO9DMe9Uv/i1bOxfpoigAfMXCFlG
    NmIKTBFOVdBOZODWj5DX+PvcwZwCZRdD9JSXzUsbcNy4KvPlDrbIspql4K38
    7//H5+Gh3QG5ZZXYnwlnnFwljYhBAKFhuljJ+iWszdb5ttIBle2Na1oqyWdQ
    RMSP2sG1SfxsUfg/+hvm6mfrcZPlvJ8h2wjDSRqiSS8f8FC0ooHWHIHAbeWS
    Yd8FB5iO4viP3Yc5pB+4OLS9GMRtpd1YYSywM1cmKGPu4B7b/g8kVgJwGyFi
    NkYFyrqpsJrr32nKfAyUj0iyaTVEpqc7D6gUviW50LZEuQ2lVfQ0zHYZb4zm
    PT+vgrJA10yt6rmEY8I8sVMBg5hPpOctZ+YoNsD6F31EqGJ8eLsjbMe1KfEE
    WgzkpIc9OQAIjAJ/AmwmURUoMB0miDUf3ECqHVpYzq6Hcq9YmWfqhpdY5QXj
    3PQ0LQniW79rEocePP6Hl7TkhblYayP7Q6JjBtS2C+nvZWh5xoKbicxx4jwg
    1ybOlWQgRgoKB/qrgrzElYD60XlFP+R5IW27BnkoSd7CQtnNY9sByFnBDZEH
    VQJt8rf9EkMkXg+qH1GVuGeQa3Osg72ZPPwF4lhCmKH/CaayeLAl3P50wPVX
    uw3G/MljoUhRqVH98AiJZ/U1gO7PAXsFmXuSdD4amuXcvqtV2m3lQ+iAADBq
    Jn9prOaibZL1wkz9i+C7CrYAHZwKxChizrlpXAmNtEtjlQA8j+GenmIQWzxP
    sikIULnGFeXeX9XK+hiwnbIkmdkB8j6mlRcNjOvmxJmcX8tFCbSNJuVJzihG
    z/aAJIGFBHJJgDEhqzYRHxRQaJz3mhccgLiu5Dk427uFnL4h10ZqJasltdOS
    Akg07Qj0BTPzZKcxq03ZEC3T1WErVbLR+V0hYUq7ARHCIO8ciUSHemFHJego
    6Q026/TDg/pYpHGFBMZVXxtITR9MAuX4Y0nEg/7PwzY0HXj2CW8OtCJ2hKEh
    8KrNSKxrvXAHwFdAWEoTDrim+FpwVD99yF/s8NGxnpoA2WfvgT+PsHZz5msk
    o5Up66QF9wIsf6ky1wjBJcFXp+j9pd7ll0oPtL5NZ5kGeNgEMqy/LHdeFQkb
    83tqebftfr8KWdn2YJOb6hU6PhAOpsLB70m3sR4JLr1u5nSGGYE3KVzasvm/
    Jspx4KUWrQVsT+Hw5ACRBwpzPsqsEzXEmmY3gpD47x4qLehJnydjhFPzBEgK
    olloi2gq1Su6qwo2Z4SnZwOH4rAym0IGm+ENP3iG1ANtnPcgp9BW3ymYp0M0
    LqNYq18iJdsl7sSs2Zv5BSFcay45wojm9zxRPQjdoWrsU7Hhr5cyxp0kDS/W
    CNwByKusge8CHz8oagcT3G2a2ZApEa3GWnhXv7o2rCD1jmLgx3wbfynILGWr
    IDQd+MpeMgLKiRW7VceKDhxi8t19VnK4R3pR51QAoXmZfS4I3N0AVQLH+7x3
    2SbMu9vHkrsApBhShXuXo7DrR3S/Fmm+pBO8/ZgDVRp8w7MIIyzlSbEqXZ3L
    vPgfMQOoBTGeFkwSUXmnUJ3bGKKFDXEyFohxtU6W0Xf5yaTiMmTTUMwFcyRr
    ihQUYEXAHfjLedjY4VtpNfDMHvb7/ELmpqOA8MUA6OdbIoSp4d/RAFglKPGx
    Ra3V9hbFhzNxxEGi7X/oJHS6e4K/1TFPEhrRrV2Lmpfun6eRFLKpwojE/4X7
    GJchgqy6X2/kL12iQXp2DUdir9JsTDXjJyTWVSJJA31gtwSX+Qr6cvjZeEJB
    YJNN0aAd73bTs0JJCQj140v1N4i8GlMahOO8fxwL8Hldk9AoflKRR53voMtf
    4Le0HdrALO3wPBm0VMclaVQeffIguGL1]
oracle_build7::rac::ssh::oracle_auth_keys: >
    ENC[PKCS7,MIIErQYJKoZIhvcNAQcDoIIEnjCCBJoCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAfG9n8diBsflGkPK2cBFuHIRun+I8js4uR48J
    FgaKVjRVKB996ZFneMd0ED1kIQ4N2Oh+xhBQOrbiC7si9ePL5QICqRuE0NDF
    IpXNj31PsLxV8zMFRAQ2aXObPmlurp9QJu7lqK6VZbSKKEhaQMqY9qCqoICj
    8cjeU7vCmGpZOguh/NO2kxn4ScZ9rnOhO5phypj3+7OdbfPfySTP6bSNp6ky
    soZW6gCqn5+dAW5L8ek3VxfkmXWySkRd5UW7AedB3NvEvey1YCIkZd8cBTbG
    0b4QpSjdbxCugJIVYjiH7UmMZKgMqwBBfmWpVxeTH5c2x4dUCGuAp+BZcqKW
    3eVXVzCCA24GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEDc8NmVOcpQU5Kdo
    k0aQ+6yAggNAHjkTtTAEI+luxnw14OKQFeKkN6t20MIZiu9gKJccIOxFgFD3
    i0eXQxyzYxEEDi7nqIdqREMwYsrOUxXZNmvSLQACEmg128PMjhvv3zsGwXu2
    /Nh5IDGSYJmDzZx+DTehyJYR65W8BIrathlZcvXiRSJ4dc8FnR0XZV3s7oIB
    q5C3ilKsdwI1eRlc6Ay7ihUfZeWFF4/mBygmeaRXp8ML/g7OyUfw45mrP19H
    C22aaw/w3MOA3L2FhP5FQKRhV2/BLmmoCZ5jJpFjmvu3wW3y+RYwQrNvLMFM
    UTN/+8gHNtAzKoMbpdEyj0spURaQUiagqzeN7iYAhaPN9oHrBHRnnOsbicOF
    Wp5qfBrLXW+KZAKWo6eHGSTqqmtrK4jecDoJ0SHBBkF4rBlskTP3NGzucw9C
    66JqaYuIG0YYfj2Fh4B+lJgTWmFc2rdmateTK3BnIJ5LP+X6wVtB2B8OCmJa
    dBX/O0+UDwzPRUJW+GOczGheygoRyafmUCF3FH8ThBIvwbf1rIP8WQ9iqPz2
    1N35RaIf1rzA7leXkPAd/YmHrbca/24JcGYpsKPHN3PNZczIUIjtZP9PLfGj
    /sHFGUkfzi5V/rbJQ6R5wvhyj6mqxnbS/wgG0M5OBYJwjxS29wUxV821JTDY
    T/o/Y0t54j01T+NAD9veyif/aKNaJoBhPfbjACCrH590CE0awdqUpYh2GcxQ
    lRcq3/jdVyUeGKrFKqQujwFLxlE44fodGa191SVeFqAHP50ng2P0Lm66cSUl
    CxCRcZd0yM8wwrtuO07dVcLAW99mgmvvnTfZr2492p8ERlAfklpDxtFR3OnQ
    8xakAYWL0eISVtVrhStbmuZKwCysMrgVXC/7lHuR3BoDN4Q6JyE2NErGtvmW
    U309t4HaG3HAUMGeZKpwghyEErY+Xkbk7FP0tVaDD6JaTbElKgAxl3Mb0il6
    oO8DDua7znG+QpHCM4zsigw6wZvm0FG4RGOKN777s/WdJ1hgdEDKCt82+x/t
    g5oQkzmpDJo0lcYkGGZb+F6ixHzD0Qa9pF2AD3dphtLxZ4tR+LeMXb+cg5Vx
    jT3KT/e3U74okt9BnOJ0mRF7tnPUZpMwOcKRol9opA==]    
