classes:
  - profiles_unix::gsc::oracle7::rac

postfix::enabled: 'true'
profiles_unix::gsc::base::auth::sssd_auth: 'true'


oracle_build7::kernel::vm_nr_hugepages: 3000

access_conf::access:
    - '+:root:LOCAL'
    - '+:(sa-local):LOCAL'
    - '+:(sa-remote):ALL'
    - '+:(gg-cgit-dba-admins):ALL'
    - '+:(gg-adm-gcdunix):ALL'
    - '+:grid:LOCAL cgeisdb1a.sherwin.com cgeisdb1a-prv.sherwin.com cgeisdb1b.sherwin.com cgeisdb1b-prv.sherwin.com cgeisdb1c.sherwin.com cgeisdb1c-prv.sherwin.com cgeisdb1d.sherwin.com cgeisdb1d-prv.sherwin.com'
    - '+:oracle:LOCAL cgeisdb1a.sherwin.com cgeisdb1a-prv.sherwin.com cgeisdb1b.sherwin.com cgeisdb1b-prv.sherwin.com cgeisdb1c.sherwin.com cgeisdb1c-prv.sherwin.com cgeisdb1d.sherwin.com cgeisdb1d-prv.sherwin.com'
    - "+:sa-qualys-linux:%{hiera('access_conf::qualys_ips')}"
    - "+:sa-cyberark-linux:%{hiera('access_conf::cyberark_ips')}"
    - '-:ALL:ALL'

    
oracle_build7::rac::ssh::grid_pub_key: >
    ENC[PKCS7,MIIDDQYJKoZIhvcNAQcDoIIC/jCCAvoCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAYeoIZH6R170BEyEUeutKK1krq8Nai0G/Rbdh
    fmHQOTTx0SUuKEHIb0dO0Kz8aOyMHTB9pVjFkkdj8A7z5BgnN/7jly7ZR6Xk
    i85A0JFdysFlBzWGfKymKZjKa0K8cLmTNcVgdCb1rifC1FmvqFLX0Q1p0Lrw
    QNq7C/sqHxvLb58x6OsGsvgXnrjGHYYTmIwSShgxBCJIR9vM+eudHbjqG+qZ
    2ldyVFKTtDd9PSFR9psAkSWxmNrgFmjN06Mk6qC/QAwUXJovUf7aWY391Tfr
    HqgwXzF4bGwhvp4vMuheZ32A1vfSSO7UINkSYayoH30b8KPYnhb3GgfpDTZ6
    0mz/KzCCAc4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEK+XFcAs1FWNGd9A
    9gsdiBeAggGgMJWPaTL/Ng/hxd6sNR1Yr83SQXrT4puTUpiNI8/H5LsXhTLx
    O3xnOYBPnH5NUfh+cbCpESrDdyGKiG+uH84t7rAQX6ASvlHfVKFjpOaayMoZ
    m9Vy7MXF/mJ9tb4wjiylpUxbj13Q6UTdicfWZ97CVqAVN/rzuU2wLicvut1B
    lRWivy2SltzflraEFmj7zlpLi8tbcyaP1uZ75dImho449c0IFoThJkfvAvMO
    6EqE50DK5JXYP3fs/vVHAMohXValh1mT/e84ugE6GmFanOeQVQLgqZcQFhbZ
    3n2O9srpakvahny3Z8PErnuLX4T2FuN4ohu5BESPqwW/aA7PV41tdv1PG4nQ
    VCkso/WmPybLJ72wc/xZcNK6mm3VE8zkRHZ8A0dh5XWvzeZeEH3q0yX44rGV
    DekKZ0ZgbJBWcUNdDPTUSBf0bsnsq3JrATBrl9Nl70pt1avNIAxMINem91oH
    fEjTqOQDzgzUml5ylCYs/KsNYKN7q0XHAOKAIX/mX/6QR5lK40fhJ1xkgZPE
    9/5UvauNnRFJqmNV0KkzWd1QKEw=]
oracle_build7::rac::ssh::grid_prv_key: >
    ENC[PKCS7,MIIHvQYJKoZIhvcNAQcDoIIHrjCCB6oCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAj3EgQskgkn9yKVRmD5N6qL3fIvgLZ8IWQcje
    6HFND+UZnNmWOvtAfzG1jqj6sEJnTKMmLFb0fexnD/RGF3n8tFd6KrSwrKJ5
    30ulTEwkG8QnEY5lCJ8lJlJonRP1cvQlHuFkSehDthCNEhsnkDG9J4e4dr/T
    lgwO9U7ddZzfTXiB8oSzYyHlK8Y/9zTN7sRjukXSkPMqkiCGP1oEsLw5X9xe
    OYB+LIcJ9y1hutLWYZe/9HtBX0VJdo/svp9+bVVjo9a8/lG0W9r86ZbUlirN
    kq1raZ7V5G/w/1sFsaw1AO4+4cKqigZLTsQR+pKXgtNU5vnGN38/Cv9Sdu2T
    3CQqHTCCBn4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEECJvTbqg7NJQ/JEc
    +n1gQ/SAggZQnnKvHKtnMPBr9tSV4Mv3hJbtX4cJ1QUtfvwhMdIV5w0D0i0D
    cQCyeTka9i8n3r5n6Ik653KKSpuUKdf6HMadBLwfJB/lokIZTiPt5sC7mGNL
    DSoo0nhXCwag88wpuCve2TZ4BKJmKFGp0b7jiVphpfuGhLCQVEqMXybxVvlp
    ePqe2EhLlR/QiqUJz08Xe8wIWB6ic7rbqdbI0vgx0URB40pGz5tqcOltoKaW
    UofyI6km+CTfqALr6K2IaVyFIUTiEmAEfcIdgA1FUWZ7Mea1PuWTex6hhRH+
    aAyFgKFFJduqK34Ys58V0Bxgk5WPdRNY/neHx9ubkwQRqtGeUMyEnoUHkWUY
    RSyvh0bJukZe0uS2dBtV2yybmx2jj6NK8/Z5x2jGPFeOt3bGxOgVO+7T/CCo
    onTvd2ub/6qQVAHTyawiRKNHdwZJziLA8ktI+EWIPpvuYw/zLeB2ciq7KSLm
    nZWyq9/5qEYdITIHH0SGC4osJeh8iCGbGZM2l58Cws+3wWS725QKOAfeoUku
    OGY1RzbUMwiznZ3oJk3CsUiItCizT0c8rgwTH4m695lPJZaDE/wQf6SZXHxL
    hjYwxHgMOpl8IWYhuQfQofXUTL0+GTXzOxnBIzLxE2UT0bhnDRhwkTRGH3Eq
    DHYvChaQcAaGLxbwL5E5M7RzuZwNqMXLSW2nTRmEm+AUTUA5d6us1HXMSrZC
    0a2ebhsts1EyvxOKNrSSkimj0he+lqU065p2HpmcclegnJJuMPcBAYFLjMJB
    ys9ApnWHItq09CSOigKY+KgDVPMXnaTarHFkWMPkqu7XMGZo7ca4SYmLQte0
    1RPdMU/LGO4YITsCqLkcqI6Yh0eHNrsz5j1oPO+niIwI31BCYUNqDiAbF5xC
    eSczD6NB2Szmqi12l83jhN5KUoWzM3nXHoJO4hXG9g6MBV8umngbenEZ7mXc
    a0N5Thcosby7X/fe+uqw4TUR/pgKhA/TsOLDLtlcEAa2TcLPyqQHnU2M4LNp
    DBwppvsdJ9TQf88iyXlDrOpkVTQclAkjGgQpsWuJ2zWADzvY3C5Gb52bjeZt
    O7GHge05b7U6lAi+ZPxM2dURyAIFkR/QYs5noav8dheW8aBLHvdbHlTKMrWP
    Ith2GBQUF60wSxL3AXx7KipHLX85qCW61OlZZ18lP7cS4geFeZtsvGpJ3oYq
    fEzW+2Qjt9li2YbNUn7c2kZxHs175tHYBl1CnS9lRvJdMb2RRAzKBM7W29rC
    CNQ2tCi7u75+4zdY7u2mCp9zLIfEdddT5N+zdW+AbFYz7HVezIL/GhRRRTtS
    ylcj0J3g7k/ws9WKBZNKZcym26J3zL9W3QIWsfM2qq9BYTnIbPJX7yq1GiSR
    /B2Jthb+PVJP0mm+Us1XihiI3TbS0m6aQRYIsfV6wrhPoqSDOpMJCV2lyvXI
    5VrT1lNt0BLkEkSo6f0AdOU/NeHOCtfk/aVJzRiY2qE3P9XjvFd0JCeEt6zL
    JjZgwUKi0pVWPR0pTRnHd8ghTirMUmdLzxlKPwpkFAGuYW7FXClUfyfHoVGc
    okyV/5+1PEp6UGsRTJmWR9okbAzvtyDYFcV7AFOaqrj2vo9qQKogn5kBd3ec
    9Xg3LsdUNh/iGc6BWKKncJCbr7T/Phg+cvVmS6AargjXf0Z6hRVO1DNVzkU+
    HCC353MScNWfKGg8wq8OdRTxYRwtxV4/SB8poIJf+RflZG8tCDmYTeQvYsw1
    aqd4d4FqGSJYg4exjS6u5x2ivLtI7UD6RKZowsM+7CiBdWBsGSnCeC4/+uPt
    SG7XC6bLRKeHE5kIcjQb4lPOxYQH+N6e+A0eRK2C21H/rQaGOev/n634kzjm
    E4Nt2cYm0/hr7/KJSzJVQBkxiY6LLBn18tEZLXMoiVQ67JefRtjNfU8c3/m2
    p6QArIebLTHXDXt0aUoNqAJJ6sn0TfsCFKGUPHEG14z481ET2LzzVUN8BVjF
    LobLHVKWReM+xw8gSm+ak+fRDWa26B7CgDlRQex9Yn1kocTfuinovIzQmKwM
    CWn7VkXsv6AqCyL78q++NKhNC+estymvWb5Ly84IQ+9QzA+MG1KqRhYgHx+h
    KEg0gGqKwQFt2YRkkkZFCtjVnqZ08IHLSoVx/58qViEBZ7xgSOOJQrxAywJQ
    rTIbIr4=]
oracle_build7::rac::ssh::grid_auth_keys: >
    ENC[PKCS7,MIIErQYJKoZIhvcNAQcDoIIEnjCCBJoCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAqEkMSuShrQrhjeUbXkd5fGaeHv+y0WLue06s
    gzTgcLsPv5XPexqemaQTt5jZmYH79S8A7NqJRolXAKC+G6qAtMy2XyA1mGlU
    FxCNGd2H6sPKonrUT55XcCJqd17YDNAEVkLcaHvQed8j+eKLhJZmk36fVD8F
    3hc+YP0e/LYFt3XtYZHscEW3/bPBuVm1YKkgkCpULSxF2NPAksXuErH1QQ6J
    SRl4a9yyiqmW+8ML7grL5rfybvBjx3MI5cPGFRdPMatRCXFYx6fdcbGBhzIt
    msxbcp5PtSRJTOIWxuI5L5FKxTRsmgb7/jmhLP24tye+uht11/AfwSptzDmB
    nPcZlDCCA24GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEJaPCVXeW0sWApGs
    p5dqeYGAggNApAm+oyyZiWjNnbvtNNmq+AzsFQqGZK4ajPQ53xQJeqoN9qgV
    liZzuxn8QvF3WQZek6kC0S+mNkZlA5v0UJRhC1H/li8d9Omza3Qkyi3UjL5h
    hYGhRR2gBWoWHQYPUSJut8603x+xD2tYn9WWzTBzNf1op63j5Amb+L9Y4VbO
    aoT/327WNeVgkMKsv93XzOf86YANxiAKT8E6gxTkJtdUb0wR3bJWyi2lJQak
    Xnjk1PDFinbB3WjwstBCgQ3U75nuTQLyrFHV5BV5JEvt7+JcI6N/LyGW396G
    OwQ9p2vFdZqhJqeuhsejiTroGXAGM0O8h6bmulx4PCPa8troLGWzt1TGFWvl
    mAMhyYb26tAmHF4mRuJoBzlpfPqLn65Hf+RDqyIEon24rSZplsuYjXpsNSOe
    UF5QYDv9eD7CnW+5HB0pzVxe1XCT9fsKkPQMyI2hcvCJDv5Pu+3aWGlmhAch
    xVbbFoPlPuzQzQlNlabv7tt9KWZ6XVK3XIcYn88uwj2MrlVAi3Rgoq7VpxU8
    oppKf59w7Loqz+67kTAkVuuxiK00XwObK7rtioCPbtgGxWZeTG7GPLXk3+xg
    M54GTfxVbXIxqNANXyHRR+l22SADrY5kvAJ2RSJtae94nr+jFt+lJ466kAmz
    ucmWSwmMqGskiCfIzJHvkZAcrQ6sLGO0BGHj7MgMorhCcenxtDfqXW3+ZxZO
    JFoev9zvhQfitVSVlYQwhE5q/b39/icOEfsfV2L9lshhgtcyXM+9+AXVWIrP
    uWtpdD2yszT1PtK1erFXa1jWAG2hgg17E/CumklrOZOfjGrHqlNH5YC3b/NX
    I+l7tT5ougBAJxrh4K61B7azvX6mgm5VZe5iyJANy59e0b4AWtar+n7otHwI
    7sb60aQ8YInhcvhhIoczTHiEZfPm8DSuxGBsz5G3mHa17EgmewSroWMXzsjR
    J4p6gCpuZhnyU+rCgaCZ3vJ+NKNvyPrYEDYXnqXAqXbNnjUoFgpc8dBiilEP
    UDZMZV+RKHJDmDCzNYnz42B5tqpi1Rl52IkLH/+892CPxGR0vhDEUxQvqNLU
    vGJphDf+ODBz1Fosgv1+LQtSBl+RlZRZ8qntNqMnzw==]
oracle_build7::rac::ssh::oracle_pub_key: >
    ENC[PKCS7,MIIDDQYJKoZIhvcNAQcDoIIC/jCCAvoCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAAkE+wjpVgYgQOgFovaUs3kCUg79kNoaO0TGB
    gJVyLAURtB/gg83KHcpfLJ4E7339X0huQ3SKMT5jl8c6vBnKGk0KoFl1RkbX
    NOzEYicy/ZJ9TFUI/wvma295c3FYTEQxssrJSZPRX57H6oUmh9euVXWbORlv
    SeNrWP+hC9O9yn61T3vJZgJtGkBmN1AaQoejYPmDpsEGQCFzbbcYZWejE8Pj
    xCLDE4TLGxlgItdOs++xPvJjk/aYRBnEQjiBbJE5quYqoKk+KKkA1K+jVWjb
    HmNfdHwurHy8rRlE2pHt6EqjThTUV6Hqxb45soiZ7rJgCXVyyTjl6nr/x+k4
    /VoC3zCCAc4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEENbmb1i379uGPDoR
    X4qgf4KAggGg14KFMQEB2nndWUaF5otAZao57BVbcGM60O2drMa4x2IoQTd9
    ehSKCdgIwwtqkzzHIT80RHp0ni6j2y8eG79173zzYeNxiGHxHmFRm0TB+Tv9
    Caz/5+a/p2oRQS5PKlRc1bm+CUiC93T5m1UlqrdzXTZFeavOTGvUKWcyHaHU
    1lVXl7aBXPj9DPY6QpPjHydYCuDe1/I5fa+FMz5jYye6KXU32cBtMZ3Vs3fU
    bEsVzRE1+nGzh2N7D5Q41FpGjOh/ppH1Gz5A2Yp4MHBzWrcCaoMsFPicERZ5
    geO4r8lvn/XvrNjP1MP3QNilU17EJrPy8FogJY+w3dVZDt76JKstwLsy9FHT
    3Nu+PxpV56ZwJlWVdHR9ejV+l0pQW6ZrwMDvwawOzN83DLr8TVCsW/C5YGMP
    SG7bSF7IQpNmbxmEO0MS4P+xFD1kG6BIXlWGjJv1VwVzvAD6HvMfC+t7gTdh
    LJYOfBsjziotW6Cb/EsfoSd8UNnI3ZQs0xNFCXKqfa3eW5//G650ljIYYNcK
    quaJvbm+PDOHIE7wvDduWdL8DZg=]
oracle_build7::rac::ssh::oracle_prv_key: >
    ENC[PKCS7,MIIHzQYJKoZIhvcNAQcDoIIHvjCCB7oCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAdRtPN5fXfeKccDYSA1EGM7Vr9Xq68LDN6SlH
    vUjokjI2lyM+sjsD+bpa8E2iLjG6Ry4bGVZbLPgI36tyzSflQkVV6+OF/ExY
    2mCJAa0ENManbI++kDVoW9RWl5o7cmQZDlNd5Qln6eYmLn7dXc/NJBZsHpQ1
    fBsQP5vU9ME4BNgqQzf4Uwqg8BSUJ1A8vhkYK08/Nf43gmWrMkdyZLd5uLh0
    SfTy3bDJgWA3MKJLngehyEm7badx/Pl7QIGqIwipLGM1oG1n791uBg+PJgxO
    V9TXhAueOyMpqbam+PCl/T5b9qm0c0CNDJt7rMfSMwXCq+j7uHPRARdb4Zy3
    tavNsTCCBo4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEP7tUgbtoD4VhMJ5
    Q8uVNbCAggZgiatjD9JAirhlNzJbYQZR8w4V4LSPqXRszxbmGK0/ESVpb6XF
    suw1mF4PRDXAYGB5NSKS3M71vHq5S0KOf65FRnZ+3jCcYDupqvlJNcU5DJyX
    1CFy/fTJb4yKRXacfHjtpwXYfqdB8Ub9aMbOqRWxM4ABdTo7kwsLMiFrIkwi
    vbHUMgRly0ABgetP8fzSSHW4suvljX1gzrXvdwZumYEuAGrzNCkKz6F0fhhb
    J62/Bg2Psdudj8opFiDBujvyjOX3cpIlMedq6bl7X1t7qUhbYjB2C3Uc2sSo
    lfQoIgk8erwjSiok5QQmOTraHY8C7bfsZPIEJ7uR8Uk9f2OvJzxsMUQ7L+wH
    /85TyE5gNSQ/NrrN+TVVcjX7VuvPzyWHW2uzjmwmuU/j9XmaDIed8NutulCl
    I8A+Q2loncKTFY029hpA/tqyJrlJ6g7o4RrkIciFnebBAY0IwkluBLtNgiuF
    LHwTigN12Mz5GO8FB5i2EWy4w/CnzUKb7t5O7liGcfVjW1fzrt1SyZnO6n5T
    erIR/VTfisMjB4efpgoIc2s0kaO5Sk1sHJEDtwT7SkazkUVEZu4sNXm36pk2
    iD/lfBnb79meYEGWXsNyCCcWi5MHTyjinzMCxD3qPup8Enos6wVCXnnZ6d54
    J5Qfg5kfYI+Z6SHltbpa0oQmXx1lSKCx5F3ugY1QYNRWPZq3EJ0VovSY+Bbk
    HFjWdmXsUmRl9emAJaxnQdZHXfpexmHSUQvNJAwTWe43IAHN91XJy5DRG9xT
    KQcCD1FG8c5t6rrPoxyQRoL6FkpUbE8CYrIGT+PxSIGhdkhoODd9p4ztZjv2
    juV8TxmJb5MJainJHcEZkVJdK8I1L5KACU1++v7E+4XtP4VocMQkV1EjmB74
    6BXfv94gl030rbP4S6iS3KxVL4uKqsAgY34gcnPe8G+qOd7mRDcNLrv1cCpc
    8x3r/oBW+/4SBoBJOCUB+zB6sAlwDD7iVO7j1qpaXO+bV45Zkh2ljP700ybr
    8MJBAuB4A/thXSoOHbvCmD0q3CzisgvhF2zqgcouf9S4qk71BuXwTzAqMCNj
    +m5OWY40qVyRhGoP51uksYI72Nljsgy8gyR5PJ+OS9twJhIhvPMV9d0SZqCY
    90+mFE+3yP1S/xJrtk4PdNOxC6wE5EMYQhtxJOSbNviMmnO2ff2oUt4QK+Wv
    4NB1xKIDHPLXIqQt+o7EulchkLYioTcKrJ2JX+qq1m56KMGQU4PGnI/GKIOy
    7Kz+rO5Ums3QohMPkr9z6RyWRdJWLoWatPjQu9W9S1OHi+JmvS6vmd9r4fao
    x73/5uRKzpIBhrlisAkFRuQ7onTR1P8g071+kQj4wlpPxTcHILtObKSwH508
    BjgPKMsJAz/U+IsuftHcMsh6sMA3zc601kz6AiwtWvhsQUfr01BdElga+59x
    gx58wXO/I+ax9EvxWA1xwYBGJHLsiZXe92wKe+r/d45LeP/RQil7dPGrQ+EF
    kmgp1h9Klia+YOAy0N/h/IMuqG60sAHwakCbZbNzZajKOIasDcM2n9ENFPY0
    c7Ne5eUm6Kp/iv6b8gyyWibUCcQEw5kNSHGlebf6aRhUcogd/axqYWc9QscJ
    OIlvp08gzL4a0gpXYV2iCe7FKvtbZgvbfWWwrSD4DciF6UsH+R8ORUJosc81
    9yIQavlr2ZAA8A4jKG17rHXkK5fJBA5byU8Buj/gVjAcXgAJbUhz7r2F/7gG
    QIQvv/GamMK0Z2Sqx4rK/sjDOKW6LTnmvcRhmNjHDDd3nsHg9qplgXCAjSf2
    MPhH5ZaiDAfxKIRo1VSmxmEEA4Pxg/4diyGWbBmqU1JWPIXYZ/XfAo+U6bgo
    3e/ZVz0jrGk6Z07pqjLHoytDsP+H3SVED6fKDAMVnMsAbWmHuyk9F/YPilAg
    QuX/WLpW7qKbvu/r5XRS61XqmIiCv4BKnqpkpY1WgAUNJfSJ3MU7NtXchFyI
    gfTuSnCMAKzN1NtUPDt8q/VFZPaO983M/0fLs5Qt8q5e+pqE7q/8j27c9rfG
    x/JG2X7GTw9LY085koFY4Qld5t/q3ENNpwruCHjASwZ4bGqZgvJ4cFbKtpFL
    id9DgwwNy32TSRy/akwfa1ozXXYBQK0L1W/k8F4qljbUFQKTedfw5QbgKLUI
    S0PKnbEMoXkNHnJzy76smCPV9+bg]
oracle_build7::rac::ssh::oracle_auth_keys: >
    ENC[PKCS7,MIIDDQYJKoZIhvcNAQcDoIIC/jCCAvoCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAnhQSkX2xCbEPXDYgilRah9Ek9X8vRT2zp+AY
    XbX5VOc9dgBKtlMyxtj+Aig9QumaD/nA6Uqtkk4V/KtjwM5eHDgSBytGvxZt
    FZ1zRb4JlsAVM40AqDFXIC7CS3AmF9eVorAg7z7Lvmkt0XGb/JyRaTxn1m7x
    OOJ7og1ZlzE2V4Ngv/j9i0ad1GhoyJMXRCpQVj/dJpP7ACdkFy9GjMXklIqA
    XhxX2WW8q5wgTkdgeD3ItF/qjgH1Z3Zb+J/mhNZHb9APKN3S9jdcVrJhuorm
    NLxr8RgKM6ZGdMAQ/J+i96ZDYhFmkZ3GiPEYX1jh/v07HwoSAlhg6OloXYhn
    kZ9iQzCCAc4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEHoMiMN5DhNGAeHB
    ieIjYuWAggGgLPzQtVKs837C2zZiz/2tZiAs5nYLAWwU8N3Ak5JisqgDc30m
    sIS3R+DCNSnEamzxFmKYkfPSmBR1JfEUxXtcw75o3NDpMLa69Y7BCGbrJPG+
    ywQ42hIRvKq6IZDdJhAWoy228TvjufA8Gr7WCHaxOsCM9VcxZbVY9DcTeyKG
    /wGuzHt5qLZApfKjuNQc2rP8JLloK2LBISdPMXBf9ddqwCCDMvjycHhN/zmL
    qkC0C3iLPkSvxFkMT4YZDi2gXEx+rso848AVQJJ8CaheS6Z8HiuAJGWPoqX7
    ZLMDo60pNuZ2s2w1OFXuBIm6ZvptwU01Ky61VsuGJIHVKg3sbNZMdKYDuoV4
    2YcaWwuwrKGqU8BDPJfm/NQpMc4H140mbNWXoIiDZHAXIGZC/wpEoOy+I6Vr
    E8CSxWlUZI9zOai6dTJBK/qYEfHnNZ1FlwadEzpIMLdZ4D7V/Kkk0DlZV1Eg
    2NKbDSAE97RuqtzVBnHDt+xe4QIs4eMyKtkDiBYsk+a9FSPOd2NTgtciA2dG
    uiRLhTU5lmsIGp8xqzH2ewNRmwQ=]
