classes:
  - profiles_unix::gsc::oracle7::rac

postfix::enabled: 'true'
profiles_unix::gsc::base::auth::sssd_auth: 'true'


oracle_build7::kernel::vm_nr_hugepages: 3000

access_conf::access:
    - '+:root:LOCAL'
    - '+:(sa-local):LOCAL'
    - '+:(sa-remote):ALL'
    - '+:(gg-cgit-dba-admins):ALL'
    - '+:(gg-adm-gcdunix):ALL'
    - '+:grid:LOCAL cgeisdb1a.sherwin.com cgeisdb1a-prv.sherwin.com cgeisdb1b.sherwin.com cgeisdb1b-prv.sherwin.com cgeisdb1c.sherwin.com cgeisdb1c-prv.sherwin.com cgeisdb1d.sherwin.com cgeisdb1d-prv.sherwin.com'
    - '+:oracle:LOCAL cgeisdb1a.sherwin.com cgeisdb1a-prv.sherwin.com cgeisdb1b.sherwin.com cgeisdb1b-prv.sherwin.com cgeisdb1c.sherwin.com cgeisdb1c-prv.sherwin.com cgeisdb1d.sherwin.com cgeisdb1d-prv.sherwin.com'
    - "+:sa-qualys-linux:%{hiera('access_conf::qualys_ips')}"
    - "+:sa-cyberark-linux:%{hiera('access_conf::cyberark_ips')}"
    - '-:ALL:ALL'

oracle_build7::rac::ssh::grid_pub_key: >
    ENC[PKCS7,MIIDDQYJKoZIhvcNAQcDoIIC/jCCAvoCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAUV9UwjZlPaAGPle65LqQGBiYTs1oI3daotiZ
    ZR8p0m1W3BVs9xsz8qLaJ20vuE1Jo4F7AUP3jsV25NpIWkxUDcBrKnwrMiea
    qGTkZ2ZWs/1duodDuyMmKF2CwWU/gXlkn630UKxzrXaxjOwLMIo99vvWKUqg
    6SqS8PdcOHlOrWvKnK64M+hPH1jfPDHptQ250/GDPEqxyouTuI54MXgD5OD8
    j136fnpXWFkFhhnBB/Tv+JRRwLgZjwX2kADkO7V5xujS+OXkfJFwepS6O6Fc
    BizEV6G0n45oWH6YJBHyK6ysZZn1K5pPnazZheNxvs4F6ZNbpnBI5FGq2whs
    oNJjHzCCAc4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEA8gN3CGDuHxMuoK
    C8TZE/WAggGg715/1N9hC2yjn5YFXMPG5LmF5wZqFkjH/l7ZEuLu/CuQETP5
    2/Kh+GlGkRaO6y/3r3Gr1bzAV4HpiygdxZCT+axVAvSWaP7KFLt/GOR2rg4A
    J3l9im9PEWDcUylrYzoH27cC2LQFuAupwjapkyvcpSSI1uC9rKeE4Sm45fTz
    qhWlDimeJK2DMeAJqgCtax+b2SGtOQYSPrrww/zjHj+pyu4D5v4yQNIEfGst
    +w75p9r0d85MSOtxtwKezKd140y01Nz78GD1F3Za/32NxXsgXxFe6CoMmduG
    GbYr7LiS6pH06FuWLQWj7zcXdGl4kb8knHfgORbJ353Ji0OaDuvuMLAcUhRJ
    0Y0iNo+urd9zXZ4UR1KVwz/d7IrMHJJ5zXJru562AjtnIfAE2C+tFqhAQStp
    pIRSkJvkyntISiNdFf8TZSLbo9lPfQ78iMxlnguU6VuMJfVugINUmmHhA8Ip
    jWmOOGME/agLF9ztlbMYMqZqhK33s79pyvVxrxVimqz0kgxJtCdx/dRU0w2y
    nsavh9lOvhLzxiME5b0kUMySt30=]
oracle_build7::rac::ssh::grid_prv_key: >
    ENC[PKCS7,MIIIDQYJKoZIhvcNAQcDoIIH/jCCB/oCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAaRcrB0jYmLgIKXs5XlvqBgyXv6f0r7xPyM18
    120+R1fny7oecQpdZnAPqsP6hYAGfGYGo1Gnnk4X7XSIsYIR4VzqvEG8pR54
    QBZKRXZXvCL1KXToaVabqni5bvC1uwqIohIhe8sGjM/afoXw+qnaqt1cgEfx
    wFWE9iHIiDTskhLbhqMR1Ey2ZKZew0aLec2C0fE0sgwSsWoE3OQMVe7ymoHS
    k/McuS0p5KPiz+n/aoNRQjUwlxc2eXLTOdHeV0I49ZMcfvtu/Pxv9m2MWhb8
    L+ZMCXkRdZo/tXUotMB0ah01vF7Vq+8QNKvXNCshkMWd9ih43I3p7MWLmNVM
    9yVxijCCBs4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEDh7lCzUOcbZnjA9
    eijK64+Aggag7jilq8geYMsVYTdNov1qNWkZYJP0REvyXJgTmrIUjXCc/Yhg
    MtHF1LS0XYph2zX4n31xESWBHVHiPb157Q72AAq1KiTdJ/AaOV6QenO6gy1a
    VTSdVURyep4okA/zymPWcR/px2SN5R6wQzaF2IzQmL/pGpDtFfnrYjWCeuqg
    0GKLz0B7jtlqHore8vygBVS4BNZtPHAje8GlVYpWZp2t/Uy7/kast7FixACn
    hqP45P+mbSTeLZOteMDUszdWjUPo+JTXRPiFbILI8FXRtBg6l97ocHmZGolI
    gwhC3TuDhcwXJjZmwyJgghIKCpk2C5nqrq2mn9vwdAfKGqZmYlzFONpEqT7K
    Q1+TYXsJJT7qtowLwqzARlfH/DRGtoHKEbVTSmArDW3KrSgIspUs/4xrX9fz
    ViTkPsuM7VLywnfnPAMyokibTYEpt5h4pwqwUpbojlInZ9cV5Y7HCFK2QOsJ
    r8/iCy74Nvgg5UrHeSWhpsuLNZu2LR7TedZduUf6fUZ7lEpww3KGvv/dU7Qp
    WRDGu8txrP7QoWoLk+FiEY6XcktuYRr7NGkeXvIVcBe8PH4oby90htjT/344
    9qyUheaLar/CnaCK3SXgo1D90KEOAt65fcKXDNnNxS7pXR2md7jg+CwC+xYY
    X5YofLxkj532uwsZ1gY1P14aPAqHIleODnLFrD7jPdCxwqGbA8JbAJI42T5p
    u4xpSebYFNDXWAZuZjLT7Dxl8CZc4ioek0AStpwr4Rj7pFnuAhVp7G6PcIgK
    hN7O0JJRYvjmdK45vi0UAcKCEDhH5tL3WaIApV3klo5Sia2iA4vBhpST1f8I
    Er86NXtOvQxFxCdxrYu/hZg37/E2QVMPqx3L6TuhM6AK6aKmkPvDjcrOplkF
    PCmHx4+yBTI1oUQP/F59WYes4vzQRqtgB7Zwi1kSx3QADfQt25wKkln0cuT/
    iBNIlhcJHLwb3Zf6uWJavd5Yui6mVfVPAFy4Ayeo5rPoNlLw9NvO060B0SCK
    PfUcSCBId2zO5XMmoI4RjVB99Jpkeyi7f7zR8xvkUASXEF+IF9zEmV/Ms8gA
    J57ZMDoo/ygUn9cWwv8xI4saEq4jzOb9iDTTeVe4QAVEYKtZlHZgWoWB/MA1
    EgFPEmrbjPsDUdxghkqXOOBnwPeLk9gui+mi+umhlzBpa3pHSMS++SR5E4Qi
    4Derdjyh9u9sYIiC22xC26w45QiFelndExPNDNUOTbRteUERgcJEcYveK8PF
    lGTlf3/qTDsDQ+AHk5fuIP/dCQPf1iTvoWmBPYIvFkxNDmZLSbyDDJlwX8VW
    7D6mNUnIn9EI5JFpE+n27E27X+Hg+Cq4dpnOekoL9ioLwnagP7bcPIk28W7Z
    LoFCeyqIomKotbXaW2eDgjbc1cjV5kfGHBJzMShNjv1fF4c38Am1oDUu9gsA
    RRY0uRK66ov1qJVivELBEe/Q4aD81rkah29C7ozCJN4CS1Qdf3K0xNJdtRNJ
    IBCx/858TVl0RvgIElF274O//gzwjJUpmBlYNdVR9545zsoOIV3B0YAvDmiI
    03azk9PVzpkOlqcXWrwgM1J7TJkoICW/+T8dG4XdfsAxO77Q41T69/b3tbZr
    stZ7TDhX47fEeX6gWf2gQWq3KB19ot5hhkRtfRIYF8NvnqweDa0M9irti8F0
    dSlpJsH45uSsyyG2yM+mTbw5PCHyzIvLf5/j3LS+B4TIi6ujNAp6YGJpLVbz
    E1/Dii9Xf5kBUTTxZyMKOo9zCS+l5VBYJdhB5LsHQTpQ0Ng0UdN+GOoAa/yj
    YImmEfqlnBjnHRuWh2bIyIJfkE9P7LTwERTZGdBF4PlQRXBT70G23R0uh29p
    IIRSVwIMzdKZzqp3XYtuapDrB+zSU+eaKsj++nb/RSKj/QkR03O2xshXgLgs
    AZnIyfvE0Sa1wjhpsScidie32i1HrI/7Ub1CY/m3nY38gokuRHjp54xZCHP/
    At/D2S7bOXQ4tou3lrStVH+EGkTxTggO55Yuyos6plA/3uZ7ei1ESa3+GbcM
    +PzcSrBUlmQkikx/Fpaohsh+EI5g9gYQ4jAJWdq3KmswZ8tWtdkWVCM/TB6o
    OuSd8H88EpY8OFlbCO9dZiXwF5nLem69uiZMIjchM151ptsAkJenxcFg9KAk
    oDZIHsIR4fFELjKNBUoxVv+jI/KrQ5kxvOmbJ/XssWJURN/YPvdk3/pPHMfa
    tauKfSzOBHLjwshxztap1+ugB0LLyM6CkRoq7hNayK9owA8Z9IQT2A==]
oracle_build7::rac::ssh::grid_auth_keys: >
    ENC[PKCS7,MIIDDQYJKoZIhvcNAQcDoIIC/jCCAvoCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAUIyd89lygBC4dwxSGtGNWPibZ+kWQwzXRVWN
    7yHi25+Lm3exEdEE22hFE41EKa1H2Qb2BWNLq2uAdKOaKStvh6bxKEH3x2ny
    ju3C3FNENVaGh1FCRVc79f4BtJDyhHyFkG6Ka1wQN7cQW4QslH1Gpd3PumEQ
    CthM4J7/v8QN11lCArOs70O08y3/1fumtBpMdqu9mAHAQvOQBobttNq0jXQd
    /tVGgDiLwtrmLhsBZx/vW6skYLRev9C6ae0gDQUR3BVOlo7fhhZpCRN4O/V6
    RlGVoJbpiq7EUxotF7JapFcoSDQQ7oAc6vPNbDVP31SyM51pcDyulBHrkcoH
    TVKFkzCCAc4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEELYWp7iypOuAJbXB
    ImUj0u2AggGgxQoRPD5dlcF0CdeYYgEHrImCg3OGSIrGx7QtHYHtCJxFc2CJ
    FdwavTCsH3mN3EmI006gIW19xOrblT8+nbbttNEi66sXO5CxVTatBtEVJGsB
    MJaOBJCr7jRM/T0o0OCAJBouqCNNtsk7g7UErYFrmb9Uqb8wfQsuM5sUw9S0
    esqb34ExCycD/0Fu01McdebJjV8Hb6IzhvlHpHdTCBugjoN+8OiEUZEqCQ9i
    w6lwBkGFrZbP2lIiqa7KbF0s61zEmulQgHI9+7tssj+v0uZjfF7OA+D/G1HP
    sUE+S//7UYRHB1DdR9KMJyvTvxW4dtRkBE+lyPQqITkxoUKxkFVyTHFZeuYG
    MV0k6Z+h9nZh1uZaTbu6ed50cag3On3QaIp5b0NFspsLiwzRw2rO/vYX/fCP
    h4O2mnqGCYX8jEj3MkKcV8JIoBNpMLwM56tjxQaHyKatRKHwRZfDQ3GsmRBE
    /azvPlB74MeAu+Y7iyprf73EwkcoaV6QFERi9ubV8vYXxvxsOMYBX2kqhltV
    RdUeIj2+Lv1z/JgSDdLgAkRtiws=]
oracle_build7::rac::ssh::oracle_pub_key: >
    ENC[PKCS7,MIIDDQYJKoZIhvcNAQcDoIIC/jCCAvoCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAE5ENEQDUfHluAuPQCDD6rwmLA7CLQgOWx+5G
    Qs+0jv0RcHeesZK2dqgNiQ9NQH3sNcJK8V74TuyaDnVxyuBun7TNqIjglNYY
    CPK9qDDnySmmNIISQ/b95lnkO2+xgvEbn28TOaCKoFQLxfJc1jsn9S1AYx0C
    eoeovcR2VEYfResRN9zeJbyT84QGW82Wd+NfAAp5nuChiulzA9/oiXJgYmto
    2sMOrE9zUCY0eqEm+XNcZTUYtbwDPhuGo2tYQ0G+u2nsSI5iJoFe998kcjun
    Gh2fdUZSdFUmHgQX6XKNtj2rmy7Ocd6qFO9jI0MNYCmpN14+OKaxtTWBwxZc
    cRJFQzCCAc4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEAty0JtaJO12UT1y
    ZxfeTjWAggGgvN80rmsudEO+7RrBjsMnBgy1APsa1x8XVGfp9LDMGZlcFXe1
    O4LaJKluk3zirQ9KFu2M4bZPWF/9L5ELis+OAlOSSIX4LIBXmPpnzBB3UTY6
    wTfJFxejKDDXfAaFdmE9pW4uVYAvq/QWjhcZ9ekB60+YPOsZ5tRDdUDbf/0Q
    R2A0jeIU29XcfpavS6fuP1g/M+kj75RSKioGGsdzUGKmXcugbelLswJHIAJ0
    KTLwKbMQBgfo0TphE/aIhcHK0hsi/OVzVVIlmTOWPM/EnwaQl5dTmr2TTpqE
    TdMaCVuIbPa1J/t+EiTtCslJpMvAk0UZZHaptZqWUTNz20KTN7Gj3ZjIIGMq
    krLeEWVafHw5//5ajRb+mvZDShOJJ1E9DOBNe6BFvTCiOjDKYwSIojZFbQ45
    HdGH3G6lacmGyfvWP5ZLNhzKeVQwMM+g3X7hqs84CCz98HtxYx61qLwZEcuU
    jzQhYPgbzZrSLhL28utta7u/o18nDddS5rkirt2DU4iDHGowBV47FUULn7Op
    TfvrZdfsVICqDdoZb9cWa87GQ3s=]
oracle_build7::rac::ssh::oracle_prv_key: >    
    ENC[PKCS7,MIIH/QYJKoZIhvcNAQcDoIIH7jCCB+oCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEAZ8u9XTD4BF45fpZarN9nRqKPSocH5M+JCReE
    cuEchY/DSsfpbOXAXhkqR2xEa2FYohWxbtXURdRK/A+qq14RvJacQVCWp2pU
    bww2a757tRE5Y/BIJiZeU9L/P1RTvt1qn94gqT+H2wDTDYHXMB4NsMERS4LV
    ACV3x73m8gAq6/88Lvdb2icyHaxgAcfQtxBpVMMspr2E3PnlMAAoohdaJXOq
    vjoAol1XXktuH4iCfOe56vpeOamFMJYlbUmUEN0VjLXzXXLGZYDh7PtdmvNs
    GZDS+QncBuvyWIZ/MxSsg83lhjFMcxWd8EPYDQHluLioGVQbrOHUDDgkWAw7
    eC1TqDCCBr4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEHFBVcQ3RmhZnVwe
    JO0Gy56AggaQFpFj92d+snDDs6HlDlaPAv1z/wQEMDw4kpiUrEUc0RCK5zB0
    Omr4Y9+JJvZdS0YlL3BlNkYinjVcKFcOCjUL2u8z3T5sc73c8DlAu0e/ZNjd
    YZD5atpGodmUGnYxr2wvWY7GLOOz5Ezm6lmYzMxw13W70OW/3z1AM8d0cbcn
    ltuNv/5DQVPl+LHnzZ0/yxJXTcEX06lcddER0/ewb7SBWmAEOG3oOZvcjFlx
    Z/Vz2EecM1/Ixu60hSmLYbH7EIX6K18iwXJMJ5PdZGJoxcOKewgnvNf99SXr
    HSv1MW8Tfr7pIWkYKe0z88jqkWaIkCfVh9I3LuhQFS8Jnomivkiwbnj4L0IW
    jAw6QK6n85MvxA4X/qJE3FUe/hlek5zlQamXG897kksfikV3Mn1ObL7Dfm1F
    Yx6nWmzbc5fsxtVUywQfLQ4ryXuPCpelYV6llc0tSEXFQnueuaufE2TR3ID9
    F/duL65WiQgQOLM0vU88tLsyTCxSJBPXHr1bMPOHHVwKFE/32OofYA+ahKb4
    QCWNYnDxlBXUxfjd0Az1RmdiE5ABHW7LoNe1vOS1L0UwpY4vydvx512/FEZf
    hpwpjDCKYUWAXeMJdnhkbqkOQQ1HRQ6CEpWJFiRn8w0YQuiS6LuTR6afrhkQ
    SV+8/xLyClsp2NV1PgQTD0Y7CqN1Kk8oW9Tco0AhYz02j/e/HWfF0ZDubHbM
    W6FLaZ03FGHSo+faZMiuOQZpcyBQUOv8MSOopKArX3xWlan8Ql8N70e7BHcb
    OXz0WclMLwVsRJnC7qR/ZJ/TxtjDWF5yKf6KdrCcugBqDg6W8aX5U8MhcVaX
    QLQ1zXQo3Rcy0XbuHwM74PYykGV2eRwmksgGyFq+WL/fShoOAyQvHtfX7X2H
    /t4RCc/GsP/KxCCurw3uJYmNfxBiyQdrA/3lLJytyTGW8gy9ZflAxn+d2mif
    wy5lS6CAgJuYHBDssb/XCzHaiCnWkaqXoFk/Zn4neWMAoq3Q8Pn/WannuGSZ
    mkjZHlNlWoPwPTgIsIZOWeTIbe+huykW29UVVbZEW2nfR9SGaVIAWttOPEzy
    F9EcqhUEVY0YtoK4GhfMhJgjzQYquu+Wa6hQLwjliir/HsZ3a8hsYWYqj3pJ
    Q1z9Lc9I4XNkUSVCX1KaKWzxRZ8Y3LppbnRxDj8ux9V4aDh+561cXgQkWiVI
    oUVs7/YC1JdEubp5+5q8STWiJO6tTloXIoIASTVHUjmhG/cDGc+K7MHuSO9T
    97qr+g9au8Ek18DNTx3GpZAQaS3hj1wvgARhqqhbbgDnRA4BKUWv/dKK59Ea
    E0z5sZy7q68sOaewWeI7M4j+d2/7o/7bSk/QcuXcrhBsA3b/okWn3SIjAU7j
    0NC/P1xSZS7RnFXfbUBEjlAcYMft6ZfUVkmhpYOM7qPX6OyTAxn4zocdGbm+
    onxxquMiIFux3Qk95eUESUyd/s4u3EHIdlwW0g2ubHJikjZN7Vren70eN9Ht
    GwjwwXX6pzihWvSxxmIO9mh0bYduwKrHVHU/nJsaJ3fymkIgRwTxUSnuPj+E
    1Si4zGYxwTiQSDbxYdBm9Zrv+aTDHWP+E/HjSWV9tctDkcFwDct70/mNnAri
    hji7ReMShO4fgNqyIp4K7arRcOQWeJ0vyHqtliGRocftd/6sy0+R4xvfF3vp
    m5wFdJwbdrIrnvsW1vSEshC0HGoM6rwWuOUW8WCKko5YTs/FQ4OGDO5g1Pwr
    2s9W6ppFK3m7/q9OWLb7VOOVH/znCsMuvjQqO7e+GrjRTNlM+gOmLybJscgS
    MxbQkQyEvTG7zlQnIHtRA1TM+afO8+buepgnal7HAqSnslBzDe+zQkGKqQQo
    /a/0o03RtHrqRMOPHndiDF4tMavGbtszjVNTwb9xblK4BG/bjp4HF+4vHa9J
    k5BHlRdWOiaEMQCz4L3gV4Jz7emG1MswwhPckNvNP+Jgnrfpdr/4X05WjEXz
    g/pKKGI0EneY7wVMM1LUdweXTV8VrTX3MEdSdlUA7jy4XR1nIf4MT5pge4bC
    hFdRSmBVjXqM7xK4M/NzJzU+N7YuBhWIrL2hyGv7MJuXJqWFW9NUFr62/pRB
    yLz1Vn/VPDRaDpQOHzj39rUt468NB+VbcS5PcWhVvrjcvRw5E1DhjRuGahSp
    OWLaKDPSd/Oe8SYjVZmVj9Ty2lnchPLSVWdAr9lOPpdEE8P7ErvW1Vn9w85a
    PwoLuw5sOSbpy8Kz29lkzh/1cUzVeETA]
oracle_build7::rac::ssh::oracle_auth_keys: >
    ENC[PKCS7,MIIErQYJKoZIhvcNAQcDoIIEnjCCBJoCAQAxggEhMIIBHQIBADAFMAACAQAw
    DQYJKoZIhvcNAQEBBQAEggEADtv5HiJvTGqzD0DMKyaQSOxPT91Ap2xmVdIa
    V1zfqizcIjjbi2m41S2zH1mOKGHqcW/S9N5symBxcuZnawZhCos3rhIGhQf8
    oQB+Xi90TV0tiYgnyyLyEoOMqKVTcdizdrUu4CQaZpzVwiCGb/KQi+bQvMMx
    xuxU319foi2tNzvW7N1kSiaxnIfoUkJsrOe/hvOXxnZT+qHbiLK1o67/tio5
    mlaM92d1DTvdVp+DmjZ/k8wxn9lyQFoDt84lzUQd3e1oJX77dK9qCub2TD7D
    0B32FMhAONnlkaM4zjZOLcUUT9b5v+0T/T2lXxuMDtYqjni8Oo05lHBtJCBA
    702s+DCCA24GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEJdlJY13NyOATOOc
    Hm2Y+niAggNAiDWEVrx80xfZiLNrp+phnZyAIXwSLR4WeavAWnSWdjOCKCVG
    tZt/fGh4Lt7Tp6jdHcMmVOp8Y0Mll4fuIKBy/SWcegrDyADd/Cs+j9b3X13R
    yBcSfAs9W7g7c7roupeW7j9tYGcnHilvEyC1W7o/CsK9NwYHrzVg6hXYlWV+
    SaoP0uLdCwzkoYVS/l4rLMTeL2Icvw90bAsGpErvn7VEWqJ5LRAT2d0aorV1
    nX4sp4WWK/3BO1CLWKvOmhahhyy96hu4Da64OnuZRYTL0sm/tuRUq1hrBsEZ
    ZozxgtN4/6giSstMCNxWmuwke4oR7BdheJqEXGjAZy3YlwLOrAKa6N8ad/ss
    ZMcmpggH5s24abfVDZUFft77tCZsFdm5HynyVY0SAdxXiynlagMCjl9dkpEn
    WPHqXg5QQGe9v/FEDucottyImBXeSUpP96hQStxFPIbVVVCMu5CLd4k9XpEi
    Ndy5lhi/tNE9JTHGgEC1YMhE2UpapLMqOvK/yIEFwaDh09cxMFy1fRuDeZ3H
    K+MRrLXFQv0xlVa1FiIxIpFfvTYzZDaAvaizir8AptsnOspE7bd2VDxMoPPO
    JQu6uDbA5fBZ5ZnoJJLZuCnPDTFfDe+jy2AI2IgA2QABScZY52FmjwUlxhKo
    jyZHzzDL90rl82iZfLH9pLLm9rr9WPo1ndGF5hRazpbKzC5q65tdmz7nr53w
    KCussHAoAGK2XIyZ6gzv7iWIPU4pmPA718BBuzw9yku4nAld0Iyhli37JjOU
    Kw6YDSbsPqFmeDtAQDUqjp5hLMKWEOdsPBVbRng+93vbMF3C2AC3CCejY2Tg
    ulQCSmkU40loZOVhjBo2Nm9dEFTxHo8RMvkkEQut4FhJDo6y/Kx9KqnZpcKb
    jnSjiI1uJDEssdrpfN1KMLXD1vM5fV0PNInH08nI2hNCLmOXk1xJNp7RrX0M
    PMVMxbJRb+R4B1qLXK/uZIzU1u6MjYnjkkl//oZKC1Mt2b9YhpzZejAr/N+G
    M8Op1i9V8irAsPzQkkuyR167cSA9Nu3cYRSpfGDb9RRhsRvjhuK1NAu13CXw
    bvagVPKAMX2YtchkRb6NoZMsucvW+BWutMyGTKBz3Q==]
    3eVXVzCCA24GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEDc8NmVOcpQU5Kdo
    k0aQ+6yAggNAHjkTtTAEI+luxnw14OKQFeKkN6t20MIZiu9gKJccIOxFgFD3
    i0eXQxyzYxEEDi7nqIdqREMwYsrOUxXZNmvSLQACEmg128PMjhvv3zsGwXu2
    /Nh5IDGSYJmDzZx+DTehyJYR65W8BIrathlZcvXiRSJ4dc8FnR0XZV3s7oIB
    q5C3ilKsdwI1eRlc6Ay7ihUfZeWFF4/mBygmeaRXp8ML/g7OyUfw45mrP19H
    C22aaw/w3MOA3L2FhP5FQKRhV2/BLmmoCZ5jJpFjmvu3wW3y+RYwQrNvLMFM
    UTN/+8gHNtAzKoMbpdEyj0spURaQUiagqzeN7iYAhaPN9oHrBHRnnOsbicOF
    Wp5qfBrLXW+KZAKWo6eHGSTqqmtrK4jecDoJ0SHBBkF4rBlskTP3NGzucw9C
    66JqaYuIG0YYfj2Fh4B+lJgTWmFc2rdmateTK3BnIJ5LP+X6wVtB2B8OCmJa
    dBX/O0+UDwzPRUJW+GOczGheygoRyafmUCF3FH8ThBIvwbf1rIP8WQ9iqPz2
    1N35RaIf1rzA7leXkPAd/YmHrbca/24JcGYpsKPHN3PNZczIUIjtZP9PLfGj
    /sHFGUkfzi5V/rbJQ6R5wvhyj6mqxnbS/wgG0M5OBYJwjxS29wUxV821JTDY
    T/o/Y0t54j01T+NAD9veyif/aKNaJoBhPfbjACCrH590CE0awdqUpYh2GcxQ
    lRcq3/jdVyUeGKrFKqQujwFLxlE44fodGa191SVeFqAHP50ng2P0Lm66cSUl
    CxCRcZd0yM8wwrtuO07dVcLAW99mgmvvnTfZr2492p8ERlAfklpDxtFR3OnQ
    8xakAYWL0eISVtVrhStbmuZKwCysMrgVXC/7lHuR3BoDN4Q6JyE2NErGtvmW
    U309t4HaG3HAUMGeZKpwghyEErY+Xkbk7FP0tVaDD6JaTbElKgAxl3Mb0il6
    oO8DDua7znG+QpHCM4zsigw6wZvm0FG4RGOKN777s/WdJ1hgdEDKCt82+x/t
    g5oQkzmpDJo0lcYkGGZb+F6ixHzD0Qa9pF2AD3dphtLxZ4tR+LeMXb+cg5Vx
    jT3KT/e3U74okt9BnOJ0mRF7tnPUZpMwOcKRol9opA==]    
